import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {afterEach,describe,expect,it} from 'vitest';import {inspectHeadArtifacts} from '../../src/fngk-head/artifacts.js';import {remoteInstallCommand} from '../../src/fngk-head/install-command.js';
const cleanup:string[]=[],commit=execFileSync('git',['-c','safe.directory=/workspace/signal','-C','/workspace/signal','rev-parse','HEAD'],{encoding:'utf8'}).trim();afterEach(async()=>{while(cleanup.length)await rm(cleanup.pop()!,{recursive:true,force:true})});
async function artifacts(){const root=await mkdtemp(path.join(tmpdir(),'atlas-head-'));cleanup.push(root);const body=Buffer.from('archive'),checksum=createHash('sha256').update(body).digest('hex'),name='fngk_linux_amd64.tar.gz';await writeFile(path.join(root,name),body);await writeFile(path.join(root,'SHA256SUMS'),`${checksum}  ${name}\n`);await writeFile(path.join(root,'version.txt'),'v0.1.0-dev\n');await writeFile(path.join(root,'manifest.json'),JSON.stringify({protocolVersion:'atlas.fngk-head.v1',commit,artifacts:[{name,checksum,size:body.length}]}));return{root,checksum}}
describe('FNGK head artifacts',()=>{
  it('requires and verifies the architecture checksum',async()=>{const {root,checksum}=await artifacts(),artifact=await inspectHeadArtifacts(root,'linux','x64','/workspace/signal');expect(artifact).toMatchObject({checksum,architecture:'amd64',commit});const command=remoteInstallCommand({artifact,baseUrl:'https://route.example',profile:'local'});expect(command).toContain(checksum);expect(command).toContain('sha256sum -c');expect(command).not.toMatch(/credential|authorization/i)});
  it('backs up both user and system installs before replacement',async()=>{const {root}=await artifacts(),artifact=await inspectHeadArtifacts(root,'linux','x64','/workspace/signal');expect(remoteInstallCommand({artifact,baseUrl:'https://route.example',profile:'local'})).toContain('fngk.atlas-backup');expect(remoteInstallCommand({artifact,baseUrl:'https://route.example',profile:'local',systemScope:true})).toContain('sudo cp /usr/local/bin/fngk /usr/local/bin/fngk.atlas-backup')});
  it('rejects a mismatched archive',async()=>{const root=await mkdtemp(path.join(tmpdir(),'atlas-head-')),name='fngk_linux_amd64.tar.gz';cleanup.push(root);await writeFile(path.join(root,name),'bad');await writeFile(path.join(root,'SHA256SUMS'),`deadbeef  ${name}\n`);await writeFile(path.join(root,'manifest.json'),JSON.stringify({protocolVersion:'atlas.fngk-head.v1',commit,artifacts:[{name,checksum:'deadbeef',size:3}]}));await expect(inspectHeadArtifacts(root,'linux','x64','/workspace/signal')).rejects.toMatchObject({code:'artifact_checksum_mismatch'})});
  it('rejects artifacts built from another commit',async()=>{const {root}=await artifacts(),manifest=JSON.stringify({protocolVersion:'atlas.fngk-head.v1',commit:'0'.repeat(40),artifacts:[]});await writeFile(path.join(root,'manifest.json'),manifest);await expect(inspectHeadArtifacts(root,'linux','x64','/workspace/signal')).rejects.toMatchObject({code:'artifact_commit_mismatch'})});
});
