import type {ProjectManifestV2,RuntimeManager,RoleKind} from './project-manifest.js';

export interface DeploymentAdapterInput{files:Record<string,string>;environment:'development'|'staging'|'production'}
export interface AdapterMatch{id:string;version:string;confidence:number;summary:string;evidence:string[]}
export interface DeploymentProposal{protocolVersion:'atlas.deployment-proposal.v1';matches:AdapterMatch[];manifest:ProjectManifestV2;runtimeRoles:any[];schedules:any[];storageResources:any[];resources:Array<{name:string;kind:string;required:boolean}>;warnings:string[]}
export interface DeploymentProjectAdapter{id:string;version:string;detect(input:DeploymentAdapterInput):AdapterMatch|undefined;explain(match:AdapterMatch):string;propose(input:DeploymentAdapterInput):Partial<DeploymentProposal>;validate(proposal:DeploymentProposal):string[];observe(input:DeploymentAdapterInput):Record<string,unknown>}

const json=(value:string|undefined)=>{try{return JSON.parse(value??'{}')}catch{return{}}},has=(input:DeploymentAdapterInput,name:string)=>Object.hasOwn(input.files,name),includes=(input:DeploymentAdapterInput,name:string,value:RegExp)=>value.test(input.files[name]??''),match=(id:string,confidence:number,summary:string,evidence:string[]):AdapterMatch=>({id,version:'1.0.0',confidence,summary,evidence});
const nodePackage=(input:DeploymentAdapterInput)=>json(input.files['package.json']),dependencies=(input:DeploymentAdapterInput)=>{const value=nodePackage(input);return{...(value.dependencies??{}),...(value.devDependencies??{})}},packageManager=(input:DeploymentAdapterInput)=>has(input,'pnpm-lock.yaml')?'pnpm':has(input,'yarn.lock')?'yarn':has(input,'bun.lock')||has(input,'bun.lockb')?'bun':'npm',run=(manager:string,script:string)=>`${manager} run ${script}`;
const manager=(input:DeploymentAdapterInput):RuntimeManager=>has(input,'docker-compose.yml')||has(input,'docker-compose.yaml')||has(input,'compose.yml')||has(input,'compose.yaml')?'docker':Object.keys(input.files).some(name=>/^ecosystem\.config\./.test(name))?'pm2':Object.keys(input.files).some(name=>/supervisor.*\.conf$|supervisord\.conf$/.test(name))?'supervisor':'systemd';
const runtime=(selected:RuntimeManager,restartPolicy:'never'|'on-failure'|'always'='on-failure')=>({manager:selected,durability:selected==='fngk-native'?'ephemeral' as const:'supervised' as const,restartPolicy});
const phase=(id:string,kind:ProjectManifestV2['phases'][number]['kind'],command?:string,timeoutMs=900_000)=>({id,kind,...(command?{command}:{}),timeoutMs});
const role=(id:string,kind:RoleKind,command:string,selected:RuntimeManager,args:string[]=[])=>({id,kind,command,...(args.length?{arguments:args}:{}),runtime:runtime(selected)});

function detected(input:DeploymentAdapterInput):AdapterMatch[]{return deploymentAdapters.map(adapter=>adapter.detect(input)).filter(Boolean).sort((a,b)=>b!.confidence-a!.confidence) as AdapterMatch[]}

const simple=(id:string,detect:(input:DeploymentAdapterInput)=>AdapterMatch|undefined):DeploymentProjectAdapter=>({id,version:'1.0.0',detect,explain:value=>value.summary,propose:()=>({}),validate:proposal=>proposal.manifest.roles.length?[]:['at least one runtime role is required'],observe:input=>({files:Object.keys(input.files).filter(name=>!name.startsWith('.env'))})});

export const deploymentAdapters:DeploymentProjectAdapter[]=[
  simple('docker',input=>Object.keys(input.files).some(name=>/^(Dockerfile|compose\.ya?ml|docker-compose\.ya?ml)$/.test(name))?match('docker',.99,'Docker owns build, runtime, health, networking, and restart behavior.',Object.keys(input.files).filter(name=>/Dockerfile|compose\.ya?ml/.test(name))):undefined),
  simple('laravel',input=>has(input,'artisan')&&String(json(input.files['composer.json']).require?.['laravel/framework']??'')?match('laravel',.99,'Laravel application with framework workers, scheduler, migrations, and writable storage.',['composer.json','artisan']):undefined),
  simple('sveltekit',input=>dependencies(input)['@sveltejs/kit']?match('sveltekit',.98,'SvelteKit application.', ['package.json',...(has(input,'svelte.config.js')?['svelte.config.js']:[])]):undefined),
  simple('svelte',input=>dependencies(input).svelte&&!dependencies(input)['@sveltejs/kit']?match('svelte',.96,'Svelte/Vite static application.',['package.json']):undefined),
  simple('fastify',input=>dependencies(input).fastify?match('fastify',.98,'Fastify Node service with explicit host, port, and readiness semantics.',['package.json']):undefined),
  simple('next',input=>dependencies(input).next?match('next',.98,'Next.js application with standalone or Node runtime output.',['package.json']):undefined),
  simple('nuxt',input=>dependencies(input).nuxt?match('nuxt',.98,'Nuxt/Nitro application.',['package.json']):undefined),
  simple('postgres',input=>dependencies(input).pg||Object.values(input.files).some(value=>/(?:image:\s*postgres|postgresql:)/i.test(value))?match('postgres',.9,'PostgreSQL dependency requiring a bound database and protected persistence.',Object.keys(input.files).filter(name=>/package\.json|compose|docker/i.test(name))):undefined),
  simple('pm2',input=>Object.keys(input.files).some(name=>/^ecosystem\.config\./.test(name))?match('pm2',.99,'Existing PM2 ecosystem definition should be adopted and reconciled.',Object.keys(input.files).filter(name=>/^ecosystem\.config\./.test(name))):undefined),
  simple('supervisor',input=>Object.keys(input.files).some(name=>/supervisor.*\.conf$|supervisord\.conf$/.test(name))?match('supervisor',.99,'Existing Supervisor definitions should be adopted and reconciled.',Object.keys(input.files).filter(name=>/supervisor/.test(name))):undefined),
  simple('cron',input=>Object.keys(input.files).some(name=>/^(crontab|cron\.d\/)/.test(name))?match('cron',.95,'Existing cron schedule requires explicit adoption and retained run evidence.',Object.keys(input.files).filter(name=>/cron/.test(name))):undefined),
];

export function interpretDeploymentProject(input:DeploymentAdapterInput):DeploymentProposal{
  const matches=detected(input),ids=new Set(matches.map(item=>item.id)),selected=manager(input),pkg=nodePackage(input),pm=packageManager(input),name=String(pkg.name??json(input.files['composer.json']).name??'project').split('/').at(-1)??'project';let adapter='node',roles:ProjectManifestV2['roles']=[],phases:ProjectManifestV2['phases']=[],port=3000,artifacts:ProjectManifestV2['artifacts']=[],storage:ProjectManifestV2['storage']=[],resources:Array<{name:string;kind:string;required:boolean}>=[],schedules:any[]=[];
  if(ids.has('docker')){adapter='docker';roles=[role('application','application','docker','docker',['compose','up','-d','--remove-orphans'])];phases=[phase('preflight','preflight','docker version',30_000),phase('build','build','docker compose build'),phase('activate','activate','docker compose up -d --remove-orphans',300_000),phase('health','health',undefined,120_000)];if(Object.values(input.files).some(value=>/postgres/i.test(value))){resources.push({name:'postgres',kind:'postgres.database',required:true});storage.push({name:'postgres-data',kind:'volume',target:'postgres_data',durable:true,deletionProtection:true})}if(Object.values(input.files).some(value=>/redis/i.test(value)))resources.push({name:'redis',kind:'redis.instance',required:true})}
  else if(ids.has('laravel')){adapter='laravel';port=8000;roles=[role('web','application','php-fpm',selected,['-F']),role('queue','worker','php',selected,['artisan','queue:work','--sleep=1','--tries=3']),role('scheduler','scheduler','php',selected,['artisan','schedule:run'])];phases=[phase('preflight','preflight','php --version',30_000),phase('install','install','composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader'),...(has(input,'package.json')?[phase('frontend-install','install',pm==='npm'?'npm ci':`${pm} install --frozen-lockfile`),phase('frontend-build','build',run(pm,'build'))]:[]),phase('storage-link','prepare','php artisan storage:link'),phase('migrate','migrate','php artisan migrate --force'),phase('cache','post-deploy','php artisan config:cache && php artisan route:cache && php artisan view:cache'),phase('activate','activate'),phase('health','health',undefined,120_000)];storage=[{name:'storage',kind:'directory',target:'storage',durable:true,deletionProtection:true}];resources=[{name:'database',kind:'postgres.database',required:true}];schedules=[{protocolVersion:'fngk.schedule.v1',id:'laravel-scheduler',manager:ids.has('cron')?'cron':'systemd-timer',expression:'* * * * *',timezone:'UTC',roleId:'scheduler',environmentRevision:1,overlapPolicy:'forbid',timeoutMs:55_000,retries:0,retentionDays:7,enabled:true}]}
  else{const framework=ids.has('sveltekit')?'sveltekit':ids.has('svelte')?'svelte':ids.has('fastify')?'fastify':ids.has('next')?'next':ids.has('nuxt')?'nuxt':'node';adapter=framework;const scripts=pkg.scripts??{},install=pm==='npm'?'npm ci':`${pm} install --frozen-lockfile`,build=typeof scripts.build==='string'?run(pm,'build'):undefined;let executable=pm,startArguments=['run','start'];if(typeof scripts.start!=='string'){executable='node';startArguments=['index.js']}if(framework==='sveltekit'&&dependencies(input)['@sveltejs/adapter-node']){executable='node';startArguments=['build']}if(framework==='nuxt'){executable='node';startArguments=['.output/server/index.mjs']}roles=[role('web','application',executable,selected,startArguments)];phases=[phase('preflight','preflight','node --version',30_000),phase('install','install',install),...(build?[phase('build','build',build)]:[]),phase('activate','activate'),phase('health','health',undefined,120_000)];artifacts=framework==='next'?[{path:'.next',kind:'server'}]:framework==='nuxt'?[{path:'.output',kind:'server'}]:framework==='sveltekit'?[{path:'build',kind:'server'}]:framework==='svelte'?[{path:'dist',kind:'static'}]:[];if(ids.has('postgres'))resources.push({name:'postgres',kind:'postgres.database',required:true})}
  const readiness={protocol:'http' as const,path:'/health',timeoutMs:120_000},manifest:ProjectManifestV2={protocolVersion:'fngk.project.v2',name,adapter:{id:adapter,version:'1.0.0'},roles,phases,ports:[{name:'web',port,protocol:'http'}],health:{readiness,shutdownSignal:'SIGTERM',drainTimeoutMs:10_000},environments:{[input.environment]:{variables:{NODE_ENV:input.environment},secretReferences:resources.map(item=>`${item.name}.url`)}},routes:[{name:'web'}],artifacts,storage,resources,retention:{successfulReleases:5,failedReleaseDays:7,logDays:7}},runtimeRoles=roles.map(item=>({protocolVersion:'fngk.runtime.v1',roleId:item.id,manager:item.runtime.manager,command:item.command,arguments:item.arguments??[],cwd:item.cwd??'.',user:'device-agent',environmentRevision:1,instances:item.instances??1,durability:item.runtime.durability,restart:{policy:item.runtime.restartPolicy,maxRestarts:10,backoffMs:1000},...(item.kind==='application'?{readiness}:{}),shutdown:{signal:'SIGTERM',drainTimeoutMs:10_000},logs:[{source:'stdout'},{source:'stderr'},{source:'manager'}]})),storageResources=storage.map(item=>({protocolVersion:'fngk.storage.v1',name:item.name,kind:item.kind==='object'?'object-storage':item.kind,target:item.target,durable:item.durable,deletionProtection:item.deletionProtection,consumers:roles.map(role=>role.id),environment:input.environment})),warnings:string[]=[];
  if(selected==='systemd'&&!ids.has('docker'))warnings.push('No existing PM2 or Supervisor definition was found; verify systemd user/service ownership and boot enablement before production approval.');if(adapter==='svelte'&&input.environment==='production')warnings.push('Static Svelte output should use immutable hosted-artifact publication instead of a daemon process.');
  const proposal:DeploymentProposal={protocolVersion:'atlas.deployment-proposal.v1',matches,manifest,runtimeRoles,schedules,storageResources,resources,warnings};const errors=deploymentAdapters.flatMap(value=>value.validate(proposal));if(errors.length)throw new Error([...new Set(errors)].join('; '));return proposal;
}
