export const PROJECT_MANIFEST_PROTOCOL='fngk.project.v1' as const;
export type RestartPolicy='never'|'on-failure'|'always';
export interface ProjectManifest {protocolVersion:typeof PROJECT_MANIFEST_PROTOCOL;name:string;commands:{install?:string;build?:string;start:string};port:number;health:{protocol:'http'|'tcp';path:string;timeoutMs:number};artifacts:Array<{path:string;kind:string}>;restartPolicy:RestartPolicy;environments:Record<string,{variables:Record<string,string>;secretReferences:string[]}>;routes:Array<{name:string;hostname?:string}>}

const record=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const text=(value:unknown,label:string,max:number)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${label} is required and must not exceed ${max} characters.`);return value.trim()};

export function parseProjectManifest(value:unknown):ProjectManifest{
  const input=record(value);if(input.protocolVersion!==PROJECT_MANIFEST_PROTOCOL)throw new Error(`protocolVersion must be ${PROJECT_MANIFEST_PROTOCOL}.`);
  const commands=record(input.commands),start=text(commands.start,'commands.start',8192),port=Number(input.port);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('port must be between 1 and 65535.');
  const healthInput=record(input.health),protocol=healthInput.protocol??'http';if(!['http','tcp'].includes(protocol))throw new Error('health.protocol must be http or tcp.');const healthPath=healthInput.path??'/';if(typeof healthPath!=='string'||!healthPath.startsWith('/')||healthPath.length>1000)throw new Error('health.path must be a bounded absolute URL path.');const timeoutMs=Number(healthInput.timeoutMs??30_000);if(!Number.isInteger(timeoutMs)||timeoutMs<1000||timeoutMs>300_000)throw new Error('health.timeoutMs must be between 1000 and 300000.');
  const artifacts=(Array.isArray(input.artifacts)?input.artifacts:[]).map((raw:any)=>{const item=record(raw),artifactPath=text(item.path,'artifact path',2000);if(artifactPath.startsWith('/')||artifactPath.split(/[\\/]/).includes('..'))throw new Error('artifact path must remain inside the release directory.');return{path:artifactPath,kind:text(item.kind,'artifact kind',100)}});if(artifacts.length>100)throw new Error('artifacts must contain at most 100 entries.');
  const environments:ProjectManifest['environments']={};for(const [name,raw] of Object.entries(record(input.environments))){if(!/^[a-zA-Z][\w.-]{0,63}$/.test(name))throw new Error('environment names must be bounded identifiers.');const item=record(raw),variables:Record<string,string>={};for(const [key,rawValue] of Object.entries(record(item.variables))){if(/secret|password|token|credential|private[_-]?key|database_url/i.test(key))throw new Error(`${key} must use a secret reference instead of an inline value.`);if(typeof rawValue!=='string'||rawValue.length>4000)throw new Error(`environment variable ${key} must be a bounded string.`);variables[key]=rawValue}const secretReferences=Array.isArray(item.secretReferences)?item.secretReferences.map((entry:unknown)=>text(entry,'secret reference',200)):[];environments[name]={variables,secretReferences:[...new Set(secretReferences)]}}
  const routes=(Array.isArray(input.routes)?input.routes:[]).map((raw:any)=>{const item=record(raw),hostname=item.hostname===undefined?undefined:text(item.hostname,'route hostname',253);if(hostname&&!/^[a-z0-9.-]+$/i.test(hostname))throw new Error('route hostname is invalid.');return{name:text(item.name,'route name',100),...(hostname?{hostname}:{})}});if(routes.length>20)throw new Error('routes must contain at most 20 entries.');
  const restartPolicy=input.restartPolicy??'on-failure';if(!['never','on-failure','always'].includes(restartPolicy))throw new Error('restartPolicy is invalid.');
  return{protocolVersion:PROJECT_MANIFEST_PROTOCOL,name:text(input.name,'name',100),commands:{...(commands.install?{install:text(commands.install,'commands.install',8192)}:{}),...(commands.build?{build:text(commands.build,'commands.build',8192)}:{}),start},port,health:{protocol,path:healthPath,timeoutMs},artifacts,restartPolicy,environments,routes};
}
