<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import Send from '@lucide/svelte/icons/send';
  import Square from '@lucide/svelte/icons/square';
  import type { WorkbenchState } from '../lib/workbench-state.js';
  import { AgentChatStore, createAtlasConversationTransport, type AgentReference, type ConversationEvent } from '../lib/agent-chat.js';
  import { authorizedSlashCommands, loadAtlasCapabilities, type AtlasCapability } from '../lib/atlas-capabilities.js';
  import ToolApprovalCard from './ToolApprovalCard.svelte';
  import './AgentChatPanel.css';

  export let state: WorkbenchState;
  let store = new AgentChatStore({ scopeKey: state.snapshot().contextId });
  let references: AgentReference[] = store.snapshot().references;
  let prompt = '', status = 'Checking Calculator…', error = '', conversationId = store.snapshot().conversationId, cursor = store.snapshot().cursor;
  let tools: AtlasCapability[] = [], allowed = new Set<string>(), slash = [] as ReturnType<typeof authorizedSlashCommands>;
  let messages: Array<{ id: string; role: 'user' | 'assistant'; text: string }> = [], toolCalls = new Map<string, any>(), approvals = new Map<string, any>();
  let stopStream: (() => void) | undefined; const transport = createAtlasConversationTransport();
  const scope = () => ({ profile: state.snapshot().connection.profile, deviceId: state.snapshot().contextId.startsWith('device:') ? state.snapshot().contextId.slice(7) : undefined });
  const persist = () => { store.setConversation(conversationId, cursor); references = store.snapshot().references; };
  const removeReference = (reference: AgentReference) => { store.removeReference(reference); references = store.snapshot().references; };
  const addReference = (reference: AgentReference) => { store.attach(reference); references = store.snapshot().references; };
  function apply(event: ConversationEvent) { const data = event as Record<string, unknown>; cursor = event.cursor; persist(); if (event.type === 'message.delta') { const id = String(data.messageId ?? event.id), text = String(data.text ?? ''); const existing = messages.find(message => message.id === id); if (existing) existing.text += text; else messages = [...messages, { id, role: 'assistant', text }]; } if (event.type === 'tool.call') toolCalls.set(String(data.toolCallId), { ...(typeof data.tool === 'object' && data.tool ? data.tool as Record<string, unknown> : {}), id: data.toolCallId, status: 'running' }); if (event.type === 'tool.progress' || event.type === 'tool.result') toolCalls.set(String(data.toolCallId), { ...(toolCalls.get(String(data.toolCallId)) ?? {}), id: data.toolCallId, status: event.type === 'tool.result' ? data.status : 'running', summary: data.summary }); if (event.type === 'approval.requested') approvals.set(String(data.approvalId), { approvalId: data.approvalId, toolCallId: data.toolCallId, summary: data.summary }); toolCalls = new Map(toolCalls); approvals = new Map(approvals); }
  function resume() { if (!conversationId) return; stopStream?.(); stopStream = transport.stream(conversationId, cursor, apply, reason => { error = reason.message; status = 'Disconnected — resume is available'; }); status = 'Streaming'; }
  async function send() { let text = prompt.trim(); if (!text) return; error = ''; const command = slash.find(item => text === item.command || text.startsWith(`${item.command} `)); if (command) text = `Use ${command.id}${text.slice(command.command.length)}`.trim(); try { if (!conversationId) { const created = await transport.create({ references }); conversationId = created.conversationId; persist(); resume(); } messages = [...messages, { id: crypto.randomUUID(), role: 'user', text }]; prompt = ''; await transport.send(conversationId, { text, references }); status = 'Streaming'; } catch (reason) { error = (reason as Error).message; status = 'Needs recovery'; } }
  async function cancel() { if (!conversationId) return; try { await transport.cancel(conversationId); status = 'Cancelled'; } catch (reason) { error = (reason as Error).message; } }
  async function decide(approval: any, decision: string) { try { if (decision === 'deny') { approvals.delete(approval.approvalId); approvals = new Map(approvals); return; } const kind = decision === 'allow_full_access' ? 'full_access' : decision === 'allow_durable' ? 'durable' : 'conversation'; const expiresAt = decision === 'allow_full_access' ? new Date(Date.now() + 60 * 60 * 1000).toISOString() : undefined; await fetch('/api/agent-tools/grants', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ scope: scope(), toolIds: [approval.toolId ?? '*'], kind, actor: `conversation:${conversationId ?? 'pending'}`, expiresAt }) }); approvals.delete(approval.approvalId); approvals = new Map(approvals); } catch (reason) { error = (reason as Error).message; } }
  async function revoke() { const value = await fetch('/api/agent-tools/grants').then(response => response.json()).catch(() => ({ grants: [] })); for (const grant of value.grants ?? []) if (grant.actor === `conversation:${conversationId ?? 'pending'}`) await fetch(`/api/agent-tools/grants/${encodeURIComponent(grant.id)}/revoke`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ actor: 'atlas-user' }) }); }
  onMount(() => { const selected = state.snapshot().selection; if (state.snapshot().contextId.startsWith('device:')) addReference({ kind: 'device', id: state.snapshot().contextId, label: state.snapshot().contextId.slice(7) }); if (selected?.path) addReference({ kind: 'file', id: selected.path, label: selected.path.split('/').at(-1) ?? selected.path }); const unsubscribe = state.subscribe(() => { slash = authorizedSlashCommands(tools, allowed); }); const attach = (event: Event) => addReference((event as CustomEvent<AgentReference>).detail); window.addEventListener('atlas:agent-chat-reference', attach); void loadAtlasCapabilities().then(value => { tools = value; allowed = new Set(value.filter(tool => tool.risk === 'read').map(tool => tool.id)); slash = authorizedSlashCommands(value, allowed); status = 'Ready'; if (conversationId) resume(); }).catch(reason => { error = (reason as Error).message; status = 'Calculator unavailable'; }); return () => { unsubscribe(); window.removeEventListener('atlas:agent-chat-reference', attach); stopStream?.(); }; });
  onDestroy(() => stopStream?.());
</script>

<section class="agent-chat" aria-label="Atlas Agent Chat">
  <header><strong>Agent Chat</strong><small>{status}</small>{#if conversationId}<button title="Cancel response" aria-label="Cancel response" onclick={() => void cancel()}><Square size={13}/></button>{/if}</header>
  {#if error}<p class="connection-warning">{error}</p>{/if}
  <div class="reference-list" aria-label="Conversation references">{#each references as reference}<span>{reference.kind}: {reference.label}<button aria-label={`Remove ${reference.label}`} onclick={() => removeReference(reference)}>×</button></span>{/each}{#if !references.length}<small>No context references attached.</small>{/if}</div>
  <div class="transcript" aria-live="polite">{#each messages as message}<article class:user={message.role === 'user'} class="message">{message.text}</article>{/each}{#each [...toolCalls.values()] as call}<article class="tool-card"><header><strong>{call.title ?? 'Atlas tool'}</strong><small>{call.status}</small></header><p>{call.summary ?? call.id}</p>{#if call.documentationTarget}<a href="#documentation" onclick={() => window.dispatchEvent(new CustomEvent('atlas:open-documentation', { detail: { topicId: call.documentationTarget } }))}>Open documentation</a>{/if}</article>{/each}{#each [...approvals.values()] as approval}<ToolApprovalCard {approval} onDecision={(decision) => decide(approval, decision)} onRevoke={() => void revoke()}/>{/each}</div>
  <form class="composer" onsubmit={(event) => { event.preventDefault(); void send(); }}><textarea bind:value={prompt} aria-label="Message Atlas Agent" placeholder={slash.length ? `Ask Atlas or use ${slash[0].command}` : 'Ask Atlas…'}></textarea><button type="submit" disabled={!prompt.trim()}><Send size={14}/>Send</button>{#if conversationId}<button type="button" onclick={resume}>Resume</button>{/if}</form>
</section>
