<script lang="ts">
  import {onMount} from 'svelte';import SquareTerminal from '@lucide/svelte/icons/square-terminal';import Search from '@lucide/svelte/icons/search';import Keyboard from '@lucide/svelte/icons/keyboard';import PanelRightOpen from '@lucide/svelte/icons/panel-right-open';import FilePlus from '@lucide/svelte/icons/file-plus';import UnifiedSearch from './UnifiedSearch.svelte';import {AtlasCommandRegistry,type AtlasCommand} from '../lib/command-registry.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  import {contextActions} from '../lib/context-actions.js';
  export let state:WorkbenchState;const registry=new AtlasCommandRegistry();let open=false,query='',items:AtlasCommand[]=[];
  const dispatch=(name:string)=>{window.dispatchEvent(new Event(name))};const refresh=()=>items=registry.search(query);
  function show(){open=true;query='';refresh();queueMicrotask(()=>document.querySelector<HTMLInputElement>('.command-palette input')?.focus())}
  onMount(()=>{const unregister=[
    registry.register({id:'file.new',label:'File: New Buffer',keywords:['new file','untitled'],shortcut:'Ctrl+N',run:()=>dispatch('atlas:new-buffer')}),
    registry.register({id:'file.save',label:'File: Save',keywords:['write current editor'],shortcut:'Ctrl+S',run:()=>dispatch('atlas:save-active')}),
    registry.register({id:'file.saveAs',label:'File: Save As',keywords:['copy create path'],shortcut:'Ctrl+Shift+S',run:()=>dispatch('atlas:save-as-active')}),
    registry.register({id:'view.search',label:'View: Search Context',keywords:['find symbols processes'],run:()=>dispatch('atlas:focus-search')}),
    registry.register({id:'view.files',label:'View: Open Filesystem',keywords:['explorer folders'],run:()=>{window.dispatchEvent(new CustomEvent('atlas:open-root',{detail:{contextId:state.snapshot().contextId,path:'/'}}))}}),
    registry.register({id:'terminal.open',label:'Terminal: Open',keywords:['shell session'],run:()=>dispatch('atlas:open-terminal')}),
    ...contextActions.map(action=>registry.register({id:`context.${action.id}`,label:`Context: ${action.label}`,keywords:[action.group,action.placement],enabled:()=>action.available(state.snapshot()),run:()=>action.run(state.snapshot())})),
  ],palette=()=>show(),keyboard=(event:KeyboardEvent)=>{const mod=event.ctrlKey||event.metaKey;if(mod&&event.key.toLowerCase()==='n'){event.preventDefault();void registry.execute('file.new')}if(mod&&!event.shiftKey&&event.key.toLowerCase()==='k'){event.preventDefault();dispatch('atlas:focus-search')}if(mod&&event.shiftKey&&event.key.toLowerCase()==='p'){event.preventDefault();show()}if(event.key==='Escape')open=false};window.addEventListener('atlas:shortcuts',palette);window.addEventListener('keydown',keyboard);refresh();return()=>{for(const remove of unregister)remove();window.removeEventListener('atlas:shortcuts',palette);window.removeEventListener('keydown',keyboard)}});
</script>
<header class="atlas-command-menu" aria-label="Atlas title bar"><div class="title-brand"><img src="/brand/fngk-mark.svg" alt=""/><b>FNGK Atlas</b><span>effective systems & code map</span></div><UnifiedSearch {state} commands={registry}/><div class="title-actions"><button title="New file buffer" aria-label="New file" onclick={()=>void registry.execute('file.new')}><FilePlus size={14}/></button><button title="Search files, symbols, and processes" aria-label="Search" onclick={()=>void registry.execute('view.search')}><Search size={14}/></button><button title="Open filesystem" aria-label="Focus filesystem" onclick={()=>void registry.execute('view.files')}><PanelRightOpen size={14}/></button><button title="Open terminal for selected Device" aria-label="Open terminal" onclick={()=>void registry.execute('terminal.open')}><SquareTerminal size={14}/></button><button title="Command palette" aria-label="Command palette" onclick={show}><Keyboard size={14}/></button></div></header>
{#if open}<div class="palette-backdrop"><div class="command-palette" role="dialog" aria-modal="true" aria-label="Command palette"><label><Keyboard size={15}/><input bind:value={query} oninput={refresh} placeholder="Type a command…" aria-label="Command search"/></label><div>{#each items as command}<button onclick={()=>{open=false;void registry.execute(command.id)}}><span>{command.label}</span>{#if command.shortcut}<kbd>{command.shortcut}</kbd>{/if}</button>{/each}</div></div></div>{/if}
