<script lang="ts">
  import {onMount} from 'svelte';import SquareTerminal from '@lucide/svelte/icons/square-terminal';import Search from '@lucide/svelte/icons/search';import Keyboard from '@lucide/svelte/icons/keyboard';import PanelRightOpen from '@lucide/svelte/icons/panel-right-open';import FilePlus from '@lucide/svelte/icons/file-plus';import Sun from '@lucide/svelte/icons/sun';import Moon from '@lucide/svelte/icons/moon';import UnifiedSearch from './UnifiedSearch.svelte';import AtlasSelect from './ui/AtlasSelect.svelte';import {AtlasCommandRegistry,registerDocumentationCommands,type AtlasCommand} from '../lib/command-registry.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  import {api} from '../lib/api.js';import {notify} from '../lib/notifications.js';
  import {contextActions} from '../lib/context-actions.js';
  export let state:WorkbenchState;const registry=new AtlasCommandRegistry();let open=false,query='',items:AtlasCommand[]=[],theme=state.snapshot().theme,profiles:any[]=[],profile=state.snapshot().connection.profile??'',paletteInvoker:HTMLElement|undefined,selected=0;
  const dispatch=(name:string)=>{window.dispatchEvent(new Event(name))};const refresh=()=>{items=registry.search(query);selected=0};
  async function execute(command:AtlasCommand){if(command.enabled&&!command.enabled())return;dismiss();try{await registry.execute(command.id)}catch(error){notify((error as Error).message,'error')}}
  function navigate(event:KeyboardEvent){if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();selected=(selected+(event.key==='ArrowDown'?1:-1)+items.length)%Math.max(1,items.length);document.getElementById('command-'+selected)?.scrollIntoView({block:'nearest'})}else if(event.key==='Enter'){event.preventDefault();if(items[selected])void execute(items[selected])}else if(event.key==='Tab'){event.preventDefault();document.querySelector<HTMLInputElement>('.command-palette input')?.focus()}}
  function show(){paletteInvoker=document.activeElement instanceof HTMLElement?document.activeElement:undefined;open=true;query='';refresh();queueMicrotask(()=>document.querySelector<HTMLInputElement>('.command-palette input')?.focus())}
  function dismiss(){open=false;queueMicrotask(()=>paletteInvoker?.focus())}
  onMount(()=>{const stateUnsub=state.subscribe(value=>{theme=value.theme;profile=value.connection.profile??profile}),loadProfiles=async()=>{try{const value=await api<{profiles:any[]}>('/api/fngk/profiles');profiles=value.profiles??[]}catch{profiles=[]}},unregister=[
    registry.register({id:'file.new',label:'File: New Buffer',keywords:['new file','untitled'],shortcut:'Ctrl+N',run:()=>dispatch('atlas:new-buffer')}),
    registry.register({id:'file.save',label:'File: Save',keywords:['write current editor'],shortcut:'Ctrl+S',run:()=>dispatch('atlas:save-active')}),
    registry.register({id:'file.saveAs',label:'File: Save As',keywords:['copy create path'],shortcut:'Ctrl+Shift+S',run:()=>dispatch('atlas:save-as-active')}),
    registry.register({id:'view.search',label:'View: Search Context',keywords:['find symbols processes'],run:()=>dispatch('atlas:focus-search')}),
    registry.register({id:'view.files',label:'View: Open Filesystem',keywords:['explorer folders'],run:()=>{window.dispatchEvent(new CustomEvent('atlas:open-root',{detail:{contextId:state.snapshot().contextId,path:'/'}}))}}),
    registry.register({id:'view.recovery',label:'FNGK: Connection setup and recovery',run:()=>dispatch('atlas:recover')}),
    registry.register({id:'view.lifecycle',label:'FNGK: Device management',run:()=>dispatch('atlas:open-device-lifecycle')}),
    registry.register({id:'atlas:open-device-sessions',label:'FNGK: Device Sessions',keywords:['connections','persistent','leases'],run:()=>dispatch('atlas:open-device-sessions')}),
    registry.register({id:'atlas:open-agent-chat',label:'Atlas: Agent Chat',keywords:['calculator','assistant','ai','tools'],run:()=>dispatch('atlas:open-agent-chat')}),
    registry.register({id:'atlas:open-app-connections',label:'Atlas: Manage app connections',keywords:['calculator','authorization','connect'],run:()=>dispatch('atlas:open-app-connections')}),
    registry.register({id:'view.theme',label:'View: Toggle light / dark theme',run:()=>state.setTheme(state.snapshot().theme==='dark'?'light':'dark')}),
    registry.register({id:'terminal.newPane',label:'Terminal: New pane',run:()=>{window.dispatchEvent(new CustomEvent('atlas:open-terminal',{detail:{create:true}}))}}),
    registry.register({id:'terminal.open',label:'Terminal: Open',keywords:['shell session'],run:()=>dispatch('atlas:open-terminal')}),
    registerDocumentationCommands(registry,topicId=>window.dispatchEvent(new CustomEvent('atlas:open-documentation',{detail:{topicId}}))),
    ...contextActions.map(action=>registry.register({id:`context.${action.id}`,label:`Context: ${action.label}`,keywords:[action.group,action.placement],enabled:()=>action.available(state.snapshot()),run:()=>action.run(state.snapshot())})),
    ],palette=()=>show(),keyboard=(event:KeyboardEvent)=>{const mod=event.ctrlKey||event.metaKey;if(mod&&event.key.toLowerCase()==='n'){event.preventDefault();void registry.execute('file.new')}if(mod&&!event.shiftKey&&event.key.toLowerCase()==='k'){event.preventDefault();dispatch('atlas:focus-search')}if(mod&&event.shiftKey&&event.key.toLowerCase()==='p'){event.preventDefault();show()}if(event.key==='Tab'&&open){event.preventDefault();document.querySelector<HTMLInputElement>('.command-palette input')?.focus()}if(event.key==='Escape'&&open)dismiss()};window.addEventListener('atlas:shortcuts',palette);window.addEventListener('keydown',keyboard);void loadProfiles();refresh();return()=>{stateUnsub();for(const remove of unregister)remove();window.removeEventListener('atlas:shortcuts',palette);window.removeEventListener('keydown',keyboard)}});
</script>
<header class="atlas-command-menu" aria-label="Atlas title bar"><div class="title-brand"><img src="/brand/fngk-mark.svg" alt=""/><b>FNGK Atlas</b><span>workspace</span></div><UnifiedSearch {state} commands={registry}/><div class="title-actions">{#if profiles.length>0}<label class="profile-picker" title="Switch FNGK profile"><span>Profile</span><AtlasSelect ariaLabel="FNGK profile" bind:value={profile} onchange={event=>window.dispatchEvent(new CustomEvent('atlas:profile',{detail:{profile:(event.currentTarget as HTMLSelectElement).value}}))} options={[...(!profiles.some(item=>item.name===profile)?[{value:profile,label:profile||'Select profile'}]:[]),...profiles.map(item=>({value:item.name,label:`${item.name}${item.current?' · default':''}`}))]}/></label>{/if}<button title="New file buffer" aria-label="New file" onclick={()=>void registry.execute('file.new')}><FilePlus size={14}/></button><button title="Search files, symbols, and processes" aria-label="Search" onclick={()=>void registry.execute('view.search')}><Search size={14}/></button><button title="Open filesystem" aria-label="Focus filesystem" onclick={()=>void registry.execute('view.files')}><PanelRightOpen size={14}/></button><button title="Open terminal for selected Device" aria-label="Open terminal" onclick={()=>void registry.execute('terminal.open')}><SquareTerminal size={14}/></button><button title="Command palette" aria-label="Command palette" onclick={show}><Keyboard size={14}/></button><button title={`Use ${theme==='dark'?'light':'dark'} theme`} aria-label={`Use ${theme==='dark'?'light':'dark'} theme`} onclick={()=>state.setTheme(theme==='dark'?'light':'dark')}>{#if theme==='dark'}<Sun size={14}/>{:else}<Moon size={14}/>{/if}</button></div></header>
{#if open}<div class="palette-backdrop"><div class="command-palette" role="dialog" aria-modal="true" aria-label="Command palette"><label><Keyboard size={15}/><input bind:value={query} oninput={refresh} onkeydown={navigate} aria-controls="command-options" aria-activedescendant={items.length?'command-'+selected:undefined} placeholder="Type a command…" aria-label="Command search"/></label><div id="command-options">{#each items as command,index}<button id={'command-'+index} class:command-selected={index===selected} disabled={command.enabled?!command.enabled():false} onclick={()=>void execute(command)}><span>{command.label}</span>{#if command.shortcut}<kbd>{command.shortcut}</kbd>{/if}</button>{/each}{#if !items.length}<p class="palette-empty">No matching commands</p>{/if}</div></div></div>{/if}
