<script lang="ts">
  import {onMount} from 'svelte';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import Database from '@lucide/svelte/icons/database';import Plug from '@lucide/svelte/icons/plug';import Play from '@lucide/svelte/icons/play';import Trash from '@lucide/svelte/icons/trash';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import DocumentationHelp from './DocumentationHelp.svelte';
  export let state:WorkbenchState;export let params:{contextId?:string}={};let contextId=params.contextId??state.snapshot().contextId,candidates:any[]=[],errors:any[]=[],resource:any,surface:any,bindings:any[]=[],active:any,ephemeralBindingId='',ephemeralEnvelope:any,databases:string[]=[],databaseName='postgres',section='query',sql='SELECT current_database(), current_user;',result:any,status='Discovering PostgreSQL Surfaces…',busy=false,confirmDelete=false,profile={name:'local',environment:'development',host:'127.0.0.1',port:5432,database:'postgres',username:'',sslMode:'prefer',password:'',remember:false},catalog:any,tables:any[]=[],backupPath='',restorePath='',queryHistory:Array<{sql:string;database:string;at:string;status:string}>=[],savedQueries:Array<{name:string;sql:string}>=[],savedName='',schemaBaseline:any,schemaDifference='';
  const bytes=(value:Uint8Array)=>btoa(String.fromCharCode(...value));const decode=(value:string)=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
  async function encrypt(password:string,publicKey:string){if(!password)return undefined;const recipient=await crypto.subtle.importKey('raw',decode(publicKey),{name:'ECDH',namedCurve:'P-256'},false,[]),pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:recipient},pair.privateKey,256)),salt=crypto.getRandomValues(new Uint8Array(16)),material=new Uint8Array(shared.length+salt.length);material.set(shared);material.set(salt,shared.length);const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',material),'AES-GCM',false,['encrypt']),nonce=crypto.getRandomValues(new Uint8Array(12)),ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce},key,new TextEncoder().encode(password))),ephemeralPublicKey=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));return{ephemeralPublicKey:bytes(ephemeralPublicKey),salt:bytes(salt),nonce:bytes(nonce),ciphertext:bytes(ciphertext)}}
  async function discover(){busy=true;try{const value=await api<any>(`/api/databases/discover?contextId=${encodeURIComponent(contextId)}`);candidates=(value.items??[]).filter((item:any)=>item.engine==='postgres');errors=value.errors??[];status=`${candidates.length} PostgreSQL service${candidates.length===1?'':'s'} detected`;}catch(error){status=(error as Error).message}finally{busy=false}}
  async function select(candidate:any){const resourceId=candidate.evidence?.nativeResourceId;if(!resourceId){status='Adopt this PostgreSQL resource in Signal before opening it natively.';return}busy=true;try{resource=candidate;surface=await api<any>(`/api/databases/surface?resourceId=${encodeURIComponent(resourceId)}`);profile={...profile,host:candidate.host,port:candidate.port??5432};await loadBindings();status='Native Device Surface ready.'}catch(error){status=(error as Error).message}finally{busy=false}}
  async function loadBindings(){if(!resource)return;const value=await api<any>(`/api/databases/bindings?resourceId=${encodeURIComponent(resource.evidence.nativeResourceId)}`);bindings=value.items??[];active=bindings.find(item=>item.id===active?.id)??bindings[0];if(active)await loadDatabases()}
  async function createProfile(){if(!resource||!surface)return;busy=true;try{const secretEnvelope=await encrypt(profile.password,surface.credentialPublicKey),remember=profile.remember,value=await api<any>('/api/databases/bindings',{method:'POST',body:JSON.stringify({contextId,resourceId:resource.evidence.nativeResourceId,name:profile.name,environment:profile.environment,config:{host:profile.host,port:Number(profile.port),database:profile.database,username:profile.username,sslMode:profile.sslMode,credentialSource:remember?'device-vault':profile.password?'ephemeral':'peer'},persistCredential:remember,...(secretEnvelope?{secretEnvelope}:{})})});active=value;ephemeralBindingId=!remember&&secretEnvelope?value.id:'';ephemeralEnvelope=!remember?secretEnvelope:undefined;profile.password='';await invoke('database.connection.test');await loadBindings();status='Device profile connected.'}catch(error){profile.password='';status=(error as Error).message}finally{busy=false}}
  async function invoke(capability:string,input:Record<string,unknown>={},confirmation?:string){if(!active)throw new Error('Select a database profile first.');return api<any>(`/api/databases/bindings/${encodeURIComponent(active.id)}/invoke`,{method:'POST',body:JSON.stringify({contextId,capability,input:{...input,database:databaseName},...(active.id===ephemeralBindingId&&ephemeralEnvelope?{secretEnvelope:ephemeralEnvelope}:{}),...(confirmation?{confirmation}: {})})})}
  async function loadDatabases(){try{const value=await invoke('database.catalog',{section:'databases'}),rows=value.output?.rows??[],index=Math.max(0,(value.output?.columns??[]).findIndex((column:string)=>column==='datname'));databases=rows.map((row:any[])=>String(row[index])).filter(Boolean);databaseName=databases.includes(active?.config?.database)?active.config.database:databases[0]??active?.config?.database??'postgres'}catch(error){status=(error as Error).message}}
  async function runQuery(){busy=true;try{const normalized=sql.trim(),kind=/^(SELECT|SHOW|VALUES|TABLE|EXPLAIN(?!\s+ANALYZE))/i.test(normalized)?'read':/^(INSERT|UPDATE|DELETE|MERGE|COPY)/i.test(normalized)?'write':'admin',value=await invoke(`database.query.${kind}`,{sql,maxRows:1000},kind==='read'?undefined:active.name);result=value.output;status=`${result.rowCount??result.rows?.length??0} rows · ${result.durationMs??0} ms`;queryHistory=[{sql,database:databaseName,at:new Date().toISOString(),status},...queryHistory].slice(0,100);localStorage.setItem('atlas.database.history',JSON.stringify(queryHistory))}catch(error){status=(error as Error).message;queryHistory=[{sql,database:databaseName,at:new Date().toISOString(),status},...queryHistory].slice(0,100)}finally{busy=false}}
  async function loadCatalog(kind:string){busy=true;try{section=kind;const value=await invoke('database.catalog',{section:kind});catalog=value.output;if(kind==='tables')tables=catalog.rows??[];status=`Loaded ${kind}.`}catch(error){status=(error as Error).message}finally{busy=false}}
  async function readTable(row:any[]){const columns=catalog?.columns??[],schema=String(row[columns.indexOf('table_schema')]??row[0]),table=String(row[columns.indexOf('table_name')]??row[1]);try{result=(await invoke('database.table.read',{schema,table,limit:200,offset:0})).output;section='data';status=`${schema}.${table}`}catch(error){status=(error as Error).message}}
  async function snapshot(){busy=true;try{result=(await invoke('database.schema.snapshot',{})).output;section='schema';status='Schema snapshot loaded.'}catch(error){status=(error as Error).message}finally{busy=false}}
  async function compareSchema(){busy=true;try{const current=(await invoke('database.schema.snapshot',{})).output;if(!schemaBaseline){schemaBaseline=current;schemaDifference='Baseline captured for this workbench.'}else{schemaDifference=JSON.stringify(schemaBaseline)===JSON.stringify(current)?'No schema change detected.':'Schema differs from the captured baseline.';result={baseline:schemaBaseline,current}}section='schema';status=schemaDifference}catch(error){status=(error as Error).message}finally{busy=false}}
  function saveQuery(){if(!savedName.trim()||!sql.trim())return;savedQueries=[...savedQueries.filter(item=>item.name!==savedName.trim()),{name:savedName.trim(),sql}];localStorage.setItem('atlas.database.saved-queries',JSON.stringify(savedQueries));savedName='';status='Query saved in this browser.'}
  async function transfer(kind:'backup'|'restore'){const file=kind==='backup'?backupPath:restorePath;if(!file)return;busy=true;try{result=(await invoke(`database.${kind}`,kind==='backup'?{format:'custom',destination:file}:{format:'custom',source:file},active.name)).output;status=`${kind} completed on the Device.`}catch(error){status=(error as Error).message}finally{busy=false}}
  async function remove(){if(!active)return;await api(`/api/databases/bindings/${encodeURIComponent(active.id)}`,{method:'DELETE',body:JSON.stringify({confirm:true})});confirmDelete=false;active=undefined;await loadBindings()}
  function exportCsv(){if(!result?.columns||!result?.rows)return;const cell=(value:any)=>`"${String(value??'').replaceAll('"','""')}"`,body=[result.columns.map(cell).join(','),...result.rows.map((row:any[])=>row.map(cell).join(','))].join('\n'),url=URL.createObjectURL(new Blob([body],{type:'text/csv'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`${databaseName}-results.csv`;anchor.click();URL.revokeObjectURL(url)}
  onMount(()=>{try{queryHistory=JSON.parse(localStorage.getItem('atlas.database.history')??'[]');savedQueries=JSON.parse(localStorage.getItem('atlas.database.saved-queries')??'[]')}catch{}void discover()});
</script>
<DocumentationHelp topicId="databases" label="Database documentation"/>
<section class="panel native-database"><header><div><Database size={15}/><strong>PostgreSQL</strong><span>{contextId}</span></div><button title="Discover PostgreSQL resources" onclick={discover}><RefreshCw size={13}/></button></header>
  {#if !resource}<div class="database-candidates"><h3>Device PostgreSQL resources</h3>{#each candidates as candidate}<button onclick={()=>select(candidate)}><Database size={15}/><span><b>{candidate.host}:{candidate.port}</b><small>{candidate.source} · {candidate.evidence?.nativeStatus??'observed'}</small></span></button>{/each}{#if !candidates.length}<p>No PostgreSQL Surface is available. Scan the Device, install or update the signed PostgreSQL adapter, then adopt the resource in Signal.</p>{/if}{#each errors as error}<small>{error.message}</small>{/each}</div>
  {:else if !active}<form class="database-profile" onsubmit={event=>{event.preventDefault();void createProfile()}}><h3>New Device profile</h3><div><label>Name<input bind:value={profile.name}/></label><label>Environment<select bind:value={profile.environment}><option>development</option><option>staging</option><option>production</option></select></label></div><div><label>Host<input bind:value={profile.host}/></label><label>Port<input type="number" bind:value={profile.port}/></label></div><div><label>Initial database<input bind:value={profile.database}/></label><label>User<input bind:value={profile.username}/></label></div><label>TLS<select bind:value={profile.sslMode}><option>disable</option><option>allow</option><option>prefer</option><option>require</option><option>verify-ca</option><option>verify-full</option></select></label><label>Password<input type="password" autocomplete="off" bind:value={profile.password}/></label><label class="check"><input type="checkbox" bind:checked={profile.remember}/>Remember in encrypted Device vault</label><button type="submit" disabled={busy}><Plug size={13}/>Create native profile</button><small>The password is encrypted in this browser to the Device public key. Atlas and Signal never receive plaintext.</small></form>
  {:else}<div class="database-toolbar"><select bind:value={active} onchange={loadDatabases}>{#each bindings as binding}<option value={binding}>{binding.name}</option>{/each}</select><select bind:value={databaseName}>{#each databases as database}<option>{database}</option>{/each}</select><button onclick={()=>loadCatalog('schemas')}>Schemas</button><button onclick={()=>loadCatalog('tables')}>Tables</button><button onclick={()=>loadCatalog('activity')}>Activity</button><button onclick={snapshot}>Schema</button><button onclick={()=>confirmDelete=true} title="Delete profile"><Trash size={13}/></button></div>
    <div class="database-workspace"><nav><button class:active={section==='query'} onclick={()=>section='query'}>SQL</button><button class:active={section==='data'} onclick={()=>section='data'}>Data</button><button class:active={section==='history'} onclick={()=>section='history'}>History</button><button class:active={section==='backup'} onclick={()=>section='backup'}>Backup & restore</button><button onclick={compareSchema}>Compare schema</button></nav>{#if section==='query'}<div class="query"><textarea bind:value={sql} spellcheck="false"></textarea><div><button onclick={runQuery} disabled={busy}><Play size={13}/>Run</button><button onclick={exportCsv} disabled={!result?.rows}>CSV</button><input bind:value={savedName} placeholder="Saved query name"/><button onclick={saveQuery}>Save</button></div>{#each savedQueries as saved}<button onclick={()=>sql=saved.sql}>{saved.name}</button>{/each}</div>{:else if section==='tables'}<div class="table-list">{#each tables as row}<button onclick={()=>readTable(row)}>{row.join(' · ')}</button>{/each}</div>{:else if section==='history'}<div class="table-list">{#each queryHistory as item}<button onclick={()=>{sql=item.sql;databaseName=item.database;section='query'}}><b>{item.database} · {item.status}</b><small>{item.at}</small><code>{item.sql}</code></button>{/each}</div>{:else if section==='backup'}<div class="transfer"><label>Device backup destination<input bind:value={backupPath}/></label><button onclick={()=>transfer('backup')}>Create backup</button><label>Device restore source<input bind:value={restorePath}/></label><button class="danger" onclick={()=>transfer('restore')}>Restore</button></div>{/if}
      {#if schemaDifference}<p>{schemaDifference}</p>{/if}
      {#if result?.columns}<div class="results"><table><thead><tr>{#each result.columns as column}<th>{column}</th>{/each}</tr></thead><tbody>{#each result.rows??[] as row}<tr>{#each row as value}<td>{value===null?'NULL':String(value)}</td>{/each}</tr>{/each}</tbody></table></div>{:else if result}<pre>{JSON.stringify(result,null,2)}</pre>{/if}{#if catalog?.columns&&section!=='tables'}<div class="results"><table><thead><tr>{#each catalog.columns as column}<th>{column}</th>{/each}</tr></thead><tbody>{#each catalog.rows??[] as row}<tr>{#each row as value}<td>{value===null?'NULL':String(value)}</td>{/each}</tr>{/each}</tbody></table></div>{/if}</div>
  {/if}<footer>{busy?'Working…':status}</footer>
</section>
{#if confirmDelete}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>Delete Device profile?</h2><p>This deletes <b>{active.name}</b> and its encrypted Device-vault credential.</p><div><button onclick={()=>confirmDelete=false}>Cancel</button><button class="danger" onclick={remove}>Delete</button></div></div></div>{/if}
<style>
  .native-database{height:100%;min-height:0;display:flex;flex-direction:column;background:#0d1117;color:#dce5ed}.native-database>header,.database-toolbar{display:flex;gap:7px;align-items:center;padding:7px 9px;border-bottom:1px solid #252d36}.native-database>header div{display:flex;gap:7px;align-items:center;flex:1}.native-database>header span{color:#82909e;font-size:11px}.database-candidates,.database-profile{display:grid;gap:8px;padding:12px;overflow:auto}.database-candidates>button{display:flex;gap:8px;text-align:left;padding:9px;background:#111821;border:1px solid #2a333e;color:inherit}.database-candidates span{display:grid}.database-candidates small,.database-profile small{color:#8492a0}.database-profile>div{display:grid;grid-template-columns:1fr 1fr;gap:8px}.database-profile label,.transfer label{display:grid;gap:4px;font-size:11px}.database-profile input,.database-profile select,.database-toolbar select,.transfer input{padding:7px;background:#080b0f;border:1px solid #303946;color:inherit}.database-profile .check{display:flex}.database-workspace{display:flex;flex-direction:column;min-height:0;flex:1}.database-workspace nav{display:flex;gap:5px;padding:6px;border-bottom:1px solid #252d36}.database-workspace nav .active{background:#244567}.query{display:grid;grid-template-rows:minmax(100px,1fr) auto;gap:6px;padding:7px;max-height:42%}.query textarea{resize:none;background:#080b0f;color:#dce5ed;border:1px solid #303946;padding:9px;font:12px/1.5 ui-monospace,monospace}.query>div{display:flex;gap:6px}.results{overflow:auto;min-height:0;flex:1}.results table{border-collapse:collapse;min-width:100%;font:11px ui-monospace,monospace}.results th,.results td{padding:6px 8px;border:1px solid #252d36;white-space:nowrap;text-align:left}.results th{position:sticky;top:0;background:#141b24}.table-list,.transfer{display:grid;gap:7px;padding:8px;overflow:auto}.table-list button{text-align:left}.native-database>footer{margin-top:auto;padding:7px 9px;border-top:1px solid #252d36;color:#8d9aa7;font-size:11px}.native-database pre{overflow:auto;padding:8px}
</style>
