<script lang="ts">
  import {onMount} from 'svelte';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import Database from '@lucide/svelte/icons/database';import Plug from '@lucide/svelte/icons/plug';import Square from '@lucide/svelte/icons/square';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  export let state:WorkbenchState;export let params:{contextId?:string}={};let contextId=params.contextId??state.snapshot().contextId,candidates:any[]=[],errors:any[]=[],sessions:any[]=[],active:any,status='Discovering database services…',dialog=false,form={engine:'postgres',host:'127.0.0.1',port:5432,database:'',user:'',password:'',readOnly:false,label:''};
  async function discover(){status='Discovering through effective terminal authority…';try{const value=await api<any>(`/api/databases/discover?contextId=${encodeURIComponent(contextId)}`);candidates=value.items??[];errors=value.errors??[];status=`${candidates.length} database service${candidates.length===1?'':'s'} detected`;}catch(error){status=(error as Error).message;}}
  async function load(){try{sessions=(await api<any>('/api/databases/sessions')).items??[];active=sessions.find(item=>item.contextId===contextId&&item.status==='live');}catch{}}
  function use(candidate:any){form={...form,engine:candidate.engine,host:candidate.host,port:candidate.port??form.port,label:`${candidate.engine} · ${candidate.host}:${candidate.port}`};}
  async function connect(){status='Starting isolated database workbench…';try{const value=await api<any>('/api/databases/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contextId,...form})});form.password='';active=value.session;await load();status='Database workbench live';}catch(error){form.password='';const diagnosticSessionId=(error as any).body?.diagnosticSessionId;if(diagnosticSessionId)window.dispatchEvent(new CustomEvent('atlas:open-logs',{detail:{diagnosticId:diagnosticSessionId}}));status=(error as Error).message;}}
  async function stop(){if(!active)return;try{await api(`/api/databases/sessions/${encodeURIComponent(active.id)}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true})});active=undefined;dialog=false;await load();}catch(error){status=(error as Error).message;}}
  onMount(()=>{void discover();void load()});
</script>
<section class="panel database-panel"><header><div><Database size={15}/><strong>Databases</strong><span>{contextId}</span></div><div><button title="Discover database services" onclick={discover}><RefreshCw size={13}/></button></div></header>{#if active}<div class="database-session-bar"><span>{active.label} · {active.engine} · isolated non-root sidecar</span><button title="Stop database session" onclick={()=>dialog=true}><Square size={12}/></button></div><iframe title="Database workbench" src={active.proxyPath}></iframe>{:else}<div class="database-layout"><section><h3>Detected services</h3>{#each candidates as candidate}<button class="database-candidate" onclick={()=>use(candidate)}><Database size={15}/><span><b>{candidate.engine}</b><small>{candidate.host}:{candidate.port} · {candidate.source}</small></span></button>{/each}{#if !candidates.length}<p>No known database listener yet. Discovery does not inspect credentials.</p>{/if}{#each errors as error}<p class="database-warning">{error.message}</p>{/each}</section><form onsubmit={event=>{event.preventDefault();void connect()}}><h3>Connection</h3><label>Engine<select bind:value={form.engine}><option>postgres</option><option>mysql</option><option>mariadb</option><option>redis</option><option>mongodb</option><option>mssql</option><option>oracle</option><option>sqlite</option></select></label><label>Host<input bind:value={form.host}/></label><label>Port<input type="number" bind:value={form.port}/></label><label>Database<input bind:value={form.database}/></label><label>User<input bind:value={form.user}/></label><label>Password<input type="password" bind:value={form.password} autocomplete="off"/></label><label class="database-check"><input type="checkbox" bind:checked={form.readOnly}/> Read-only session</label><button class="database-connect" type="submit"><Plug size={13}/>Open workbench</button><small>Credentials are passed only to the ephemeral sidecar and are never stored by Atlas.</small></form></div>{/if}<footer>{status}</footer>{#if dialog}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>Stop database workbench?</h2><p>The loopback sidecar and its in-memory connection will be destroyed.</p><div><button onclick={()=>dialog=false}>Cancel</button><button class="danger" onclick={stop}>Stop</button></div></div></div>{/if}</section>
