<script lang="ts">
  import {onMount} from 'svelte';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import RotateCw from '@lucide/svelte/icons/rotate-cw';import Rocket from '@lucide/svelte/icons/rocket';import ExternalLink from '@lucide/svelte/icons/external-link';
  export let params:Record<string,unknown>;export let state:WorkbenchState;
  let contextId=String(params.contextId??state.snapshot().contextId),repositoryPath=String(params.repositoryPath??'/workspace'),view=String(params.view??'overview'),name='web',environment='production',commitSha='',installCommand='npm ci',buildCommand='npm run build',startCommand='npm start',port=8000,healthPath='/',status='',busy=false,confirmDeploy=false,plan:any,items:any[]=[],selectedId='',detail:any,logs:any[]=[],browserDiagnostics:any,browserExpression='document.title',domains:any,vanitySlug='',customHostname='';
  const manifest=()=>({protocolVersion:'fngk.project.v1',name,commands:{...(installCommand.trim()?{install:installCommand.trim()}:{}),...(buildCommand.trim()?{build:buildCommand.trim()}:{}),start:startCommand.trim()},port:Number(port),health:{protocol:'http',path:healthPath,timeoutMs:30_000},artifacts:[{path:'dist',kind:'web'}],restartPolicy:'on-failure',environments:{[environment]:{variables:{NODE_ENV:environment},secretReferences:[]}},routes:[{name}]});
  async function refresh(){busy=true;try{const value=await api<any>(`/api/deployments?contextId=${encodeURIComponent(contextId)}`);items=value.deployments??[];selectedId=selectedId||items[0]?.id||'';if(selectedId){detail=await api<any>(`/api/deployments/${encodeURIComponent(selectedId)}`);if(view==='logs'){const value=await api<any>(`/api/deployments/${encodeURIComponent(selectedId)}/logs?after=-1&limit=500`);logs=value.items??[]}if(view==='routes')domains=await api<any>(`/api/deployments/${encodeURIComponent(selectedId)}/domains`)}status=items.length?`${items.length} retained deployment${items.length===1?'':'s'}`:'No retained deployments yet.'}catch(error){status=(error as Error).message}finally{busy=false}}
  async function preview(){try{plan=await api('/api/deployments/plan',{method:'POST',body:JSON.stringify({contextId,repositoryPath,environment,commitSha,manifest:manifest()})});status='Plan validated. No Device command was run.'}catch(error){status=(error as Error).message}}
  async function deploy(){confirmDeploy=false;busy=true;try{const result:any=await api('/api/deployments/execute',{method:'POST',body:JSON.stringify({contextId,repositoryPath,environment,commitSha,manifest:manifest(),confirm:true})});selectedId=result.deploymentId;status=`Release healthy at ${result.url}`;await refresh()}catch(error){status=(error as Error).message}finally{busy=false}}
  async function rollback(){if(!selectedId)return;busy=true;try{await api(`/api/deployments/${encodeURIComponent(selectedId)}/rollback`,{method:'POST',body:JSON.stringify({confirm:true,contextId})});status='Rollback is healthy and the route has switched.';await refresh()}catch(error){status=(error as Error).message}finally{busy=false}}
  async function diagnose(){if(!selectedId)return;busy=true;try{browserDiagnostics=await api(`/api/deployments/${encodeURIComponent(selectedId)}/diagnostics`,{method:'POST',body:JSON.stringify({screenshot:false})});status=browserDiagnostics.ok?'Browser diagnostics passed.':'Browser diagnostics found a failure.'}catch(error){status=(error as Error).message}finally{busy=false}}
  async function evaluateBrowser(){if(!selectedId||!browserExpression.trim())return;busy=true;try{browserDiagnostics=await api(`/api/deployments/${encodeURIComponent(selectedId)}/diagnostics`,{method:'POST',body:JSON.stringify({contextId,expression:browserExpression,confirm:true})});status='Audited browser expression completed.'}catch(error){status=(error as Error).message}finally{busy=false}}
  async function domainAction(action:'vanity'|'custom'|'verify'){if(!selectedId)return;busy=true;try{const method=action==='vanity'?'PUT':'POST',body=action==='vanity'?{slug:vanitySlug,confirm:true}:action==='custom'?{hostname:customHostname,confirm:true}:{confirm:true};await api(`/api/deployments/${encodeURIComponent(selectedId)}/domains/${action}`,{method,body:JSON.stringify(body)});status=`Domain ${action} completed.`;domains=await api<any>(`/api/deployments/${encodeURIComponent(selectedId)}/domains`)}catch(error){status=(error as Error).message}finally{busy=false}}
  const payload=(item:any)=>{try{return atob(String(item.body_base64??''))}catch{return ''}};
  $: releases=detail?.releases??[];$: events=detail?.events??[];$: current=[...releases].reverse().find((item:any)=>item.status==='healthy')??releases.at(-1);$: publicUrl=[...events].reverse().find((item:any)=>item.detail?.url)?.detail?.url;
  onMount(()=>{if(view!=='overview'||params.deploymentId)void refresh();if(view==='logs'){const timer=setInterval(()=>void refresh(),1000);return()=>clearInterval(timer)}});
</script>
<section class="panel deployment-panel" data-view={view}>
  <header><strong>{view==='overview'?'Deployment':view.replace('-', ' & ')}</strong><span>{contextId}</span><button title="Refresh deployment data" onclick={refresh} disabled={busy}><RotateCw size={13}/></button></header>
  {#if view==='overview'}
    <form class="deployment-form" onsubmit={(event)=>{event.preventDefault();void preview()}}><label>Repository path<input bind:value={repositoryPath}/></label><div><label>Name<input bind:value={name}/></label><label>Environment<select bind:value={environment}><option>development</option><option>staging</option><option>production</option></select></label></div><label>Immutable commit SHA<input bind:value={commitSha} placeholder="40-character production commit"/></label><div><label>Install<input bind:value={installCommand}/></label><label>Build<input bind:value={buildCommand}/></label></div><label>Start command<input bind:value={startCommand}/></label><div><label>Port<input type="number" min="1" max="65535" bind:value={port}/></label><label>Health path<input bind:value={healthPath}/></label></div><footer><button type="submit">Preview plan</button><button type="button" class="primary" onclick={()=>confirmDeploy=true}><Rocket size={13}/>Deploy immutable release</button></footer></form>
    {#if plan}<pre class="deployment-json">{JSON.stringify(plan,null,2)}</pre>{/if}
  {:else if view==='plan'}
    <div class="deployment-empty"><p>Deployment plans are generated from <code>.fngk/project.json</code> or the Deployment form and execute in strict phase order.</p><ol><li>Verify commit</li><li>Extract versioned release</li><li>Install and build</li><li>Start managed process</li><li>Pass Device-local health check</li><li>Inventory artifacts</li><li>Publish route</li></ol></div>
  {:else if view==='browser'}
    {#if publicUrl}<div class="deployment-browser"><div><a href={publicUrl} target="_blank" rel="noreferrer">{publicUrl}<ExternalLink size={13}/></a><button onclick={diagnose} disabled={busy}>Reload & capture</button><input bind:value={browserExpression} aria-label="Browser console expression"/><button onclick={evaluateBrowser} disabled={busy}>Evaluate (confirmed)</button></div>{#if browserDiagnostics}<pre>{JSON.stringify(browserDiagnostics,null,2)}</pre>{/if}<iframe title="Deployed project browser" src={publicUrl}></iframe></div>{:else}<div class="deployment-empty">No healthy release with a public URL is selected.</div>{/if}
  {:else if view==='logs'}
    <pre class="deployment-logs">{[...events.filter((event:any)=>event.detail?.output).map((event:any)=>`[${event.event}] ${event.detail.output}\n`),...logs.map(item=>`[${item.stream}] ${payload(item)}`)].join('')||'No retained build or managed-process output for the selected deployment.'}</pre>
  {:else if view==='runs'}
    <div class="deployment-list">{#each items as item}<button class:active={selectedId===item.id} onclick={()=>{selectedId=item.id;void refresh()}}><b>{item.name}</b><span>{item.environment} · {item.status}</span><small>{item.repository_path}</small></button>{/each}</div>
  {:else if view==='routes'}
    <div class="deployment-empty"><h3>Route & domains</h3><p>Generated fallback: {domains?.generated??publicUrl??'not published'}</p><p>Effective: {domains?.effective??publicUrl??'not published'} · Connection: {current?.connection_id??'not associated'}</p><label>Vanity slug<input bind:value={vanitySlug}/></label><button onclick={()=>domainAction('vanity')}>Reserve vanity hostname</button><label>Custom domain<input bind:value={customHostname} placeholder="app.example.com"/></label><button onclick={()=>domainAction('custom')}>Attach domain & show TXT proof</button><button onclick={()=>domainAction('verify')}>Verify DNS and activate</button>{#if domains?.customDomain}<pre>{JSON.stringify(domains.customDomain,null,2)}</pre>{/if}<p>The generated Signal hostname remains as fallback. Signal enforces entitlements and DNS ownership.</p></div>
  {:else if view==='artifacts'}
    <div class="deployment-list">{#each current?.artifacts??[] as artifact}<div><b>{artifact.path}</b><span>{artifact.kind??'release artifact'}</span></div>{/each}{#if !(current?.artifacts?.length)}<p>No artifacts inventoried.</p>{/if}</div>
  {:else}
    <div class="deployment-list">{#each events as event}<div><b>{event.event}</b><span>{event.phase??'deployment'} · {new Date(event.created_at).toLocaleString()}</span><small>{JSON.stringify(event.detail??{})}</small></div>{/each}{#if !events.length}<p>No retained deployment history.</p>{/if}</div><button onclick={rollback} disabled={!selectedId||busy}>Roll back and switch route</button>
  {/if}
  <footer class="deployment-status">{busy?'Working…':status}</footer>
</section>
{#if confirmDeploy}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>Deploy immutable release?</h2><p>Atlas will extract <code>{commitSha}</code> into a new versioned directory on {contextId}, run the declared build, health-check the managed process, and publish only after it passes.</p><div><button onclick={()=>confirmDeploy=false}>Cancel</button><button class="primary" onclick={deploy}>Deploy</button></div></div></div>{/if}

<style>
  .deployment-panel{height:100%;min-height:0;display:flex;flex-direction:column;background:#0d1117;color:#d8e1ea}.deployment-panel>header{display:flex;gap:8px;align-items:center;padding:8px 10px;border-bottom:1px solid #252c35}.deployment-panel>header span{flex:1;color:#82909e;font-size:11px}.deployment-form{display:grid;gap:9px;padding:12px;overflow:auto}.deployment-form label{display:grid;gap:4px;font-size:11px;color:#98a6b4}.deployment-form>div{display:grid;grid-template-columns:1fr 1fr;gap:8px}.deployment-form input,.deployment-form select{min-width:0;padding:7px;background:#080b0f;border:1px solid #303844;color:#e3ebf3}.deployment-form footer{display:flex;gap:7px}.deployment-json,.deployment-logs{margin:0;padding:12px;overflow:auto;white-space:pre-wrap;flex:1;background:#080b0f}.deployment-list{display:grid;gap:6px;padding:8px;overflow:auto}.deployment-list>*{display:grid;gap:2px;text-align:left;padding:8px;border:1px solid #252c35;background:#111720;color:inherit}.deployment-list .active{border-color:#5183b8}.deployment-list span,.deployment-list small{color:#8795a3}.deployment-empty{padding:16px;overflow:auto}.deployment-browser{display:flex;flex-direction:column;min-height:0;flex:1}.deployment-browser>div{padding:7px}.deployment-browser a{display:inline-flex;align-items:center;gap:5px;color:#7db4e8}.deployment-browser iframe{border:0;background:white;flex:1;min-height:0}.deployment-status{margin-top:auto;padding:7px 10px;border-top:1px solid #252c35;color:#8f9dac;font-size:11px}
</style>
