<script lang="ts">
 import {onMount} from 'svelte';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import ChevronRight from '@lucide/svelte/icons/chevron-right';import CircleAlert from '@lucide/svelte/icons/circle-alert';import Database from '@lucide/svelte/icons/database';import FileCode from '@lucide/svelte/icons/file-code';import Network from '@lucide/svelte/icons/network';import ShieldCheck from '@lucide/svelte/icons/shield-check';
 export let state:WorkbenchState;let selection:any,running=false,result:any,args='[]',contextId='local',semantic:any,loading=false,error='',generation=0;
 const icon=(kind:string)=>kind==='database'?Database:kind==='module'||kind==='function'?FileCode:kind==='identity'?ShieldCheck:Network;
 const related=(id:string)=>semantic?.relatedEntities?.find((value:any)=>value.id===id);
 const safeEntries=(value:any)=>Object.entries(value??{}).filter(([,item])=>item!==undefined&&item!==null&&typeof item!=='object').slice(0,30);
 const sections=()=>semantic?.views?.[0]?.sections??[{kind:'properties',title:'Identity'},{kind:'relationships',title:'Relationships'},{kind:'evidence',title:'Why Atlas believes this'},{kind:'timeline',title:'Recent changes'}];
 const sectionEntries=(descriptor:any)=>{const entries=safeEntries(semantic?.entity?.attributes);return descriptor.fields?.length?entries.filter(([key])=>descriptor.fields.includes(key)):entries};
 const sectionAssertions=(descriptor:any)=>descriptor.predicate?semantic.assertions.filter((value:any)=>value.predicate===descriptor.predicate):semantic.assertions;
 async function loadSemantic(){const token=++generation;if(!selection?.semantic){semantic=undefined;return}loading=true;error='';try{const [detail,timeline]=await Promise.all([api<any>(`/api/atlas/entities/${encodeURIComponent(selection.id)}?contextId=${encodeURIComponent(selection.contextId??contextId)}`),api<any>(`/api/atlas/entities/${encodeURIComponent(selection.id)}/timeline?contextId=${encodeURIComponent(selection.contextId??contextId)}`)]);if(token===generation)semantic={...detail,timeline:timeline.items}}catch(value){if(token===generation)error=(value as Error).message}finally{if(token===generation)loading=false}}
 async function run(){if(!selection?.id||running)return;running=true;try{const symbolId=semantic?.entity?.attributes?.legacyId??selection.id;result=await api<any>('/api/run',{method:'POST',body:JSON.stringify({contextId:selection.contextId??contextId,symbolId,args:JSON.parse(args),consent:true})})}catch(value){result={classification:'unavailable',error:(value as Error).message}}finally{running=false}}
 function choose(entity:any){state.select({id:entity.id,type:entity.kind,contextId:entity.contextId,label:entity.label,semantic:true})}
 onMount(()=>state.subscribe(value=>{selection=value.selection;contextId=value.contextId;result=undefined;void loadSemantic()}));
</script>
<section class="panel details-panel semantic-details"><header><strong>Inspector</strong>{#if (semantic?.entity?.kind??selection?.type)==='function'}<button onclick={run} disabled={running} title="Run this function in the Atlas sandbox">{running?'Running…':'Run function'}</button>{/if}</header>
{#if loading}<div class="empty-copy">Resolving semantic evidence…</div>{:else if error}<div class="panel-error">{error}</div>{:else if semantic?.entity}
 {@const entity=semantic.entity}{@const KindIcon=icon(entity.kind)}
 <div class="entity-head"><KindIcon size={22}/><div><small>{entity.kind} · {entity.namespace}</small><h2>{entity.label}</h2></div><span class:stale={entity.stale}>{entity.stale?'stale':'current'}</span></div>
 {#if entity.kind==='function'}<label class="args-field">Arguments (JSON)<input bind:value={args} aria-label="Function arguments"/></label>{/if}{#if result}<pre class="operation-result">{JSON.stringify(result,null,2)}</pre>{/if}
 {#each sections() as descriptor}
  <section><h3>{descriptor.title??descriptor.kind}</h3>
  {#if descriptor.kind==='properties'||descriptor.kind==='metrics'||descriptor.kind==='documentation'}<dl>{#each sectionEntries(descriptor) as [key,value]}<dt>{key}</dt><dd>{String(value)}</dd>{:else}<p>{descriptor.empty??'No matching properties.'}</p>{/each}</dl>
  {:else if descriptor.kind==='relationships'}<div class="relations">{#each sectionAssertions(descriptor) as assertion}{@const other=related(assertion.subjectId===entity.id?assertion.objectId:assertion.subjectId)}<button onclick={()=>other&&choose(other)} disabled={!other}><span><b>{assertion.predicate.replaceAll('-',' ')}</b><small>{assertion.classification} · {Math.round(assertion.confidence*100)}%</small></span><ChevronRight size={13}/><em>{other?.label??String(assertion.value??'evidence')}</em></button>{:else}<p>{descriptor.empty??'No semantic relationships yet.'}</p>{/each}</div>
  {:else if descriptor.kind==='evidence'}{#each sectionAssertions(descriptor) as assertion}<article class="evidence"><div><span class:inferred={assertion.classification==='inferred'}>{assertion.classification}</span><b>{assertion.predicate.replaceAll('-',' ')}</b><small>{assertion.interpreterId}@{assertion.interpreterVersion}</small></div><p>{assertion.explanation}</p><footer>{assertion.evidence.length} evidence reference{assertion.evidence.length===1?'':'s'} · {Math.round(assertion.confidence*100)}% confidence</footer></article>{:else}<p>{descriptor.empty??'No assertions support this entity yet.'}</p>{/each}
  {:else if descriptor.kind==='timeline'}{#each (semantic.timeline??[]).slice(0,12) as item}<div class="timeline"><i></i><span><b>{item.changeType}</b><small>{item.interpreterId} · {new Date(item.changedAt).toLocaleString()}</small></span></div>{:else}<p>{descriptor.empty??'No retained changes.'}</p>{/each}
  {:else if descriptor.kind==='hierarchy'}<div class="relations">{#if entity.parentId&&related(entity.parentId)}{@const parent=related(entity.parentId)}<button onclick={()=>choose(parent)}><span><b>parent</b><small>{parent.kind}</small></span><ChevronRight size={13}/><em>{parent.label}</em></button>{:else}<p>{descriptor.empty??'No parent relationship.'}</p>{/if}</div>{/if}
  </section>
 {/each}
{:else if selection}<div class="detail-title">{selection.label??selection.name??selection.id}</div><dl>{#each Object.entries(selection) as [key,value]}<dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value)}</dd>{/each}</dl>{:else}<div class="empty-copy"><CircleAlert size={24}/>Select a workload, capability, process, module, or function to inspect why Atlas believes it exists.</div>{/if}</section>
<style>
 .semantic-details{overflow:auto}.entity-head{display:flex;align-items:center;gap:9px;padding:12px;border-bottom:1px solid #26323e}.entity-head>:global(svg){color:#62d9cc}.entity-head div{min-width:0;flex:1}.entity-head small{color:#748496;font-size:9px;text-transform:uppercase}.entity-head h2{overflow:hidden;margin:2px 0 0;color:#edf4fa;font-size:14px;text-overflow:ellipsis;white-space:nowrap}.entity-head>span{border-radius:10px;background:#233727;padding:3px 7px;color:#9ee6a8;font-size:9px}.entity-head>span.stale{background:#3f2424;color:#ff9b9b}.semantic-details section{padding:10px 12px;border-bottom:1px solid #202b35}.semantic-details h3{margin:0 0 8px;color:#8999a9;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.semantic-details p{margin:6px 0;color:#768594;font-size:10px}.relations{display:grid;gap:4px}.relations button{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:5px;border:1px solid #273440;border-radius:5px;background:#101820;padding:6px;text-align:left}.relations button:hover:not(:disabled){border-color:#4c667b}.relations button:disabled{opacity:.75}.relations span{display:grid}.relations b{color:#c9d5df;font-size:10px}.relations small,.relations em{overflow:hidden;color:#718191;font-size:9px;font-style:normal;text-overflow:ellipsis;white-space:nowrap}.evidence{margin:6px 0;border:1px solid #273440;border-radius:6px;background:#0c1319;padding:7px}.evidence>div{display:flex;align-items:center;gap:6px}.evidence span{border-radius:8px;background:#24392c;padding:2px 5px;color:#9bd7a8;font-size:8px;text-transform:uppercase}.evidence span.inferred{background:#3d3220;color:#f3cc76}.evidence b{color:#d3dee7;font-size:10px}.evidence small{margin-left:auto;color:#667585;font-size:8px}.evidence footer{color:#697988;font-size:8px}.timeline{display:flex;align-items:center;gap:7px;padding:4px 0}.timeline i{width:6px;height:6px;border-radius:50%;background:#62d9cc}.timeline span{display:grid}.timeline b{font-size:10px}.timeline small{color:#697988;font-size:8px}.empty-copy{gap:8px}
</style>
