<script lang="ts">
  import {onMount} from 'svelte';
  import type {WorkbenchState} from '../lib/workbench-state.js';
  import {loadContextCatalog} from '../lib/context-catalog.js';
  import {deviceLabelStore,resolveDeviceIdentity} from '../lib/device-identity.js';
  import {atlasDeviceColors,deviceAppearanceStore} from '../lib/device-appearance.js';
  import Database from '@lucide/svelte/icons/database';
  import Network from '@lucide/svelte/icons/network';
  import Rocket from '@lucide/svelte/icons/rocket';
  import SquareTerminal from '@lucide/svelte/icons/square-terminal';
  export let state:WorkbenchState;
  let device:any;let label='';let editing=false;let appearanceRevision=0;
  async function refresh(){const catalog=await loadContextCatalog(false,state.snapshot().connection.profile);device=catalog.contexts.find((item:any)=>item.id===state.snapshot().contextId&&item.kind==='fngk-device');label=device?.device?.id?deviceLabelStore.getLabel(device.device.id)??resolveDeviceIdentity(device.device.id).label:'';}
  function save(){if(device?.device?.id)deviceLabelStore.setLabel(device.device.id,label);editing=false;}
  function setColor(color:(typeof atlasDeviceColors)[number]){if(device?.device?.id){deviceAppearanceStore.set(device.device.id,color);appearanceRevision++;}}
  function shortcut(name:'ports'|'deployment'|'database'|'terminal'){if(!device)return;if(name==='ports')window.dispatchEvent(new CustomEvent('atlas:open-ports',{detail:{contextId:device.id}}));else if(name==='deployment')window.dispatchEvent(new CustomEvent('atlas:open-deployment',{detail:{contextId:device.id}}));else if(name==='database')window.dispatchEvent(new CustomEvent('atlas:open-database',{detail:{contextId:device.id}}));else window.dispatchEvent(new CustomEvent('atlas:open-terminal',{detail:{contextId:device.id,target:device.id,title:device.name??'Terminal',newSession:true}}));}
  onMount(()=>{void refresh();const unsubscribe=state.subscribe(()=>void refresh()),appearanceChanged=()=>appearanceRevision++;window.addEventListener('atlas:device-appearance-changed',appearanceChanged);return()=>{unsubscribe();window.removeEventListener('atlas:device-appearance-changed',appearanceChanged)}});
</script>
<section class="device-details" aria-label="Device details">
  <header class="device-details-header"><strong>Device details</strong><button class="collapse" title="Collapse device details" aria-label="Collapse device details" onclick={()=>window.dispatchEvent(new CustomEvent('atlas:toggle-panel-collapse',{detail:{panelId:'atlas.device-details'}}))}>−</button></header>
  {#if device}{@const identity=resolveDeviceIdentity(device.device.id)}{@const color=appearanceRevision>=0?deviceAppearanceStore.get(device.device.id).color??identity.color:identity.color}
    <div class="device-profile"><b class="glyph" style={`--atlas-device-color:var(--atlas-device-${color})`}>{identity.glyph}</b><div><strong>{deviceLabelStore.getLabel(device.device.id)??identity.label}</strong><small>{device.name}</small></div></div>
    {#if editing}<form onsubmit={(event)=>{event.preventDefault();save()}}><input bind:value={label} aria-label="Device label" maxlength="32"/><button>Save</button><button type="button" onclick={()=>editing=false}>Cancel</button></form>{:else}<div class="actions"><button class="rename" onclick={()=>editing=true}>Rename Atlas label</button><button onclick={()=>window.dispatchEvent(new Event('atlas:open-device-lifecycle'))}>Manage Device</button></div>{/if}
    <dl><div><dt>State</dt><dd>{device.online?'Online':'Offline'}</dd></div><div><dt>Platform</dt><dd>{device.device?.platform??'Unknown'}</dd></div><div><dt>Device ID</dt><dd>{device.device?.id}</dd></div></dl>
    <footer class="device-shortcuts" aria-label="Device shortcuts"><button title="Open published ports" onclick={()=>shortcut('ports')}><Network size={14}/><span>Ports</span></button><button title="Open deployments" onclick={()=>shortcut('deployment')}><Rocket size={14}/><span>Deploy</span></button><button title="Open databases" onclick={()=>shortcut('database')}><Database size={14}/><span>Data</span></button><button title="Open terminal" onclick={()=>shortcut('terminal')}><SquareTerminal size={14}/><span>Terminal</span></button></footer>
    <div class="device-colors" aria-label="Device color">{#each atlasDeviceColors as choice}<button title={`Use ${choice}`} aria-label={`Use ${choice}`} class:chosen={color===choice} style={`--device-choice:var(--atlas-device-${choice})`} onclick={()=>setColor(choice)}></button>{/each}</div>
  {:else}<p>Select an FNGK device to inspect its local Atlas identity and connection state.</p>{/if}
</section>
<style>.device-details{height:100%;padding:0 10px;overflow:auto;font-size:11px}.device-details-header{height:36px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--atlas-border)}.device-profile{display:flex;gap:8px;align-items:center;padding-top:10px}.device-profile>div{min-width:0;flex:1}.collapse{width:24px;height:24px;border:0;background:transparent} .glyph{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;color:var(--atlas-device-color);background:color-mix(in srgb,var(--atlas-device-color) 20%,transparent)}small,dt,p{color:var(--atlas-muted)}small{display:block}.device-details form,.actions{display:flex;gap:4px;margin-top:10px}.device-details input{min-width:0;flex:1}.rename{margin-top:0}dl{margin:10px 0;display:grid;gap:7px}dl div{display:grid;grid-template-columns:70px 1fr;gap:6px}dt,dd{margin:0}dd{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.device-shortcuts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:3px;margin:0;padding:6px 0;border-top:1px solid var(--atlas-border)}.device-shortcuts button{display:grid;justify-items:center;gap:2px;min-width:0;border:0;background:transparent;padding:4px 1px;color:var(--atlas-muted);font-size:9px}.device-shortcuts button:hover{color:var(--atlas-text);background:var(--atlas-hover)}.device-shortcuts span{overflow:hidden;text-overflow:ellipsis;max-width:100%}.device-colors{display:flex;gap:5px;padding:8px 0;border-top:1px solid var(--atlas-border)}.device-colors button{display:block;width:16px;height:16px;padding:0;border:2px solid transparent;border-radius:50%;background:var(--device-choice)}.device-colors button.chosen{border-color:var(--atlas-text);box-shadow:0 0 0 1px var(--atlas-surface)}</style>
