<script lang="ts">
  import {onMount} from 'svelte';import {EditorState} from '@codemirror/state';import {EditorView,keymap,lineNumbers,highlightActiveLine,highlightActiveLineGutter,drawSelection,dropCursor,rectangularSelection} from '@codemirror/view';import {defaultKeymap,history,historyKeymap} from '@codemirror/commands';import {syntaxHighlighting,HighlightStyle,bracketMatching,foldGutter,foldKeymap} from '@codemirror/language';import {tags} from '@lezer/highlight';import {javascript} from '@codemirror/lang-javascript';import {css} from '@codemirror/lang-css';import {json} from '@codemirror/lang-json';import {html} from '@codemirror/lang-html';import {markdown} from '@codemirror/lang-markdown';import {python} from '@codemirror/lang-python';import {api} from '../lib/api.js';import Save from '@lucide/svelte/icons/save';
  export let params:{contextId?:string;path?:string;line?:number;panelId?:string}={};let host:HTMLDivElement;let view:EditorView|undefined;let fingerprint='';let status='Opening…';let dirty=false;let announcedDirty=false;let saving=false;let disposed=false;
  const atlasHighlight=HighlightStyle.define([{tag:[tags.keyword,tags.modifier],color:'#c792ea'},{tag:[tags.function(tags.variableName),tags.definition(tags.variableName)],color:'#82aaff'},{tag:[tags.string,tags.special(tags.string)],color:'#c3e88d'},{tag:[tags.number,tags.bool,tags.null],color:'#f78c6c'},{tag:[tags.typeName,tags.className],color:'#ffcb6b'},{tag:tags.comment,color:'#637777',fontStyle:'italic'},{tag:[tags.operator,tags.punctuation],color:'#89ddff'},{tag:[tags.propertyName,tags.attributeName],color:'#f07178'},{tag:tags.tagName,color:'#ff5370'}]);
  const base64=(value:string)=>{const bytes=new TextEncoder().encode(value);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)};
  function language(file:string){const ext=file.toLowerCase().split('.').pop()??'';if(ext==='svelte')return html();if(['ts','tsx','js','jsx','mjs','cjs'].includes(ext))return javascript({typescript:['ts','tsx'].includes(ext),jsx:['tsx','jsx'].includes(ext)});if(['css','scss','sass','less'].includes(ext))return css();if(['json','jsonc'].includes(ext))return json();if(['html','htm'].includes(ext))return html();if(['md','markdown'].includes(ext))return markdown();if(ext==='py')return python();return [];}
  function announce(){window.dispatchEvent(new CustomEvent('atlas:file-dirty',{detail:{panelId:params.panelId,path:params.path,dirty}}));}
  async function save(){if(!view||!params.path||saving)return;const submitted=view.state.doc.toString();saving=true;status='Saving…';try{const result=await api<any>('/api/files/content',{method:'PUT',body:JSON.stringify({contextId:params.contextId??'local',path:params.path,contentBase64:base64(submitted),expectedFingerprint:fingerprint})});if(disposed)return;fingerprint=result.fingerprint;dirty=view.state.doc.toString()!==submitted;announcedDirty=dirty;status=dirty?'Modified after save':`Saved via ${result.route.kind}`;announce();}catch(error:any){if(!disposed)status=error.status===409?'Conflict: file changed on host':error.message}finally{saving=false}}
  onMount(()=>{let alive=true;disposed=false;const reveal=(event:Event)=>{const detail=(event as CustomEvent<{panelId?:string;line?:number}>).detail;if(detail.panelId!==params.panelId||!view||!detail.line)return;const line=view.state.doc.line(Math.min(detail.line,view.state.doc.lines));view.dispatch({selection:{anchor:line.from},effects:EditorView.scrollIntoView(line.from,{y:'center'})});view.focus()};window.addEventListener('atlas:file-reveal',reveal);void(async()=>{try{const opened=await api<any>(`/api/files/content?contextId=${encodeURIComponent(params.contextId??'local')}&path=${encodeURIComponent(params.path??'')}`);if(!alive)return;if(opened.binary||opened.tooLarge||typeof opened.text!=='string'||!opened.fingerprint){status=opened.binary?`Binary file · ${opened.bytes} bytes · read-only`:opened.tooLarge?'File exceeds editor limit · read-only':'File cannot be edited.';return}fingerprint=opened.fingerprint;status=`${opened.bytes} bytes · ${opened.route.kind} · ${opened.route.effectiveIdentity}`;const doc=opened.text,line=Math.min(Math.max(1,params.line??1),doc.split(/\r?\n/).length),anchor=doc.split(/\r?\n/).slice(0,line-1).reduce((total:number,current:string)=>total+current.length+1,0);view=new EditorView({parent:host,state:EditorState.create({doc,selection:{anchor},extensions:[language(params.path??''),syntaxHighlighting(atlasHighlight),lineNumbers(),foldGutter(),history(),drawSelection(),dropCursor(),rectangularSelection(),highlightActiveLine(),highlightActiveLineGutter(),bracketMatching(),keymap.of([...defaultKeymap,...historyKeymap,...foldKeymap,{key:'Mod-s',run:()=>{void save();return true}}]),EditorView.contentAttributes.of({'aria-label':`Editor for ${params.path}`}),EditorView.updateListener.of(update=>{if(update.docChanged){dirty=true;status='Modified';if(!announcedDirty){announcedDirty=true;announce();}}}),EditorView.theme({'&':{height:'100%'},'.cm-scroller':{overflow:'auto'},'.cm-content':{caretColor:'#f4f8fb'}})]})});view.focus();if(params.line)view.dispatch({effects:EditorView.scrollIntoView(anchor,{y:'center'})});}catch(error){if(alive)status=(error as Error).message}})();return()=>{alive=false;disposed=true;window.removeEventListener('atlas:file-reveal',reveal);view?.destroy()}});
</script>
<section class="panel file-panel"><header><div><strong>{dirty?'● ':''}{params.path??'File'}</strong><span>{status}</span></div><button onclick={save} disabled={!dirty||saving} title="Save file" aria-label="Save file"><Save size={14}/></button></header><div class="editor" bind:this={host}></div></section>
