<script lang="ts">
 import {onMount} from 'svelte';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import FileTypeIcon from './FileTypeIcon.svelte';import AtlasContextMenu from './AtlasContextMenu.svelte';
 import ChevronRight from '@lucide/svelte/icons/chevron-right';import ChevronDown from '@lucide/svelte/icons/chevron-down';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import FilePlus from '@lucide/svelte/icons/file-plus';import FolderPlus from '@lucide/svelte/icons/folder-plus';import Search from '@lucide/svelte/icons/search';import ArrowUpDown from '@lucide/svelte/icons/arrow-up-down';
 export let state:WorkbenchState;let contextId='local';let route:any;let error='';let loading=false;let menu:any;let expanded=new Set(['/']);let children:Record<string,any[]>={};let visibleRows:any[]=[];let pinned:string[]=[];let generation=0;let query='';let matches:any[]=[];let searchTimer:any;let searchController:AbortController|undefined;let searchGeneration=0;let sort:'name'|'type'|'size'|'modified'='name';let dialog:{action:string;item:any;value:string;title:string;contextId:string;danger?:boolean}|null=null;let lastTrash:any;
 const key=(value:string)=>value==='/'?'/':value.replace(/\/$/,'');const depth=(value:string)=>value==='/'?0:value.split('/').filter(Boolean).length;const parent=(value:string)=>value==='/'?'/':value.slice(0,value.lastIndexOf('/'))||'/';const join=(base:string,name:string)=>base==='/'?`/${name}`:`${base}/${name}`;const bytes=(value:number)=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
 function ordered(list:any[]){return [...list].sort((a,b)=>a.type==='directory'&&b.type!=='directory'?-1:b.type==='directory'&&a.type!=='directory'?1:sort==='size'?(a.bytes??0)-(b.bytes??0):sort==='modified'?String(b.modifiedAt).localeCompare(String(a.modifiedAt)):sort==='type'?String(a.type).localeCompare(String(b.type))||a.name.localeCompare(b.name):a.name.localeCompare(b.name));}
 async function load(path:string,force=false){const normalized=key(path);if(children[normalized]&&!force)return;const token=++generation;loading=true;error='';try{const page=await api<any>(`/api/files?contextId=${encodeURIComponent(contextId)}&path=${encodeURIComponent(normalized)}&limit=500`);if(token!==generation)return;children={...children,[normalized]:page.items??[]};visibleRows=rows('/');route=page.route;}catch(value){if(token===generation)error=(value as Error).message;}finally{if(token===generation)loading=false;}}
 function toggle(item:any){const itemPath=key(item.path);if(item.type!=='directory'){window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:false}}));return;}if(expanded.has(itemPath))expanded.delete(itemPath);else{expanded.add(itemPath);void load(itemPath)}expanded=new Set(expanded);visibleRows=rows('/');}
 function openPinned(path:string){expanded.add(key(path));expanded=new Set(expanded);void load(path);}
 function showMenu(event:MouseEvent,item:any){event.preventDefault();menu={x:event.clientX,y:event.clientY,item};}
 function rows(path:string):any[]{return ordered(children[key(path)]??[]).flatMap(item=>[{...item,level:depth(item.path),open:expanded.has(key(item.path))},...(item.type==='directory'&&expanded.has(key(item.path))?rows(item.path):[])]);}
 function begin(action:string,item:any={path:'/',type:'directory'}){const base=action.startsWith('new-')?item.path:parent(item.path),value=action==='rename'?item.name:'';dialog={action,item,value,contextId,title:action==='new-file'?'Create file':action==='new-directory'?'Create directory':action==='rename'?'Rename':action==='trash'?'Move to trash?':'Delete permanently?',danger:action==='delete'};menu=null;}
 function record(operation:any,path:string){const routeLabel=operation?.route?`${operation.route.kind} · ${operation.route.effectiveIdentity} · ${operation.route.privilege}`:'route unavailable';state.appendActivity(`${operation?.type??'filesystem'} · ${path} · ${routeLabel}`)}
 async function mutate(){if(!dialog)return;const current=dialog;if(current.contextId!==contextId){dialog=null;return;}error='';try{let result:any;if(current.action==='new-file'||current.action==='new-directory'){const target=join(current.item.path,current.value.trim());result=await api('/api/files',{method:'POST',body:JSON.stringify({contextId:current.contextId,path:target,type:current.action==='new-file'?'file':'directory'})})}else if(current.action==='rename'){const destination=join(parent(current.item.path),current.value.trim());result=await api('/api/files',{method:'PATCH',body:JSON.stringify({contextId:current.contextId,path:current.item.path,destination})})}else{result=await api<any>('/api/files',{method:'DELETE',body:JSON.stringify({contextId:current.contextId,path:current.item.path,permanent:current.action==='delete',confirm:current.action==='delete'})});if(!current.action.includes('delete'))lastTrash={...result,contextId:current.contextId}}record(result.operation,current.item.path);dialog=null;if(current.contextId===contextId)await load(current.action.startsWith('new-')?current.item.path:parent(current.item.path),true)}catch(value){if(current.contextId===contextId)error=(value as Error).message}}
 async function restore(){const current=lastTrash;if(!current?.restoreAvailable||!current.restorePath||current.contextId!==contextId)return;error='';try{const result=await api<any>('/api/files/restore',{method:'POST',body:JSON.stringify({contextId:current.contextId,path:current.restorePath})});record(result.operation,current.path);lastTrash=null;children={};visibleRows=[];if(current.contextId===contextId)await load('/',true)}catch(value){if(current.contextId===contextId)error=(value as Error).message}}
 function menuAction(action:string){if(!menu)return;const item=menu.item;if(action==='open'){if(item.type==='directory')openPinned(item.path);else window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:true}}));menu=null;return}if(action==='pin'){if(!pinned.includes(item.path))pinned=[...pinned,item.path];localStorage.setItem('atlas.pinned-roots',JSON.stringify(pinned));menu=null;return}if(action==='copy'){void navigator.clipboard?.writeText(item.path);menu=null;return}begin(action,item)}
 function searchFiles(){clearTimeout(searchTimer);searchController?.abort();const token=++searchGeneration,searchContext=contextId,searchQuery=query;if(!searchQuery.trim()){matches=[];return}searchTimer=setTimeout(async()=>{const controller=new AbortController();searchController=controller;loading=true;try{const value=await api<any>(`/api/files/search?contextId=${encodeURIComponent(searchContext)}&path=%2F&query=${encodeURIComponent(searchQuery)}&mode=all&limit=200`,{signal:controller.signal});if(token!==searchGeneration||searchContext!==contextId)return;matches=value.matches??[];route=value.route??route}catch(value){if(token===searchGeneration&&searchContext===contextId&&(value as {name?:string}).name!=='AbortError')error=(value as Error).message}finally{if(token===searchGeneration&&searchContext===contextId)loading=false}},180)}
 function openMatch(item:any){if(item.type==='directory'){openPinned(item.path);query='';matches=[]}else window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:true,line:item.line}}))}
 onMount(()=>{try{pinned=JSON.parse(localStorage.getItem('atlas.pinned-roots')??'[]')}catch{pinned=[]}const unsub=state.subscribe(value=>{if(value.contextId!==contextId){searchController?.abort();searchGeneration++;contextId=value.contextId;children={};visibleRows=[];matches=[];query='';dialog=null;lastTrash=null;menu=null;expanded=new Set(['/']);void load('/')}});void load('/');return()=>{generation++;searchController?.abort();clearTimeout(searchTimer);unsub()}});
</script>
<aside class="explorer tree-explorer">
 <header><div><strong>FILESYSTEM</strong><span>{contextId}</span></div><div class="header-actions"><button title="Create file" onclick={()=>begin('new-file')}><FilePlus size={14}/></button><button title="Create directory" onclick={()=>begin('new-directory')}><FolderPlus size={14}/></button><button title="Refresh filesystem" onclick={()=>{children={};visibleRows=[];void load('/',true)}}><RefreshCw size={14}/></button></div></header>
 <div class="filesystem-search"><Search size={14}/><input bind:value={query} oninput={searchFiles} placeholder="Search names and contents…" aria-label="Search filesystem"/><label title="Sort filesystem"><ArrowUpDown size={12}/><select bind:value={sort} onchange={()=>visibleRows=rows('/')}><option value="name">Name</option><option value="type">Type</option><option value="size">Size</option><option value="modified">Modified</option></select></label></div>
 {#if route}<div class="route-chip" title={route.operations?.join(', ')}>context {contextId} · {route.kind} · {route.effectiveIdentity} · {route.privilege}{route.operations?.length?` · ${route.operations.join(', ')}`:''}</div>{/if}
 {#if pinned.length&&!query}<div class="tree-pinned"><span>PINNED</span>{#each pinned as path}<button onclick={()=>openPinned(path)} title={`Open ${path}`}><FolderPlus size={12}/>{path}</button>{/each}</div>{/if}
 {#if error}<div class="panel-error">{error}</div>{/if}
 <div class="file-list tree-list" aria-busy={loading}>{#if query}{#each matches as item}<button class="file-row search-file-row" onclick={()=>openMatch(item)}><FileTypeIcon name={item.path} kind={item.type} size={16}/><b>{item.path}</b><small>{item.line?`L${item.line}`:''}</small>{#if item.preview}<em>{item.preview}</em>{/if}</button>{/each}{#if !loading&&!matches.length}<span class="empty-copy">No matching files.</span>{/if}{:else}{#each visibleRows as item}<button class="file-row tree-row" style={`--level:${item.level}`} onclick={()=>toggle(item)} oncontextmenu={(event)=>showMenu(event,item)}><span class="file-chevron">{#if item.type==='directory'}{#if item.open}<ChevronDown size={13}/>{:else}<ChevronRight size={13}/>{/if}{/if}</span><FileTypeIcon name={item.name} kind={item.type} size={16}/><b>{item.name}</b><small title={item.modifiedAt}>{item.type==='file'?bytes(item.bytes):''}</small></button>{/each}{#if !loading&&!children['/']}<span class="empty-copy">No filesystem entries available.</span>{/if}{/if}</div>
 {#if menu}<AtlasContextMenu x={menu.x} y={menu.y} item={menu.item} onclose={()=>menu=null} onrun={menuAction}/>{/if}
 {#if lastTrash}<div class="trash-notice">Moved <code>{lastTrash.path}</code> to trash via {lastTrash.route?.kind??'the selected route'} · {lastTrash.route?.effectiveIdentity??'identity unavailable'}.{#if lastTrash.restoreAvailable}<button onclick={restore}>Restore</button>{:else}<span>Restore unavailable on this route.</span>{/if}</div>{/if}
 {#if dialog}<div class="atlas-dialog-backdrop"><form class="atlas-dialog" onsubmit={(event)=>{event.preventDefault();void mutate()}}><h2>{dialog.title}</h2>{#if dialog.action==='trash'||dialog.action==='delete'}<p>{dialog.item.path}</p>{#if dialog.danger}<p>This permanently removes the selected path and cannot be undone.</p>{/if}{:else}<label>Name<input bind:value={dialog.value} required/></label>{/if}<div><button type="button" onclick={()=>dialog=null}>Cancel</button><button class:danger={dialog.danger}>{dialog.action==='trash'?'Move to trash':dialog.action==='delete'?'Delete':dialog.title}</button></div></form></div>{/if}
</aside>
