<script lang="ts">
 import {onMount} from 'svelte';import {api} from '../lib/api.js';import {atlasEvents} from '../lib/atlas-events.js';import type {WorkbenchState} from '../lib/workbench-state.js';import FileTypeIcon from './FileTypeIcon.svelte';import AtlasContextMenu from './AtlasContextMenu.svelte';import DocumentationHelp from './DocumentationHelp.svelte';import LoadingSpinner from './LoadingSpinner.svelte';
 import ChevronRight from '@lucide/svelte/icons/chevron-right';import ChevronDown from '@lucide/svelte/icons/chevron-down';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import FilePlus from '@lucide/svelte/icons/file-plus';import FolderPlus from '@lucide/svelte/icons/folder-plus';import Search from '@lucide/svelte/icons/search';import ArrowUpDown from '@lucide/svelte/icons/arrow-up-down';import AtlasSelect from './ui/AtlasSelect.svelte';
 export let state:WorkbenchState;let contextId='local';let root='/';let route:any;let error='';let pendingPaths=new Set<string>();let loadedPaths=new Set<string>();let searchLoading=false;let menu:any;let picker='';let expanded=new Set(['/']);let children:Record<string,any[]>={};let visibleRows:any[]=[];let pinned:string[]=[];let requestControllers=new Map<string,AbortController>();let requestGenerations=new Map<string,number>();let query='';let matches:any[]=[];let searchTimer:any;let searchController:AbortController|undefined;let searchGeneration=0;let sort:'name'|'type'|'size'|'modified'='name';let dialog:{action:string;item:any;value:string;title:string;contextId:string;danger?:boolean}|null=null;let creating:{type:'file'|'directory';parent:string;value:string;contextId:string}|null=null;let lastTrash:any;
 $: loading=pendingPaths.size>0||searchLoading;
 const key=(value:string)=>value==='/'?'/':value.replace(/\/$/,'');const depth=(value:string)=>value==='/'?0:value.split('/').filter(Boolean).length;const parent=(value:string)=>value==='/'?'/':value.slice(0,value.lastIndexOf('/'))||'/';const join=(base:string,name:string)=>base==='/'?`/${name}`:`${base}/${name}`;const bytes=(value:number)=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
 function ordered(list:any[]){return [...list].sort((a,b)=>a.type==='directory'&&b.type!=='directory'?-1:b.type==='directory'&&a.type!=='directory'?1:sort==='size'?(a.bytes??0)-(b.bytes??0):sort==='modified'?String(b.modifiedAt).localeCompare(String(a.modifiedAt)):sort==='type'?String(a.type).localeCompare(String(b.type))||a.name.localeCompare(b.name):a.name.localeCompare(b.name));}
 function abortFileRequests(){for(const controller of requestControllers.values())controller.abort();requestControllers=new Map();requestGenerations=new Map();}
 function isCancelled(value:unknown){const error=value as {code?:string;name?:string};return error.code==='cancelled'||error.name==='AbortError';}
 async function load(path:string,force=false){const normalized=key(path);if(children[normalized]&&!force)return;requestControllers.get(normalized)?.abort();const controller=new AbortController();requestControllers.set(normalized,controller);const token=(requestGenerations.get(normalized)??0)+1,eventId=`filesystem.list:${contextId}:${normalized}:${token}`;atlasEvents.begin({id:eventId,type:'filesystem.list',title:`Loading ${normalized}`,contextId,panelId:'atlas.filesystem'});requestGenerations.set(normalized,token);pendingPaths.add(normalized);pendingPaths=new Set(pendingPaths);error='';try{const page=await api<any>(`/api/files?contextId=${encodeURIComponent(contextId)}&path=${encodeURIComponent(normalized)}&limit=500`,{signal:controller.signal});if(requestGenerations.get(normalized)!==token||requestControllers.get(normalized)!==controller||controller.signal.aborted){atlasEvents.removeLocal(eventId);return}children={...children,[normalized]:page.items??[]};loadedPaths.add(normalized);loadedPaths=new Set(loadedPaths);visibleRows=rows(root);route=page.route;atlasEvents.resolve(eventId,{message:`Loaded ${(page.items??[]).length} entries`});}catch(value){if(isCancelled(value))atlasEvents.removeLocal(eventId);else if(requestGenerations.get(normalized)===token&&requestControllers.get(normalized)===controller){error=(value as Error).message;atlasEvents.fail(eventId,{message:error});}}finally{if(requestGenerations.get(normalized)===token&&requestControllers.get(normalized)===controller){requestControllers.delete(normalized);pendingPaths.delete(normalized);pendingPaths=new Set(pendingPaths);}}}
 function toggle(item:any){const itemPath=key(item.path);if(item.type!=='directory'){window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:false}}));return}if(picker){pickDirectory(item.path);return}if(expanded.has(itemPath))expanded.delete(itemPath);else{expanded.add(itemPath);void load(itemPath)}expanded=new Set(expanded);visibleRows=rows(root);}
 function openPinned(path:string){expanded.add(key(path));expanded=new Set(expanded);void load(path);}
 function showMenu(event:MouseEvent,item:any){event.preventDefault();menu={x:event.clientX,y:event.clientY,item};}
 function showBackgroundMenu(event:MouseEvent){if((event.target as HTMLElement).closest('.file-row'))return;event.preventDefault();menu={x:event.clientX,y:event.clientY,item:{path:root,type:'background'}};}
 function rows(path:string):any[]{return ordered(children[key(path)]??[]).flatMap(item=>[{...item,level:depth(item.path),open:expanded.has(key(item.path))},...(item.type==='directory'&&expanded.has(key(item.path))?rows(item.path):[])]);}
 function begin(action:string,item:any={path:root,type:'directory'}){menu=null;if(action==='new-file'||action==='new-directory'){creating={type:action==='new-file'?'file':'directory',parent:item.path,value:'',contextId};expanded.add(item.path);expanded=new Set(expanded);if(item.path!==root)void load(item.path);queueMicrotask(()=>document.querySelector<HTMLInputElement>('.inline-create-row input')?.focus());return}const value=action==='rename'?item.name:'';dialog={action,item,value,contextId,title:action==='rename'?'Rename':action==='trash'?'Move to trash?':'Delete permanently?',danger:action==='delete'};}
 async function completeCreation(){if(!creating||creating.contextId!==contextId)return;const current=creating,name=current.value.trim();if(!name||name==='.'||name==='..'||name.includes('/')||name.includes('\0')){error='Enter a valid name without slashes.';return}const path=join(current.parent,name);creating=null;if(current.type==='file'){window.dispatchEvent(new CustomEvent('atlas:new-buffer',{detail:{contextId:current.contextId,suggestedDirectory:current.parent,proposedPath:path}}));return}try{const result=await api<any>('/api/files',{method:'POST',body:JSON.stringify({contextId:current.contextId,path,type:'directory'})});record(result.operation,path);await load(current.parent,true)}catch(value){error=(value as Error).message}}
 function record(operation:any,path:string){const routeLabel=operation?.route?`${operation.route.kind} · ${operation.route.effectiveIdentity} · ${operation.route.privilege}`:'route unavailable';state.appendActivity(`${operation?.type??'filesystem'} · ${path} · ${routeLabel}`)}
 async function mutate(){if(!dialog)return;const current=dialog;if(current.contextId!==contextId){dialog=null;return}error='';try{let result:any;if(current.action==='rename'){const destination=join(parent(current.item.path),current.value.trim());result=await api('/api/files',{method:'PATCH',body:JSON.stringify({contextId:current.contextId,path:current.item.path,destination})})}else{result=await api<any>('/api/files',{method:'DELETE',body:JSON.stringify({contextId:current.contextId,path:current.item.path,permanent:current.action==='delete',confirm:current.action==='delete'})});if(!current.action.includes('delete'))lastTrash={...result,contextId:current.contextId}}record(result.operation,current.item.path);dialog=null;if(current.contextId===contextId)await load(parent(current.item.path),true)}catch(value){if(current.contextId===contextId)error=(value as Error).message}}
 async function restore(){const current=lastTrash;if(!current?.restoreAvailable||!current.restorePath||current.contextId!==contextId)return;error='';try{const result=await api<any>('/api/files/restore',{method:'POST',body:JSON.stringify({contextId:current.contextId,path:current.restorePath})});record(result.operation,current.path);lastTrash=null;children={};visibleRows=[];if(current.contextId===contextId)await load('/',true)}catch(value){if(current.contextId===contextId)error=(value as Error).message}}
 function menuAction(action:string){if(!menu)return;const item=menu.item;if(action==='refresh'){children={};visibleRows=[];menu=null;void load(root,true);return}if(action==='open'){if(item.type==='directory')openPinned(item.path);else window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:true}}));menu=null;return}if(action==='pin'){window.dispatchEvent(new CustomEvent('atlas:pin-root',{detail:{contextId,path:item.type==='file'?parent(item.path):item.path}}));menu=null;return}if(action==='workspace'){window.dispatchEvent(new CustomEvent('atlas:add-workspace-root',{detail:{contextId,path:item.path}}));menu=null;return}if(action==='copy'){void navigator.clipboard?.writeText(item.path);menu=null;return}begin(action,item)}
 function searchFiles(){clearTimeout(searchTimer);searchController?.abort();const token=++searchGeneration,searchContext=contextId,searchRoot=root,searchQuery=query;if(!searchQuery.trim()){matches=[];searchLoading=false;return}searchTimer=setTimeout(async()=>{const controller=new AbortController();searchController=controller;searchLoading=true;try{const value=await api<any>(`/api/files/search?contextId=${encodeURIComponent(searchContext)}&path=${encodeURIComponent(searchRoot)}&query=${encodeURIComponent(searchQuery)}&mode=all&limit=200`,{signal:controller.signal});if(token!==searchGeneration||searchContext!==contextId||searchRoot!==root)return;matches=value.matches??[];route=value.route??route}catch(value){if(token===searchGeneration&&searchContext===contextId&&(value as {name?:string}).name!=='AbortError')error=(value as Error).message}finally{if(token===searchGeneration&&searchContext===contextId)searchLoading=false}},180)}
 function openMatch(item:any){if(item.type==='directory'){openPinned(item.path);query='';matches=[]}else window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:true,line:item.line}}))}
 function beginPicker(event:Event){const detail=(event as CustomEvent<{contextId:string;path?:string;target?:string}>).detail;if(!detail)return;if(detail.contextId!==contextId)state.setContext(detail.contextId);picker=detail.target??'generic';const path=detail.path?.startsWith('/')?detail.path:'/';window.dispatchEvent(new CustomEvent('atlas:open-root',{detail:{contextId:detail.contextId,path}}))}
 function pickDirectory(path:string){window.dispatchEvent(new CustomEvent('atlas:directory-picked',{detail:{contextId,path,target:picker}}));picker=''}
 function setRoot(event:Event){const detail=(event as CustomEvent<{contextId:string;path:string}>).detail;if(!detail||detail.contextId!==contextId)return;abortFileRequests();searchController?.abort();searchGeneration++;searchLoading=false;pendingPaths=new Set();loadedPaths=new Set();root=key(detail.path);children={};visibleRows=[];matches=[];query='';dialog=null;creating=null;menu=null;expanded=new Set([root]);void load(root,true)}
 async function revealSaved(event:Event){const detail=(event as CustomEvent<{contextId:string;path:string}>).detail;if(!detail||detail.contextId!==contextId)return;const folder=parent(detail.path),inside=root==='/'||detail.path===root||detail.path.startsWith(`${root}/`);if(!inside){root=folder;children={};expanded=new Set([root])}else{expanded.add(folder);expanded=new Set(expanded)}await load(folder,true);visibleRows=rows(root)}
 onMount(()=>{try{pinned=JSON.parse(localStorage.getItem('atlas.pinned-roots')??'[]')}catch{pinned=[]}let initialLoad=true;const unsub=state.subscribe(value=>{if(initialLoad||value.contextId!==contextId){initialLoad=false;abortFileRequests();searchController?.abort();searchGeneration++;searchLoading=false;pendingPaths=new Set();loadedPaths=new Set();contextId=value.contextId;root='/';children={};visibleRows=[];matches=[];query='';dialog=null;creating=null;lastTrash=null;menu=null;expanded=new Set([root]);void load(root)}});window.addEventListener('atlas:pick-directory',beginPicker);window.addEventListener('atlas:filesystem-root',setRoot);window.addEventListener('atlas:filesystem-reveal',revealSaved);return()=>{abortFileRequests();searchController?.abort();clearTimeout(searchTimer);window.removeEventListener('atlas:pick-directory',beginPicker);window.removeEventListener('atlas:filesystem-root',setRoot);window.removeEventListener('atlas:filesystem-reveal',revealSaved);unsub()}});
</script>
<DocumentationHelp topicId="files" label="Filesystem documentation"/>
<aside class="explorer tree-explorer">
 <header><div><strong>FILESYSTEM</strong><span>{contextId} · {root}</span></div><div class="header-actions"><button title="Create file" onclick={()=>begin('new-file')}><FilePlus size={14}/></button><button title="Create directory" onclick={()=>begin('new-directory')}><FolderPlus size={14}/></button><button title="Refresh filesystem" onclick={()=>{children={};visibleRows=[];void load(root,true)}}><RefreshCw size={14}/></button></div></header>
 <div class="filesystem-search"><Search size={14}/><input bind:value={query} oninput={searchFiles} placeholder="Search names and contents…" aria-label="Search filesystem"/><label title="Sort filesystem"><ArrowUpDown size={12}/><AtlasSelect bind:value={sort} ariaLabel="Sort filesystem" onchange={()=>visibleRows=rows('/')} options={[{value:'name',label:'Name'},{value:'type',label:'Type'},{value:'size',label:'Size'},{value:'modified',label:'Modified'}]}/></label></div>
 {#if route}<div class="route-chip" title={route.operations?.join(', ')}>context {contextId} · {route.kind} · {route.effectiveIdentity} · {route.privilege}{route.operations?.length?` · ${route.operations.join(', ')}`:''}</div>{/if}
 {#if picker}<div class="directory-picker"><span>Choose the repository folder. Select a folder, or use the current root.</span><button onclick={()=>pickDirectory(root)}>Use {root}</button><button title="Cancel folder selection" onclick={()=>picker=''}>×</button></div>{/if}
 {#if pinned.length&&!query}<div class="tree-pinned"><span>PINNED</span>{#each pinned as path}<button onclick={()=>openPinned(path)} title={`Open ${path}`}><FolderPlus size={12}/>{path}</button>{/each}</div>{/if}
 {#if error}<div class="panel-error">{error}</div>{/if}
 <!-- svelte-ignore a11y_interactive_supports_focus -->
 <div class="file-list tree-list" role="tree" aria-busy={loading} oncontextmenu={showBackgroundMenu}>
  {#if query}{#each matches as item}<button class="file-row search-file-row" onclick={()=>openMatch(item)}><FileTypeIcon name={item.path} kind={item.type} size={16}/><b>{item.path}</b><small>{item.line?`L${item.line}`:''}</small>{#if item.preview}<em>{item.preview}</em>{/if}</button>{/each}{#if !loading&&!matches.length}<span class="empty-copy">No matching files.</span>{/if}
  {:else}{#if creating}<form class="file-row inline-create-row" style={`--level:${Math.max(1,depth(creating.parent)-depth(root)+1)}`} onsubmit={(event)=>{event.preventDefault();void completeCreation()}}><span class="file-chevron"></span><FileTypeIcon name={creating.value||'untitled'} kind={creating.type} size={16}/><input bind:value={creating.value} aria-label={creating.type==='file'?'New file name':'New folder name'} placeholder={creating.type==='file'?'filename.ext':'folder'} onkeydown={(event)=>{if(event.key==='Escape'){event.preventDefault();creating=null}}}/></form>{/if}{#each visibleRows as item}<button class="file-row tree-row" style={`--level:${Math.max(1,item.level-depth(root)+1)}`} onclick={()=>toggle(item)} oncontextmenu={(event)=>showMenu(event,item)}><span class="file-chevron">{#if item.type==='directory'}{#if item.open}<ChevronDown size={13}/>{:else}<ChevronRight size={13}/>{/if}{/if}</span><FileTypeIcon name={item.name} kind={item.type} size={16}/><b>{item.name}</b><small title={item.modifiedAt}>{item.type==='file'?bytes(item.bytes):''}</small>{#if item.type==='directory'&&pendingPaths.has(key(item.path))}<LoadingSpinner size="small" label={`Loading ${item.name}`}/>{/if}</button>{/each}{#if loadedPaths.has(root)&&!visibleRows.length}<span class="empty-copy">No filesystem entries available.</span>{/if}{/if}
 </div>
 {#if menu}<AtlasContextMenu x={menu.x} y={menu.y} item={menu.item} onclose={()=>menu=null} onrun={menuAction}/>{/if}
 {#if lastTrash}<div class="trash-notice">Moved <code>{lastTrash.path}</code> to trash via {lastTrash.route?.kind??'the selected route'} · {lastTrash.route?.effectiveIdentity??'identity unavailable'}.{#if lastTrash.restoreAvailable}<button onclick={restore}>Restore</button>{:else}<span>Restore unavailable on this route.</span>{/if}</div>{/if}
 {#if dialog}<div class="atlas-dialog-backdrop"><form class="atlas-dialog" onsubmit={(event)=>{event.preventDefault();void mutate()}}><h2>{dialog.title}</h2>{#if dialog.action==='trash'||dialog.action==='delete'}<p>{dialog.item.path}</p>{#if dialog.danger}<p>This permanently removes the selected path and cannot be undone.</p>{/if}{:else}<label>Name<input bind:value={dialog.value} required/></label>{/if}<div><button type="button" onclick={()=>dialog=null}>Cancel</button><button class:danger={dialog.danger}>{dialog.action==='trash'?'Move to trash':dialog.action==='delete'?'Delete':dialog.title}</button></div></form></div>{/if}
</aside>
