<script lang="ts">
  import { onMount } from 'svelte';
  import { EditorState } from '@codemirror/state';
  import { EditorView, keymap } from '@codemirror/view';
  import { defaultKeymap } from '@codemirror/commands';
  import { javascript } from '@codemirror/lang-javascript';
  import { css } from '@codemirror/lang-css';
  import { json } from '@codemirror/lang-json';
  import { html } from '@codemirror/lang-html';
  import { markdown } from '@codemirror/lang-markdown';
  import { api } from '../lib/api.js';
  export let params: { contextId?:string; path?:string; line?:number; panelId?:string } = {};
  let host:HTMLDivElement; let view:EditorView|undefined; let fingerprint=''; let status='Opening…'; let dirty=false;let announcedDirty=false;let saving=false;let disposed=false;
  const base64=(value:string)=>{const bytes=new TextEncoder().encode(value);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
  async function save(){if(!view||!params.path||saving)return;const submitted=view.state.doc.toString();saving=true;status='Saving…';try{const result=await api<any>('/api/files/content',{method:'PUT',body:JSON.stringify({contextId:params.contextId??'local',path:params.path,contentBase64:base64(submitted),expectedFingerprint:fingerprint})});if(disposed)return;fingerprint=result.fingerprint;const unchanged=view.state.doc.toString()===submitted;dirty=!unchanged;announcedDirty=dirty;status=unchanged?`Saved via ${result.route.kind}`:'Modified after save';window.dispatchEvent(new CustomEvent('atlas:file-dirty',{detail:{panelId:params.panelId,path:params.path,dirty}}));}catch(error:any){if(!disposed)status=error.status===409?'Conflict: file changed on host':error.message;}finally{saving=false;}}
  onMount(()=>{let alive=true;disposed=false;const reveal=(event:Event)=>{const detail=(event as CustomEvent<{panelId?:string;line?:number}>).detail;if(detail.panelId!==params.panelId||!view||!detail.line)return;const line=view.state.doc.line(Math.min(detail.line,view.state.doc.lines));view.dispatch({selection:{anchor:line.from},effects:EditorView.scrollIntoView(line.from,{y:'center'})});};window.addEventListener('atlas:file-reveal',reveal);void (async()=>{try{const opened=await api<any>(`/api/files/content?contextId=${encodeURIComponent(params.contextId??'local')}&path=${encodeURIComponent(params.path??'')}`);if(!alive)return;if(opened.binary){status=`Binary file · ${opened.bytes} bytes · read-only`;return;}if(opened.tooLarge){status=`File exceeds the ${opened.bytes} byte editor limit · read-only`;return;}if(typeof opened.text!=='string'||!opened.fingerprint){status='File cannot be edited.';return;}fingerprint=opened.fingerprint;status=`${opened.bytes} bytes · ${opened.route.kind} · ${opened.route.effectiveIdentity}`;const doc=opened.text,line=Math.min(Math.max(1,params.line??1),doc.split(/\r?\n/).length),anchor=doc.split(/\r?\n/).slice(0,line-1).reduce((total:number,current:string)=>total+current.length+1,0);view=new EditorView({parent:host,state:EditorState.create({doc,selection:{anchor},extensions:[javascript({typescript:/\.[cm]?tsx?$/.test(params.path??'')}),keymap.of([...defaultKeymap,{key:'Mod-s',run:()=>{void save();return true;}}]),EditorView.updateListener.of(update=>{if(update.docChanged){dirty=true;status='Modified';if(!announcedDirty){announcedDirty=true;window.dispatchEvent(new CustomEvent('atlas:file-dirty',{detail:{panelId:params.panelId,path:params.path,dirty:true}}));}}}),EditorView.theme({'&':{height:'100%'},'.cm-scroller':{overflow:'auto'}})]})});if(params.line)view.dispatch({effects:EditorView.scrollIntoView(anchor,{y:'center'})});}catch(error){if(alive)status=(error as Error).message;}})();return()=>{alive=false;disposed=true;window.removeEventListener('atlas:file-reveal',reveal);view?.destroy();};});
</script>
<section class="panel file-panel"><header><div><strong>{dirty?'● ':''}{params.path??'File'}</strong><span>{status}</span></div><button onclick={save} disabled={!dirty||saving}>{saving?'Saving…':'Save'}</button></header><div class="editor" bind:this={host}></div></section>
