<script lang="ts">
 import {onMount} from 'svelte';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import FileTypeIcon from './FileTypeIcon.svelte';import AtlasContextMenu from './AtlasContextMenu.svelte';import ChevronRight from '@lucide/svelte/icons/chevron-right';import ChevronDown from '@lucide/svelte/icons/chevron-down';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import FolderPlus from '@lucide/svelte/icons/folder-plus';
 export let state:WorkbenchState;let contextId='local';let route:any;let error='';let loading=false;let menu:any;let expanded=new Set(['/']);let children=new Map<string,any[]>();let pinned:string[]=[];let generation=0;
 const key=(path:string)=>path==='/'?'/':path.replace(/\/$/,'');const depth=(path:string)=>path==='/'?0:path.split('/').filter(Boolean).length;
 async function load(path:string,force=false){const normalized=key(path);if(children.has(normalized)&&!force)return;const token=++generation;loading=true;error='';try{const page=await api<any>(`/api/files?contextId=${encodeURIComponent(contextId)}&path=${encodeURIComponent(normalized)}&limit=250`);if(token!==generation)return;children.set(normalized,page.items??[]);route=page.route;children=new Map(children);}catch(value){if(token===generation)error=(value as Error).message;}finally{if(token===generation)loading=false;}}
 function toggle(item:any){const path=key(item.path);if(item.type!=='directory'){window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:false}}));return;}if(expanded.has(path))expanded.delete(path);else{expanded.add(path);void load(path)}expanded=new Set(expanded);}
 function openPinned(path:string){expanded.add(key(path));expanded=new Set(expanded);void load(path);}
 function showMenu(event:MouseEvent,item:any){event.preventDefault();menu={x:event.clientX,y:event.clientY,item};}
 function menuAction(action:string){if(!menu)return;const item=menu.item;if(action==='open'){if(item.type==='directory')openPinned(item.path);else window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:item.path,pinned:true}}));}if(action==='pin'){if(!pinned.includes(item.path))pinned=[...pinned,item.path];localStorage.setItem('atlas.pinned-roots',JSON.stringify(pinned));}if(action==='copy')void navigator.clipboard?.writeText(item.path);menu=null;}
 function rows(path:string):any[]{const list=children.get(key(path))??[];return list.flatMap(item=>[{...item,level:depth(item.path),open:expanded.has(key(item.path))},...(item.type==='directory'&&expanded.has(key(item.path))?rows(item.path):[])]);}
 onMount(()=>{try{pinned=JSON.parse(localStorage.getItem('atlas.pinned-roots')??'[]')}catch{pinned=[]}const unsub=state.subscribe(value=>{if(value.contextId!==contextId){contextId=value.contextId;children=new Map();expanded=new Set(['/']);void load('/')}});void load('/');return()=>{generation++;unsub()};});
</script>
<aside class="explorer tree-explorer"><header><div><strong>FILESYSTEM</strong><span>{contextId}</span></div><div class="header-actions"><button title="Refresh filesystem" aria-label="Refresh filesystem" onclick={()=>{children=new Map();void load('/',true)}}><RefreshCw size={14}/></button></div></header>{#if route}<div class="route-chip">{route.kind} · {route.effectiveIdentity} · {route.privilege}</div>{/if}{#if pinned.length}<div class="tree-pinned"><span>PINNED</span>{#each pinned as path}<button onclick={()=>openPinned(path)} title={`Open ${path}`}><FolderPlus size={12}/>{path}</button>{/each}</div>{/if}{#if error}<div class="panel-error">{error}</div>{/if}<div class="file-list tree-list" aria-busy={loading}>{#each rows('/') as item}<button class="file-row tree-row" style={`--level:${item.level}`} onclick={()=>toggle(item)} oncontextmenu={(event)=>showMenu(event,item)}><span class="file-chevron">{#if item.type==='directory'}{#if item.open}<ChevronDown size={13}/>{:else}<ChevronRight size={13}/>{/if}{/if}</span><FileTypeIcon name={item.name} kind={item.type} size={16}/><b>{item.name}</b><small>{item.type==='file'?`${item.bytes} B`:''}</small></button>{/each}{#if !loading&&!children.has('/')}<span class="empty-copy">No filesystem entries available.</span>{/if}</div>{#if menu}<AtlasContextMenu x={menu.x} y={menu.y} item={menu.item} onclose={()=>menu=null} onrun={menuAction}/>{/if}</aside>
