<script lang="ts">
  import {onMount} from 'svelte';import {api} from '../lib/api.js';import {atlasEvents} from '../lib/atlas-events.js';import {loadContextCatalog} from '../lib/context-catalog.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  import PackageCheck from '@lucide/svelte/icons/package-check';import Download from '@lucide/svelte/icons/download';import ExternalLink from '@lucide/svelte/icons/external-link';import Square from '@lucide/svelte/icons/square';
  export let params:Record<string,unknown>;export let state:WorkbenchState;
  let targetContextId=String(params.targetContextId??state.snapshot().contextId),profile='local',systemScope=false,session:any,status='',busy=false,confirmInstall=false,devices:any[]=[];
  $: if(params.targetContextId)targetContextId=String(params.targetContextId);
  async function prepare(){const eventId=`fngk.handoff.prepare:${crypto.randomUUID()}`;atlasEvents.begin({id:eventId,type:'fngk.handoff.prepare',title:'Prepare exact-head FNGK handoff',panelId:'atlas.fngk-handoff'});busy=true;status='Validating and publishing exact-head artifacts…';try{session=await api<any>('/api/fngk-head/handoff/prepare',{method:'POST',body:'{}'});status='Artifact route ready';atlasEvents.resolve(eventId,{message:status})}catch(error){status=(error as Error).message;atlasEvents.fail(eventId,{message:status})}finally{busy=false}}
  async function install(){const eventId=`fngk.handoff.install:${crypto.randomUUID()}`;atlasEvents.begin({id:eventId,type:'fngk.handoff.install',title:'Install exact-head FNGK',contextId:targetContextId,panelId:'atlas.fngk-handoff'});confirmInstall=false;busy=true;status='Installing and converging the remote daemon…';try{session=await api<any>('/api/fngk-head/handoff/install',{method:'POST',body:JSON.stringify({handoffId:session.id,targetContextId,profile,systemScope,confirm:true})});status='Remote exact-head FNGK verified';atlasEvents.resolve(eventId,{message:status})}catch(error){const detail=(error as any).body;if(detail?.handoff)session=detail.handoff;if(detail?.diagnosticSessionId)window.dispatchEvent(new CustomEvent('atlas:open-logs',{detail:{diagnosticId:detail.diagnosticSessionId}}));status=(error as Error).message;atlasEvents.fail(eventId,{message:status,diagnosticId:detail?.diagnosticSessionId})}finally{busy=false}}
  async function stop(){if(!session)return;const eventId=`fngk.handoff.stop:${crypto.randomUUID()}`;atlasEvents.begin({id:eventId,type:'fngk.handoff.stop',title:'Stop FNGK handoff route',panelId:'atlas.fngk-handoff'});try{await api(`/api/fngk-head/handoff/${encodeURIComponent(session.id)}`,{method:'DELETE',body:JSON.stringify({confirm:true})});session={...session,status:'stopped'};status='Artifact route stopped';atlasEvents.resolve(eventId,{message:status})}catch(error){status=(error as Error).message;atlasEvents.fail(eventId,{message:status})}}
  onMount(()=>{void loadContextCatalog(false,state.snapshot().connection.profile).then(value=>devices=(value.contexts??[]).filter((item:any)=>item.kind==='fngk-device'&&item.online))});
</script>
<section class="panel handoff-panel"><header><div><strong>Exact-head FNGK handoff</strong><span>{targetContextId}</span></div></header><div class="handoff-body"><PackageCheck size={32}/><h2>Install this Signal checkout on a remote Device</h2><p>Atlas verifies the local archive and checksum, publishes only those artifacts through Signal/HKMN, installs with backup and rollback, converges the daemon, and verifies the source commit.</p><label>Target Device<select bind:value={targetContextId}>{#if !devices.some(item=>item.id===targetContextId)}<option value={targetContextId}>{targetContextId}</option>{/if}{#each devices as item}<option value={item.id}>{item.name} · {item.id.slice(-8)}</option>{/each}</select></label><label>Profile<input bind:value={profile}/></label><label class="check"><input type="checkbox" bind:checked={systemScope}/>Install system-wide with sudo</label>{#if !session}<button disabled={busy} onclick={prepare}><ExternalLink size={14}/>Prepare private artifact route</button>{:else}<dl><div><dt>Status</dt><dd>{session.status}</dd></div><div><dt>Commit</dt><dd>{session.artifact?.commit}</dd></div><div><dt>Checksum</dt><dd>{session.artifact?.checksum?.slice(0,16)}…</dd></div>{#if session.route}<div><dt>Temporary route</dt><dd>{session.route.hostname}</dd></div>{/if}</dl><div class="handoff-actions"><button disabled={busy||session.status!=='ready'} onclick={()=>confirmInstall=true}><Download size={14}/>Install and verify</button><button disabled={session.status==='stopped'} onclick={stop}><Square size={12}/>Stop route</button></div>{/if}</div><footer>{busy?'Working…':status||'No artifact is exposed until you prepare a handoff.'}</footer></section>
{#if confirmInstall}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>Install exact-head FNGK?</h2><p>This changes the FNGK installation on {targetContextId}. The existing binary is backed up and a rollback command is retained.</p><div><button onclick={()=>confirmInstall=false}>Cancel</button><button onclick={install}>Install</button></div></div></div>{/if}
