<script lang="ts">
  import {onMount} from 'svelte';
  import cytoscape from 'cytoscape';
  import {api} from '../lib/api.js';
  import type {WorkbenchState} from '../lib/workbench-state.js';
  import ArrowLeft from '@lucide/svelte/icons/arrow-left';import ArrowRight from '@lucide/svelte/icons/arrow-right';import Focus from '@lucide/svelte/icons/focus';import Maximize2 from '@lucide/svelte/icons/maximize-2';import RotateCcw from '@lucide/svelte/icons/rotate-ccw';import ZoomIn from '@lucide/svelte/icons/zoom-in';import Sparkles from '@lucide/svelte/icons/sparkles';

  export let state:WorkbenchState;
  let host:HTMLDivElement,cy:cytoscape.Core|undefined,error='',count='',contextId=state.snapshot().contextId,rootId='',lens='overview',level=0,generation=0,projection:any,selected='Device overview',cursor=-1,showRelationships=false;
  let history:Array<{rootId:string;lens:string;level:number}>=[];
  const lenses=[['overview','Overview'],['runtime','Runtime'],['code','Code'],['data','Data'],['network','Network'],['security','Security'],['activity','Activity']];
  const colors:Record<string,string>={device:'#d3fa72',environment:'#8fb3d9',workload:'#62d9cc',capability:'#bda4ff',service:'#ff9e78',process:'#ff7d78',container:'#f3ad5d',runtime:'#8fb3d9',interface:'#48b9ff',port:'#f3ad5d',socket:'#48b9ff','http-endpoint':'#48b9ff','external-system':'#8996a5',repository:'#d3fa72',package:'#bda4ff',module:'#62d9cc',class:'#78a7ff',function:'#78a7ff',test:'#88d498','data-store':'#f3ad5d',database:'#f3ad5d',table:'#f6d365',identity:'#e68bd4',event:'#e68bd4',operation:'#8996a5'};
  const title=(kind:string)=>kind.replaceAll('-',' ').replace(/\b\w/g,value=>value.toUpperCase());
  function remember(next:{rootId:string;lens:string;level:number}){history.splice(cursor+1);history.push(next);cursor=history.length-1}
  function syncUrl(replace=false){const params=new URLSearchParams(location.search);params.set('contextId',contextId);params.set('atlasLens',lens);params.set('atlasLevel',String(level));if(rootId)params.set('atlasRoot',rootId);else params.delete('atlasRoot');window.history[replace?'replaceState':'pushState']({},'',`${location.pathname}?${params}`)}
  function navigate(next:{rootId?:string;lens?:string;level?:number},record=true){rootId=next.rootId??rootId;lens=next.lens??lens;level=next.level??level;if(record){remember({rootId,lens,level});syncUrl()}void load()}
  function back(){if(cursor<=0)return;cursor--;({rootId,lens,level}=history[cursor]);void load()}
  function forward(){if(cursor+1>=history.length)return;cursor++;({rootId,lens,level}=history[cursor]);void load()}
  function home(){showRelationships=false;navigate({rootId:'',level:0})}
  function relationships(){showRelationships=true;void load()}
  async function load(){const token=++generation;error='';try{const query=new URLSearchParams({contextId,lens,level:String(level),budget:'160'}),url=rootId?`/api/world/entities/${encodeURIComponent(rootId)}/neighborhood`:'/api/world/projection';const value=await api<any>(`${url}?${query}`);if(token!==generation)return;projection=value;count=`${value.nodes.length} visible · ${value.edges.length} relationships${value.aggregates?.length?` · ${value.aggregates.reduce((sum:number,item:any)=>sum+item.count,0)} folded`:''}`;render(value)}catch(value){error=(value as Error).message;count='Atlas unavailable'}}
  function render(value:any){cy?.destroy();if(!rootId&&!showRelationships){host.innerHTML='';return}cy=cytoscape({container:host,elements:[...value.nodes.map((node:any)=>({data:{...node,type:node.kind,label:node.label}})),...value.edges.map((edge:any)=>({data:edge}))],style:[
   {selector:'node',style:{'background-color':(node:any)=>colors[node.data('kind')]??'#6d7684','border-color':(node:any)=>node.data('stale')?'#ef4444':node.data('classification')==='inferred'?'#f3ad5d':node.data('kind')==='device'?'#d3fa72':'#111923','border-style':(node:any)=>node.data('classification')==='inferred'?'dashed':'solid','border-width':(node:any)=>node.data('kind')==='device'?4:2,'label':'data(label)','font-size':(node:any)=>['device','workload'].includes(node.data('kind'))?13:10,'font-weight':(node:any)=>['device','workload'].includes(node.data('kind'))?600:400,'color':'#dce5ef','text-valign':'bottom','text-margin-y':9,'width':(node:any)=>node.data('kind')==='device'?58:node.data('kind')==='workload'?42:26,'height':(node:any)=>node.data('kind')==='device'?58:node.data('kind')==='workload'?42:26,'text-outline-color':'#0a0f14','text-outline-width':3,'text-wrap':'ellipsis','text-max-width':140,'opacity':(node:any)=>node.data('stale')?.55:Math.max(.58,Number(node.data('confidence')??1))} as any},
   {selector:'edge',style:{'line-color':(edge:any)=>edge.data('stale')?'#713f3f':edge.data('type')==='provides-capability'?'#bda4ff':edge.data('type')==='contains'?'#344252':'#596675','target-arrow-color':(edge:any)=>edge.data('type')==='provides-capability'?'#bda4ff':'#596675','target-arrow-shape':'triangle','curve-style':'bezier','width':(edge:any)=>Math.max(1,Number(edge.data('confidence')??.5)*2),'line-style':(edge:any)=>edge.data('classification')==='inferred'?'dashed':'solid','opacity':.82} as any},
   {selector:':selected',style:{'border-width':4,'border-color':'#fff'}}],layout:(lens==='overview'&&!rootId?{name:'concentric',padding:50,minNodeSpacing:55,levelWidth:()=>2}:{name:'breadthfirst',directed:true,padding:48,spacingFactor:1.5,animate:false}) as any});
   cy.on('tap','node',event=>{const data=event.target.data();selected=data.label;state.select({id:data.id,type:data.kind,contextId,path:data.attributes?.path??data.attributes?.legacyPath,label:data.label,semantic:true})});
   cy.on('dbltap','node',event=>navigate({rootId:event.target.id(),level:Math.min(4,level+1)}));
  }
  onMount(()=>{const params=new URLSearchParams(location.search);contextId=params.get('contextId')??contextId;rootId=params.get('atlasRoot')??'';lens=params.get('atlasLens')??lens;level=Math.max(0,Math.min(4,Number(params.get('atlasLevel'))||0));remember({rootId,lens,level});syncUrl(true);void load();const refresh=()=>void load(),pop=()=>{const next=new URLSearchParams(location.search);rootId=next.get('atlasRoot')??'';lens=next.get('atlasLens')??'overview';level=Math.max(0,Math.min(4,Number(next.get('atlasLevel'))||0));history=[];cursor=-1;remember({rootId,lens,level});void load()},unsubscribe=state.subscribe(value=>{if(value.contextId!==contextId){contextId=value.contextId;rootId='';level=0;history=[];cursor=-1;remember({rootId,lens,level});syncUrl(true);void load()}});window.addEventListener('atlas:graph-refresh',refresh);window.addEventListener('popstate',pop);return()=>{generation++;unsubscribe();window.removeEventListener('atlas:graph-refresh',refresh);window.removeEventListener('popstate',pop);cy?.destroy()}});
</script>

<section class="panel graph-panel semantic-atlas">
 <header><div><strong>Device atlas</strong><span>{selected} · {count}</span></div><div class="graph-actions"><button title="Back" aria-label="Back in atlas" onclick={back} disabled={cursor<=0}><ArrowLeft size={14}/></button><button title="Forward" aria-label="Forward in atlas" onclick={forward} disabled={cursor+1>=history.length}><ArrowRight size={14}/></button><button title="Device overview" aria-label="Show Device overview" onclick={home}><RotateCcw size={14}/></button><button title="Focus selected" aria-label="Focus selected entity" onclick={()=>{const id=state.snapshot().selection?.id;if(id)navigate({rootId:id,level:Math.min(4,level+1)})}}><Focus size={14}/></button><button title="Ask Calculator" aria-label="Open Atlas intelligence" onclick={()=>window.dispatchEvent(new Event('atlas:open-intelligence'))}><Sparkles size={14}/></button><button title="Fit map" aria-label="Fit map" onclick={()=>cy?.fit(undefined,40)}><Maximize2 size={14}/></button></div></header>
 <nav class="atlas-breadcrumbs" aria-label="Atlas breadcrumb">{#each projection?.breadcrumbs??[] as item,index}<button onclick={()=>navigate({rootId:item.id,level:Math.max(0,index)})}>{item.label}</button>{#if index<(projection?.breadcrumbs?.length??0)-1}<span>›</span>{/if}{:else}<span>{contextId}</span>{/each}</nav>
 <div class="atlas-controls"><div class="lens-picker" aria-label="Atlas lenses">{#each lenses as item}<button class:active={lens===item[0]} onclick={()=>navigate({lens:item[0],rootId:'',level:0})}>{item[1]}</button>{/each}</div><div class="zoom-level" aria-label="Semantic zoom level"><span>Detail</span>{#each [0,1,2,3,4] as value}<button class:active={level===value} title={`Semantic level ${value}`} onclick={()=>navigate({level:value})}>{value}</button>{/each}{#if level<4}<button class="deeper" onclick={()=>navigate({level:level+1})}><ZoomIn size={13}/> Deeper</button>{/if}</div></div>
 {#if error}<div class="panel-error">{error}</div>{/if}{#if !rootId&&!showRelationships}<section class="semantic-home" aria-label="Semantic Device overview"><div class="home-summary"><strong>{projection?.synthesis?.title??'Device overview'}</strong><p>{projection?.synthesis?.summary??'Resolving workloads from Device evidence…'}</p>{#if projection?.synthesis?.attention?.length}<small>{projection.synthesis.attention.join(' · ')}</small>{/if}</div><div class="workload-cards">{#each projection?.cards??[] as card}<button class="workload-card" onclick={()=>navigate({rootId:card.id,level:0})}><span class="card-kind">WORKLOAD</span><strong>{card.title}</strong><p>{card.purpose}</p><dl>{#each card.facts as fact}<div><dt>{fact.label}</dt><dd>{fact.value}</dd></div>{/each}</dl><em class:stale={card.status==='stale'}>{card.status} · inspect evidence ›</em></button>{:else}<p class="empty-home">No logical workloads have been resolved yet. Refresh the selected Device to collect evidence.</p>{/each}</div></section>{/if}<div class="graph" class:hidden={!rootId&&!showRelationships} bind:this={host}></div>
 <footer><div class="semantic-legend">{#each Object.entries(colors).filter(([kind])=>(projection?.nodes??[]).some((node:any)=>node.kind===kind)) as [kind,color]}<span><i style={`--node-color:${color}`}></i>{title(kind)}</span>{/each}</div><button class="relationships-toggle" onclick={relationships} title="Show contextual relationships">{showRelationships?'Device overview':'Relationships'}</button>{#if projection?.aggregates?.length}<div class="folded">{#each projection.aggregates as item}<span>{item.count} {title(item.kind)}</span>{/each}</div>{/if}</footer>
</section>

<style>
 .graph.hidden{display:none}.semantic-home{min-height:0;flex:1;overflow:auto;padding:16px}.home-summary{border-bottom:1px solid #263442;padding:2px 2px 14px}.home-summary strong{color:#edf4fa;font-size:16px}.home-summary p{margin:5px 0;color:#93a4b4;font-size:11px}.home-summary small{color:#f3ad5d;font-size:10px}.workload-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;padding-top:14px}.workload-card{display:grid;gap:5px;border:1px solid #2c4351;border-radius:8px;background:linear-gradient(145deg,#12212a,#0d151c);padding:12px;text-align:left;color:#dce6ee}.workload-card:hover{border-color:#62d9cc}.card-kind{color:#62d9cc;font-size:8px;letter-spacing:.12em}.workload-card strong{font-size:14px}.workload-card p{min-height:26px;margin:0;color:#90a2b2;font-size:10px}.workload-card dl{display:flex;gap:12px;margin:4px 0}.workload-card dl div{display:grid}.workload-card dt{color:#657889;font-size:8px;text-transform:uppercase}.workload-card dd{margin:2px 0 0;color:#d7e2ea;font-size:11px}.workload-card em{color:#9bd7a8;font-size:9px;font-style:normal}.workload-card em.stale{color:#ff9b9b}.empty-home{color:#8190a0;font-size:11px}.relationships-toggle{border:1px solid #2d4351;border-radius:4px;background:#111b24;padding:4px 7px;color:#9db0bf;font-size:9px}
 .semantic-atlas{background:radial-gradient(circle at 50% 45%,#111c26 0,#0a1016 48%,#070b0f 100%)}.atlas-breadcrumbs{display:flex;height:30px;align-items:center;gap:5px;padding:0 10px;border-bottom:1px solid #25313d;color:#8190a0;font-size:10px}.atlas-breadcrumbs button{color:#b9c7d4}.atlas-controls{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:6px 9px;border-bottom:1px solid #25313d;background:#0b1117}.lens-picker,.zoom-level{display:flex;align-items:center;gap:3px}.lens-picker button,.zoom-level button{border:1px solid transparent;border-radius:4px;padding:4px 7px;color:#8190a0;font-size:10px}.lens-picker button.active,.zoom-level button.active{border-color:#4b6275;background:#182431;color:#e4edf5}.zoom-level span{margin-right:4px;color:#607080;font-size:9px;text-transform:uppercase}.zoom-level button:not(.deeper){width:24px;padding:4px}.zoom-level .deeper{display:flex;align-items:center;gap:4px;color:#bda4ff}.graph{min-height:0;flex:1}.semantic-atlas footer{display:flex;min-height:30px;align-items:center;justify-content:space-between;gap:10px;border-top:1px solid #25313d;padding:4px 9px}.semantic-legend,.folded{display:flex;flex-wrap:wrap;gap:8px;color:#8190a0;font-size:9px}.semantic-legend span{display:flex;align-items:center;gap:4px}.semantic-legend i{width:7px;height:7px;border-radius:50%;background:var(--node-color)}.folded span{border-radius:10px;background:#151d26;padding:2px 6px}@media(max-width:850px){.atlas-controls{align-items:flex-start;flex-direction:column}.lens-picker{max-width:100%;overflow:auto}.zoom-level{display:none}}
</style>
