<script lang="ts">
  import {onMount} from 'svelte';import {api,atlasWebSocket} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  import Play from '@lucide/svelte/icons/play';import Square from '@lucide/svelte/icons/square';import ExternalLink from '@lucide/svelte/icons/external-link';import Stethoscope from '@lucide/svelte/icons/stethoscope';import RotateCw from '@lucide/svelte/icons/rotate-cw';import CirclePause from '@lucide/svelte/icons/circle-pause';import FolderOpen from '@lucide/svelte/icons/folder-open';
  export let params:Record<string,unknown>;export let state:WorkbenchState;
  let contextId=String(params.contextId??state.snapshot().contextId),repositoryPath=String(params.repositoryPath??'/workspace'),command=String(params.command??'npm run dev -- --host 0.0.0.0 --port 8000'),port=Number(params.port??8000),sessions:any[]=[];let current:any,status='';let confirmStart=false,diagnostics:any,stream:WebSocket|undefined;
  async function load(){const value=await api<any>('/api/live-projects');sessions=value.items;current=sessions.find(item=>item.id===current?.id)??sessions.find(item=>item.contextId===contextId&&['starting','running'].includes(item.status))??current}
  function watch(session:any){stream?.close();current=session;stream=atlasWebSocket(`/api/live-projects/${encodeURIComponent(session.id)}/events`);stream.onmessage=event=>{current=JSON.parse(event.data);sessions=sessions.map(item=>item.id===current.id?current:item)};stream.onclose=()=>stream=undefined}
  async function start(){confirmStart=false;status='Starting project terminal…';diagnostics=undefined;try{const value=await api<any>('/api/live-projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contextId,repositoryPath,command,port,confirm:true})});sessions=[value.session,...sessions.filter(item=>item.id!==value.session.id)];watch(value.session);status='Published through FNGK'}catch(error){const detail=(error as any).body??{};if(detail.liveProjectSession){sessions=[detail.liveProjectSession,...sessions.filter(item=>item.id!==detail.liveProjectSession.id)];current=detail.liveProjectSession;window.dispatchEvent(new CustomEvent('atlas:open-terminal',{detail:{contextId,sessionId:detail.liveProjectSession.terminalSessionId,target:contextId,title:'Project terminal'}}));}if(detail.diagnosticSessionId)window.dispatchEvent(new CustomEvent('atlas:open-logs',{detail:{diagnosticId:detail.diagnosticSessionId}}));status=(error as Error).message}}
  async function stop(){if(!current)return;await api(`/api/live-projects/${encodeURIComponent(current.id)}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true})});status='Project and route stopped';await load()}
  async function diagnose(){if(!current)return;status='Running browser diagnostics…';try{diagnostics=await api(`/api/live-projects/${encodeURIComponent(current.id)}/diagnostics`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});status=diagnostics.ok?'Diagnostics passed':'Diagnostics found a response failure'}catch(error){status=(error as Error).message}}
  async function action(action:'interrupt'|'restart'){if(!current)return;status=action==='restart'?'Restarting project and route…':'Interrupting project…';try{const value=await api<any>(`/api/live-projects/${encodeURIComponent(current.id)}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,confirm:true})});if(value.session){sessions=[value.session,...sessions.filter(item=>item.id!==current.id)];watch(value.session)}status=action==='restart'?'Project restarted':'Interrupt sent'}catch(error){status=(error as Error).message}}
  function browse(){window.dispatchEvent(new CustomEvent('atlas:pick-directory',{detail:{contextId,path:repositoryPath,target:'live-project'}}))}
  onMount(()=>{const picked=(event:Event)=>{const detail=(event as CustomEvent<{contextId:string;path:string;target?:string}>).detail;if(detail?.contextId===contextId&&detail.target==='live-project')repositoryPath=detail.path};window.addEventListener('atlas:directory-picked',picked);void load().then(()=>{if(current)watch(current)});return()=>{stream?.close();window.removeEventListener('atlas:directory-picked',picked)}});
</script>
<section class="panel live-project-panel">
  <header><strong>Live project</strong><span>{current?.status??'idle'} · {contextId}</span><button title="Refresh sessions" onclick={load}><RotateCw size={13}/></button></header>
  {#if current?.url&&['running','starting'].includes(current.status)}
    <div class="live-toolbar"><b>{current.command}</b><span>{current.repositoryPath} · :{current.port}</span><a href={current.url} target="_blank" rel="noreferrer" title="Open public route"><ExternalLink size={13}/></a><button title="Run Playwright diagnostics" onclick={diagnose}><Stethoscope size={14}/></button><button title="Interrupt process" onclick={()=>action('interrupt')}><CirclePause size={13}/></button><button title="Restart project and route" onclick={()=>action('restart')}><RotateCw size={13}/></button><button title="Stop project and public route" onclick={stop}><Square size={12}/></button></div>
    <div class="live-content"><iframe title="Live project preview" src={current.url}></iframe><pre aria-label="Live project output">{current.output||'Waiting for output…'}</pre></div>
  {:else}
    <form class="live-project-form" onsubmit={(event)=>{event.preventDefault();confirmStart=true}}><h3>Run on selected Device</h3><label>Repository path<div class="path-picker"><input bind:value={repositoryPath}/><button type="button" title="Choose from filesystem" onclick={browse}><FolderOpen size={14}/></button></div></label><label>Command<input bind:value={command}/></label><label>HTTP port<input type="number" min="1" max="65535" bind:value={port}/></label><button type="submit"><Play size={14}/>Start and publish</button><small>The command runs in a dedicated visible FNGK terminal. Port publication uses the Device daemon and Signal/HKMN.</small></form>
  {/if}
  {#if diagnostics}<section class="live-diagnostics"><b>{diagnostics.ok?'Reachable':'Needs attention'} · HTTP {diagnostics.status??'—'} · {diagnostics.durationMs} ms</b><span>{diagnostics.title}</span><span>{diagnostics.consoleErrors.length} console errors · {diagnostics.failedRequests.length} failed requests</span></section>{/if}
  <footer>{status||current?.error||'No project is running.'}</footer>
</section>
{#if confirmStart}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>Start and publish project?</h2><p><code>{command}</code> will run on {contextId} from {repositoryPath}, and port {port} will receive a Signal public route.</p><div><button onclick={()=>confirmStart=false}>Cancel</button><button onclick={start}>Start</button></div></div></div>{/if}
