<script lang="ts">
  import {onMount} from 'svelte';import {api} from '../lib/api.js';import type {WorkbenchState} from '../lib/workbench-state.js';import Play from '@lucide/svelte/icons/play';import RefreshCw from '@lucide/svelte/icons/refresh-cw';
  export let state:WorkbenchState;let rows:any[]=[];let runs:any[]=[];let indexes:any[]=[];let status='Loading metrics…';let root='';let contextId=state.snapshot().contextId;let indexId='';let command='';let running=false;let output='';let tab:'functions'|'problems'|'runs'='functions';
  const useful=(row:any)=>!/(^|\/)(?:web-dist|dist|build|coverage|node_modules|\.svelte-kit)(\/|$)|\.min\.[cm]?js$/i.test(row.path??'');
  async function loadFunctions(){const response=await api<any>(`/api/software/functions?limit=10000&contextId=${encodeURIComponent(contextId)}&indexId=${encodeURIComponent(indexId)}`);rows=(response.items??[]).filter(useful).sort((a:any,b:any)=>(b.crap??-1)-(a.crap??-1));status=`${rows.length} functions · ${rows.filter((row:any)=>row.coverage&&!row.coverage.stale).length} covered`}
  async function load(){try{const snapshot=await api<any>(`/api/state?contextId=${encodeURIComponent(contextId)}&fngk=0`);runs=snapshot.runs??[];indexes=snapshot.indexes??[];if(!snapshot.index){rows=[];status='Map a repository on this context to populate functions.';return}indexId=snapshot.index.id;root=snapshot.index.root;await loadFunctions();command=''}catch(error){status=(error as Error).message}}
  async function chooseIndex(){const selected=indexes.find(item=>item.id===indexId);if(!selected)return;root=selected.root;await loadFunctions();const commands=await api<any>(`/api/coverage/commands?contextId=${encodeURIComponent(contextId)}&repositoryPath=${encodeURIComponent(root)}`).catch(()=>({commands:[]}));command=commands.commands?.[0]?.command??'';}
  async function refreshCoverage(){if(!command||running)return;running=true;status='Running coverage through the selected context…';try{const result=await api<any>('/api/coverage/refresh',{method:'POST',body:JSON.stringify({contextId,indexId,repositoryPath:root,command})});output=result.output??'';status=result.coverage?.verified?'Coverage verified':'Coverage completed without verified evidence';await api('/api/world/refresh',{method:'POST',body:JSON.stringify({contextId})});window.dispatchEvent(new Event('atlas:graph-refresh'));await load()}catch(error){status=(error as Error).message}finally{running=false}}
  function open(row:any){window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId,path:`${root}/${row.path}`.replaceAll('//','/'),pinned:true,line:row.line}}))}
  onMount(()=>{void load();const refresh=()=>void load(),unsubscribe=state.subscribe(value=>{if(value.contextId!==contextId){contextId=value.contextId;void load();}});window.addEventListener('atlas:graph-refresh',refresh);return()=>{unsubscribe();window.removeEventListener('atlas:graph-refresh',refresh)}});
</script>

<section class="panel metrics-panel"><header><div><strong>Evidence</strong><span>{status}</span></div><div class="metric-actions"><select bind:value={indexId} onchange={chooseIndex} aria-label="Repository index">{#each indexes as item}<option value={item.id}>{item.root}</option>{/each}</select><input bind:value={command} aria-label="Coverage command" placeholder="coverage command"/><button onclick={refreshCoverage} disabled={!command||running} title="Run coverage through FNGK"><Play size={13}/></button><button onclick={load} title="Refresh evidence"><RefreshCw size={13}/></button></div></header>
  <div class="evidence-tabs"><button class:active={tab==='functions'} onclick={()=>tab='functions'}>Functions <span>{rows.length}</span></button><button class:active={tab==='problems'} onclick={()=>tab='problems'}>Problems <span>{rows.filter(row=>row.crap>30||row.coverage?.stale).length}</span></button><button class:active={tab==='runs'} onclick={()=>tab='runs'}>Runs <span>{runs.length}</span></button></div>
  {#if output}<details class="run-output"><summary>Latest coverage output</summary><pre>{output}</pre></details>{/if}
  {#if tab==='functions'}<div class="metrics-table"><table><thead><tr><th>Function</th><th>File</th><th>Lines</th><th>Complexity</th><th>Coverage</th><th>CRAP</th></tr></thead><tbody>{#each rows as row}<tr ondblclick={()=>open(row)}><td>{row.qualifiedName??row.label}</td><td>{row.path}:{row.line}</td><td>{row.physicalLines??'—'}</td><td>{row.complexity??'—'}</td><td>{row.coverage?`${Math.round(row.coverage.fraction*100)}%${row.coverage.stale?' stale':''}`:'—'}</td><td class:bad={row.crap>30}>{row.crap==null?'—':Number(row.crap).toFixed(1)}</td></tr>{/each}</tbody></table>{#if !rows.length}<div class="empty-copy">No function evidence for this context. Use the repository action on its Device row to map code.</div>{/if}</div>
  {:else if tab==='problems'}<div class="problem-list">{#each rows.filter(row=>row.crap>30||row.coverage?.stale) as row}<button onclick={()=>open(row)}><b>{row.qualifiedName??row.label}</b><span>{row.crap>30?`CRAP ${Number(row.crap).toFixed(1)}`:'stale coverage'} · {row.path}:{row.line}</span></button>{/each}{#if !rows.some(row=>row.crap>30||row.coverage?.stale)}<div class="empty-copy">No measured high-risk or stale functions. Unmeasured coverage remains visible as “—” in Functions.</div>{/if}</div>
  {:else}<div class="run-list">{#each runs as run}<article><b>{run.mode} · {run.status}</b><span>{run.symbolId}</span><small>{run.createdAt} · {run.durationMs??'—'} ms</small></article>{/each}{#if !runs.length}<div class="empty-copy">No Atlas operations have been recorded yet.</div>{/if}</div>{/if}
</section>
