<script lang="ts">
  import PanelsTopLeft from '@lucide/svelte/icons/panels-top-left';import SquareTerminal from '@lucide/svelte/icons/square-terminal';import FileText from '@lucide/svelte/icons/file-text';import FolderOpen from '@lucide/svelte/icons/folder-open';import Rocket from '@lucide/svelte/icons/rocket';import Database from '@lucide/svelte/icons/database';import Bot from '@lucide/svelte/icons/bot';import BookOpen from '@lucide/svelte/icons/book-open';import ChartNoAxesCombined from '@lucide/svelte/icons/chart-no-axes-combined';import PanelRightOpen from '@lucide/svelte/icons/panel-right-open';import WorkbenchContextMenu from './WorkbenchContextMenu.svelte';import type {AtlasPanelDescriptor} from '../lib/panel-registry.js';
  export let items:AtlasPanelDescriptor[]=[];export let visibleCount=7;export let onrestore:(id:string)=>void=()=>{};export let onforget:(id:string)=>void=()=>{};let menu:{x:number;y:number;item:AtlasPanelDescriptor}|undefined;let overflow=false;
  function panelIcon(kind:string){if(kind==='terminal')return SquareTerminal;if(kind==='file')return FileText;if(kind==='filesystem'||kind==='navigator')return FolderOpen;if(kind==='deployment'||kind==='live-project')return Rocket;if(kind==='database')return Database;if(kind==='agent-chat'||kind==='intelligence')return Bot;if(kind==='documentation')return BookOpen;if(kind==='operations'||kind==='output'||kind==='metrics'||kind==='logs')return ChartNoAxesCombined;return PanelRightOpen;}
  $: shown=items.slice(-visibleCount).reverse();$: hidden=items.slice(0,Math.max(0,items.length-visibleCount)).reverse();
</script>
{#if items.length}<div class="minimized-tray" aria-label="Minimized panels">
  {#each shown as item}{@const Icon=panelIcon(item.kind)}<button class="minimized-panel-icon" aria-label={`Restore ${item.title}`} title={`Restore ${item.title}`} onclick={()=>onrestore(item.id)} oncontextmenu={(event)=>{event.preventDefault();menu={x:event.clientX,y:event.clientY,item}}}><Icon size={15}/></button>{/each}
  {#if hidden.length}<div class="minimized-overflow"><button aria-label={`${hidden.length} more minimized panels`} title={`${hidden.length} more minimized panels`} onclick={()=>overflow=!overflow}><PanelsTopLeft size={15}/><i>{hidden.length}</i></button>{#if overflow}<div role="menu">{#each hidden as item}{@const Icon=panelIcon(item.kind)}<button role="menuitem" onclick={()=>{overflow=false;onrestore(item.id)}}><Icon size={13}/><span>{item.title}</span></button>{/each}</div>{/if}</div>{/if}
</div>{/if}
{#if menu}<WorkbenchContextMenu x={menu.x} y={menu.y} actions={[{id:'restore',label:'Restore panel'},{id:'close',label:'Close panel',danger:true}]} onclose={()=>menu=undefined} onrun={(action)=>{if(action==='restore')onrestore(menu!.item.id);else onforget(menu!.item.id)}}/>{/if}
