<script lang="ts">
  import {onMount} from 'svelte';
  import {api,websocketUrl} from '../lib/api.js';
  import {chooseContext,type WorkbenchState} from '../lib/workbench-state.js';
  import Search from '@lucide/svelte/icons/search';import SquareTerminal from '@lucide/svelte/icons/square-terminal';import ScanSearch from '@lucide/svelte/icons/scan-search';import Map from '@lucide/svelte/icons/map';import MoreHorizontal from '@lucide/svelte/icons/more-horizontal';import FolderOpen from '@lucide/svelte/icons/folder-open';import Network from '@lucide/svelte/icons/network';import Activity from '@lucide/svelte/icons/activity';import Database from '@lucide/svelte/icons/database';
  export let state:WorkbenchState;
  let contexts:any[]=[];let selected='local';let current:any;let status='Discovering FNGK…';let repository='/workspace';let overflow='';let query='';let results:any[]=[];let searching=false;let timer:any;let searchController:AbortController|undefined;let searchGeneration=0;const sockets=new Set<WebSocket>();
  const label=(item:any)=>`${item.name}${item.device?.agentMode?` · ${item.device.agentMode}`:''}${item.device?.id?` · ${item.device.id.slice(0,8)}`:''}`;
  async function load(){state.setConnection({phase:'checking',message:'Discovering installed FNGK…'});try{const value=await api<any>('/api/contexts');contexts=value.contexts;selected=chooseContext(contexts,state.snapshot());state.setContext(selected,false);if(value.state.compatible){status=`${value.state.profile??'default'} · ${value.state.version}`;state.setConnection({phase:'connected',message:`Connected to ${value.state.profile??'default'}`,profile:value.state.profile,version:value.state.version});}else{status=value.state.reason??'FNGK unavailable';state.setConnection({phase:value.state.login==='required'?'authentication-required':'unavailable',message:status,profile:value.state.profile,version:value.state.version});}}catch(error){status=(error as Error).message;contexts=[{id:'local',name:'Atlas process host',kind:'local',online:true}];selected='local';state.setContext('local',false);state.setConnection({phase:'unavailable',message:status});}}
  function scan(){const socket=new WebSocket(websocketUrl(`/api/discovery/scan?contextId=${encodeURIComponent(selected)}`));let failed=false;sockets.add(socket);status='Scanning host…';socket.onmessage=e=>{const v=JSON.parse(e.data);if(v.type==='error'){failed=true;status=v.message??v.code;}state.appendActivity(`${v.type} · ${v.scanned??''}`)};socket.onclose=()=>{sockets.delete(socket);if(!failed){status='Scan complete';window.dispatchEvent(new Event('atlas:graph-refresh'))}}}
  function analyze(){if(!repository.trim())return;const socket=new WebSocket(websocketUrl(`/api/analysis/repository?contextId=${encodeURIComponent(selected)}&path=${encodeURIComponent(repository)}`));let completed=false,failed=false;sockets.add(socket);status='Mapping repository…';socket.onmessage=e=>{const v=JSON.parse(e.data);if(v.type==='error'){failed=true;status=v.message??v.code}state.appendActivity(`${v.type} · ${v.index?.summary?.functions??v.nodes?.length??''}`);if(v.type==='analysis_complete'){completed=true;status=`${v.index.summary.functions} functions mapped`;window.dispatchEvent(new Event('atlas:graph-refresh'))}};socket.onclose=()=>{sockets.delete(socket);if(!completed&&!failed)status='Analysis stopped'}}
  function action(name:string){overflow='';if(name==='terminal')window.dispatchEvent(new Event('atlas:open-terminal'));if(name==='database')window.dispatchEvent(new CustomEvent('atlas:open-database',{detail:{contextId:selected}}));if(name==='files')window.dispatchEvent(new Event('atlas:focus-files'));if(name==='scan')scan();if(name==='map')analyze();if(name==='architecture')window.dispatchEvent(new Event('atlas:graph-refresh'));}
  function search(){clearTimeout(timer);searchController?.abort();searchGeneration++;results=[];searching=false;window.dispatchEvent(new CustomEvent('atlas:search-query',{detail:{query}}))}
  function openResult(item:any){const resultContext=item.contextId??selected;if(resultContext!==selected)return;if(item.path&&['file','module','function','test'].includes(item.type)){const root=item.repositoryRoot??repository,path=item.path.startsWith('/')?item.path:`${root}/${item.path}`.replaceAll('//','/');window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId:resultContext,path,pinned:true}}));return}state.select({id:item.entityId,type:item.type,path:item.path});window.dispatchEvent(new Event('atlas:graph-refresh'))}
  $: current=contexts.find(item=>item.id===selected);
  onMount(()=>{void load();void api<any>('/api/contexts').then(value=>{const local=value.contexts?.find((item:any)=>item.id==='local');if(local?.workspaceRoot)repository=local.workspaceRoot}).catch(()=>{});const stateUnsub=state.subscribe(value=>{if(value.contextId===selected)return;searchController?.abort();searchGeneration++;selected=value.contextId;overflow='';results=[];query='';}),runScan=()=>scan(),runAnalyze=()=>analyze();window.addEventListener('atlas:scan',runScan);window.addEventListener('atlas:analyze',runAnalyze);return()=>{stateUnsub();searchController?.abort();clearTimeout(timer);for(const socket of sockets)socket.close();window.removeEventListener('atlas:scan',runScan);window.removeEventListener('atlas:analyze',runAnalyze)}});
</script>

<aside class="navigator context-navigator"><section class="context-sidebar">
    <header><div><strong>{current?.name??'Context'}</strong><small>{current?label(current):selected}</small></div><div><button title="Browse filesystem" onclick={()=>action('files')}><FolderOpen size={14}/></button>{#if current?.kind==='fngk-device'}<button title="Open terminal" onclick={()=>action('terminal')}><SquareTerminal size={14}/></button>{/if}<button title="More actions" onclick={()=>overflow=overflow?'':selected}><MoreHorizontal size={15}/></button></div></header>
    {#if overflow}<div class="context-popover"><button onclick={()=>action('architecture')}><Network size={13}/>Architecture</button><button onclick={()=>action('scan')}><ScanSearch size={13}/>Scan host</button><button onclick={()=>action('map')}><Map size={13}/>Map repository</button><button onclick={()=>action('database')}><Database size={13}/>Databases</button><button onclick={()=>window.dispatchEvent(new Event('atlas:focus-metrics'))}><Activity size={13}/>Evidence</button></div>{/if}
    <div class="context-search"><Search size={14}/><input bind:value={query} oninput={search} placeholder="Search functions, modules, processes…" aria-label="Search selected context"/>{#if searching}<span>…</span>{/if}</div>
    <div class="search-results">{#each results as item}<button onclick={()=>openResult(item)}><span>{item.type}</span><b>{item.label}</b><small>{item.path||item.detail}</small><em>{item.contextId??selected} · {item.source??'index'}</em></button>{/each}{#if query&&!searching&&!results.length}<p>No indexed matches in this context.</p>{/if}</div>
    <div class="repository-config"><label for="repository-path">Repository path</label><div><input id="repository-path" bind:value={repository} aria-label="Repository path"/><button title="Map repository" onclick={analyze}><Map size={14}/></button></div></div>
    <footer>{status}</footer>
  </section></aside>
