<script lang="ts">
 import {onMount} from 'svelte';import {atlasEvents,type AtlasEvent} from '../lib/atlas-events.js';import AtlasInput from './ui/AtlasInput.svelte';
 let events:AtlasEvent[]=[];let filter='';let selectedId='';let confirmClear=false;
 // Cancellation is normal control flow for superseded UI work.  It is removed
 // at the producer now; this filter also hides cancellation records persisted
 // by earlier Atlas versions so the operational history stays actionable.
 $: visible=events.filter(event=>event.state!=='cancelled'&&`${event.title} ${event.type} ${event.state}`.toLowerCase().includes(filter.toLowerCase()));
 onMount(()=>atlasEvents.subscribe(value=>events=value));
</script>
<section class="observability" aria-label="Observability"><header><div><strong>Observability</strong><small>Local operation history</small></div><AtlasInput bind:value={filter} placeholder="Filter events" ariaLabel="Filter operation history"/><button onclick={()=>confirmClear=true}>Clear unpinned</button></header>{#if confirmClear}<div class="clear-confirm" role="alertdialog" aria-label="Clear unpinned events"><span>Clear local unpinned events?</span><button onclick={()=>{atlasEvents.clearUnpinned();confirmClear=false}}>Clear</button><button onclick={()=>confirmClear=false}>Cancel</button></div>{/if}<div class="events">{#each visible.slice().reverse() as event (event.id)}<article class:expanded={selectedId===event.id} class={`event ${event.state}`}><button title={event.pinned?'Unpin event':'Pin event'} onclick={()=>atlasEvents.pin(event.id,!event.pinned)}>{event.pinned?'★':'☆'}</button><button class="event-summary" onclick={()=>selectedId=selectedId===event.id?'':event.id} aria-expanded={selectedId===event.id}><b>{event.title}</b><small>{event.type} · {event.state}{event.message?` · ${event.message}`:''}</small></button>{#if event.source==='local'}<button title="Delete local event" aria-label={`Delete ${event.title}`} onclick={()=>atlasEvents.removeLocal(event.id)}>×</button>{/if}{#if selectedId===event.id}<dl><div><dt>Updated</dt><dd>{new Date(event.updatedAt??event.createdAt).toLocaleString()}</dd></div>{#if event.contextId}<div><dt>Context</dt><dd>{event.contextId}</dd></div>{/if}{#if event.panelId}<div><dt>Panel</dt><dd>{event.panelId}</dd></div>{/if}{#if event.correlationId}<div><dt>Correlation</dt><dd>{event.correlationId}</dd></div>{/if}{#each Object.entries(event.metadata??{}) as [key,value]}<div><dt>{key}</dt><dd>{String(value)}</dd></div>{/each}</dl>{/if}</article>{/each}{#if !visible.length}<p>No operation events yet.</p>{/if}</div></section>
<style>.observability{height:100%;display:grid;grid-template-rows:auto auto 1fr;font-size:11px}.observability header{display:flex;gap:8px;align-items:center;padding:8px;border-bottom:1px solid var(--atlas-border)}.observability header div{margin-right:auto}.observability small{display:block;color:var(--atlas-muted)}.clear-confirm{display:flex;gap:7px;align-items:center;padding:6px 8px;background:color-mix(in srgb,var(--atlas-warning) 12%,var(--atlas-surface));border-bottom:1px solid var(--atlas-border)}.events{overflow:auto;padding:6px}.event{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:7px;padding:7px;border-bottom:1px solid color-mix(in srgb,var(--atlas-border) 55%,transparent)}.event.error{border-left:2px solid var(--atlas-danger)}.event.warning{border-left:2px solid var(--atlas-warning)}.event>button{background:transparent;border:0;padding:0 2px}.event-summary{text-align:left;min-width:0}.event b{display:block}.event.expanded dl{grid-column:2/-1;display:grid;gap:4px;margin:3px 0 0}.event.expanded dl div{display:grid;grid-template-columns:72px minmax(0,1fr);gap:6px}.event dt,.event dd{margin:0}.event dt{color:var(--atlas-muted)}.event dd{overflow-wrap:anywhere}.events p{color:var(--atlas-muted)}</style>
