<script lang="ts">
 import {onDestroy} from 'svelte';import cytoscape from 'cytoscape';import type {WorkbenchState} from '../lib/workbench-state.js';
 export let projection:any;export let state:WorkbenchState;export let onenter:(id:string)=>void=()=>{};let host:HTMLDivElement,cy:cytoscape.Core|undefined,last:any;
 const colors:Record<string,string>={device:'#d3fa72',workload:'#62d9cc',capability:'#bda4ff',service:'#ff9e78',process:'#ff7d78',container:'#f3ad5d',repository:'#d3fa72',package:'#bda4ff',module:'#62d9cc',function:'#78a7ff',database:'#f3ad5d',port:'#48b9ff',identity:'#e68bd4'};
 function draw(value:any){if(!host||!value||value===last)return;last=value;cy?.destroy();cy=cytoscape({container:host,elements:[...(value.nodes??[]).map((node:any)=>({data:node})),...(value.edges??[]).map((edge:any)=>({data:edge}))],style:[{selector:'node',style:{'background-color':(node:any)=>colors[node.data('kind')]??'#718096','border-color':(node:any)=>node.data('stale')?'#ef4444':'#111923','border-style':(node:any)=>node.data('classification')==='inferred'?'dashed':'solid','border-width':3,label:'data(label)','font-size':11,color:'#dce5ef','text-valign':'bottom','text-margin-y':8,'text-outline-color':'#080d12','text-outline-width':3,width:(node:any)=>node.data('kind')==='workload'?46:28,height:(node:any)=>node.data('kind')==='workload'?46:28} as any},{selector:'edge',style:{'line-color':'#526375','target-arrow-color':'#526375','target-arrow-shape':'triangle','curve-style':'bezier','line-style':(edge:any)=>edge.data('classification')==='inferred'?'dashed':'solid','label':'data(type)','font-size':7,color:'#8293a4','text-background-color':'#0a1016','text-background-opacity':.8} as any},{selector:':selected',style:{'border-color':'#fff','border-width':4}}],layout:{name:'breadthfirst',directed:true,padding:45,spacingFactor:1.5} as any});cy.on('tap','node',event=>{const data=event.target.data();state.select({id:data.id,type:data.kind,contextId:data.contextId,label:data.label,semantic:true})});cy.on('dbltap','node',event=>onenter(event.target.id()))}
 $: { draw(projection); }
 onDestroy(()=>{cy?.destroy()});
</script>
<section class="relationships-surface"><div class="relationships-view" bind:this={host} aria-label="Contextual relationships"></div><div class="relationship-summary" aria-label="Relationship list"><h3>Visible relationships</h3>{#each projection?.edges??[] as edge}{@const source=(projection?.nodes??[]).find((node:any)=>node.id===edge.source)}{@const target=(projection?.nodes??[]).find((node:any)=>node.id===edge.target)}<article><button onclick={()=>target&&state.select({id:target.id,type:target.kind,contextId:target.contextId,label:target.label,semantic:true})}><span>{source?.label??edge.source}</span><b>{edge.type.replaceAll('-',' ')}</b><span>{target?.label??edge.target}</span><small>{edge.classification} · {Math.round((edge.confidence??1)*100)}%</small></button><button class="relationship-open" disabled={!target} onclick={()=>target&&onenter(target.id)}>Open</button></article>{:else}<p>No relationships are visible at this depth.</p>{/each}</div></section>
<style>
 .relationship-summary article{display:grid;grid-template-columns:minmax(0,1fr) auto;border-top:1px solid #202c36}.relationship-summary article>button:first-child{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto;border:0;border-top:0}.relationship-summary .relationship-open{display:block;width:auto;border:0;border-left:1px solid #263641;border-radius:0;padding:0 8px;color:#62d9cc;font-size:8px}.relationship-summary .relationship-open:disabled{opacity:.35}
</style>
