<script lang="ts">
 import {onMount} from 'svelte';import ArrowUp from '@lucide/svelte/icons/arrow-up';import Home from '@lucide/svelte/icons/house';import RefreshCw from '@lucide/svelte/icons/refresh-cw';import Sparkles from '@lucide/svelte/icons/sparkles';import {api} from '../lib/api.js';import {ATLAS_VIEWS,createAtlasNavigation,parseAtlasLocation,serializeAtlasLocation,type AtlasLocation,type AtlasView} from '../lib/atlas-navigation.js';import type {WorkbenchState} from '../lib/workbench-state.js';import AtlasBreadcrumbs from './AtlasBreadcrumbs.svelte';import AtlasViewTabs from './AtlasViewTabs.svelte';import MachineOverview from './MachineOverview.svelte';import RelationshipsView from './RelationshipsView.svelte';
 export let state:WorkbenchState;let location:AtlasLocation={contextId:state.snapshot().contextId,view:'overview',level:0},navigation=createAtlasNavigation(location),projection:any,error='',loading=true,generation=0;
 const title=(value:string)=>value.replaceAll('-',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
 function commit(mode:'push'|'replace'='push'){location=navigation.snapshot();window.history[mode==='push'?'pushState':'replaceState']({},'',`${window.location.pathname}${serializeAtlasLocation(location,window.location.search)}`);void load()}
 function enter(id:string){navigation.enter(id);commit()}
 function inspect(card:any){state.select({id:card.id,type:card.kind,contextId:location.contextId,label:card.title,semantic:true})}
 function home(){navigation.home(location.contextId);commit()}
 function up(){const breadcrumbs=projection?.breadcrumbs??[],parent=breadcrumbs.length>1?breadcrumbs[breadcrumbs.length-2]?.id:undefined;navigation.up(parent);commit()}
 function openView(view:AtlasView){navigation.openView(view);commit()}
 async function load(){const token=++generation;loading=true;error='';try{const query=new URLSearchParams({contextId:location.contextId,lens:location.view,level:String(location.level),budget:'180'});if(location.rootId)query.set('rootId',location.rootId);const value=await api<any>(`/api/world/projection?${query}`);if(token!==generation)return;projection=value;if(location.rootId&&value.rootId!==location.rootId){navigation.home(location.contextId);location=navigation.snapshot();window.history.replaceState({},'',`${window.location.pathname}${serializeAtlasLocation(location,window.location.search)}`)}}catch(value){if(token===generation)error=(value as Error).message}finally{if(token===generation)loading=false}}
 async function refreshEvidence(){const target=location.contextId,token=++generation;loading=true;error='';try{await api('/api/world/refresh',{method:'POST',body:JSON.stringify({contextId:target})});if(token!==generation||target!==location.contextId)return;await load()}catch(value){if(token===generation)error=(value as Error).message;loading=false}}
 onMount(()=>{location=parseAtlasLocation(window.location.search,state.snapshot().contextId);navigation=createAtlasNavigation(location);commit('replace');const pop=()=>{location=parseAtlasLocation(window.location.search,state.snapshot().contextId);navigation=createAtlasNavigation(location);void load()},refresh=()=>void load(),navigate=(event:Event)=>{const detail=(event as CustomEvent<{rootId?:string;view?:AtlasView}>).detail;if(detail?.rootId)navigation.enter(detail.rootId);if(detail?.view)navigation.openView(detail.view);commit()},unsubscribe=state.subscribe(value=>{if(value.contextId===location.contextId)return;navigation.home(value.contextId);commit('replace')});window.addEventListener('popstate',pop);window.addEventListener('atlas:graph-refresh',refresh);window.addEventListener('atlas:navigate',navigate);return()=>{generation++;unsubscribe();window.removeEventListener('popstate',pop);window.removeEventListener('atlas:graph-refresh',refresh);window.removeEventListener('atlas:navigate',navigate)}});
</script>
<section class="panel semantic-atlas"><header class="semantic-header"><div><strong>{projection?.synthesis?.headline??'Atlas'}</strong><span>{location.rootId?'Semantic entity':'Device home'} · {title(location.view)}</span></div><div><button title="Device home" aria-label="Device home" onclick={home}><Home size={14}/></button><button title="Up one semantic level" aria-label="Up one semantic level" disabled={!location.rootId} onclick={up}><ArrowUp size={14}/></button><button title="Refresh semantic evidence" aria-label="Refresh semantic evidence" disabled={loading} onclick={refreshEvidence}><RefreshCw size={14}/></button><button title="Open Atlas intelligence" aria-label="Open Atlas intelligence" onclick={()=>window.dispatchEvent(new Event('atlas:open-intelligence'))}><Sparkles size={14}/></button></div></header>
<AtlasBreadcrumbs items={projection?.breadcrumbs??[]} onenter={enter}/><AtlasViewTabs views={projection?.availableViews??ATLAS_VIEWS} active={location.view} onchange={openView}/>
{#if loading}<div class="semantic-state">Interpreting current Device evidence…</div>{:else if error}<div class="panel-error">{error}<button onclick={()=>load()}>Try again</button></div>{:else if location.view==='relationships'}<RelationshipsView {projection} {state} onenter={enter}/>{:else if location.view==='overview'}<MachineOverview {projection} onenter={enter} oninspect={inspect}/>{:else}<section class="semantic-entity-view"><div class="entity-view-summary"><small>{title(location.view)}</small><h2>{projection?.synthesis?.headline}</h2>{#each projection?.synthesis?.facts??[] as fact}<p>{fact.text}</p>{/each}</div><div class="entity-list">{#each projection?.nodes??[] as node (node.id)}<article class:stale={node.stale}><button onclick={()=>enter(node.id)}><small>{node.kind}</small><strong>{node.label}</strong><span>{node.classification??'observed'} · {Math.round((node.confidence??1)*100)}%</span></button><button class="inspect" onclick={()=>state.select({id:node.id,type:node.kind,contextId:node.contextId,label:node.label,semantic:true})}>Inspect</button></article>{:else}<div class="semantic-empty"><strong>No {location.view} evidence yet</strong><p>Atlas retains unknowns rather than inventing structure. Scan the Device or map the relevant repository.</p></div>{/each}</div></section>{/if}
</section>
