<script lang="ts">
  import { onMount } from 'svelte';
  import { Terminal } from '@xterm/xterm';
  import { FitAddon } from '@xterm/addon-fit';
  import { websocketUrl } from '../lib/api.js';
  import type { WorkbenchState } from '../lib/workbench-state.js';
  export let params:{target?:string;profile?:string;session?:string}={}; export let state:WorkbenchState;
  let host:HTMLDivElement;let target=params.target??'';let sessionId=params.session??'';let newSession=!params.session;let terminal:Terminal;let fit:FitAddon;let socket:WebSocket|undefined;let status='Detached';let request=0;let approval='';
  const send=(value:Record<string,unknown>)=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify(value));const encoded=(value:string)=>{const bytes=new TextEncoder().encode(value);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
  function connect(){if(!target.trim())return;socket?.close();terminal.reset();terminal.writeln(`\x1b[38;2;211;250;114mFNGK Atlas\x1b[0m  attaching to ${target}…`);status='Connecting';const selection=sessionId?`&session=${encodeURIComponent(sessionId)}`:newSession?'&new=1':'';const current=new WebSocket(websocketUrl(`/api/fngk/terminals?target=${encodeURIComponent(target)}${selection}${params.profile?`&profile=${encodeURIComponent(params.profile)}`:''}`));socket=current;current.onmessage=event=>{if(socket!==current)return;const value=JSON.parse(event.data);if(value.type==='ready'){sessionId=String(value.sessionId??sessionId);status=`Live · ${value.sessionId}`;terminal.writeln(`\x1b[2mconnected · ${value.target??target} · ${value.recordingMode??'recorded'}\x1b[0m`);resize();}else if(value.type==='output'||value.type==='replay'){try{terminal.write(Uint8Array.from(atob(value.bodyBase64),c=>c.charCodeAt(0)));}catch{}}else if(value.type==='approval'){approval=String(value.approvalId);terminal.writeln(`\r\n\x1b[33mApproval required: ${value.approvalId}\x1b[0m`);}else if(value.type==='collaboration'){status=`Live · ${value.mode??value.collaborationMode??'collaborative'}`;}else if(value.type==='error'){terminal.writeln(`\r\n\x1b[31m${value.message??value.code}\x1b[0m`);}else if(value.type==='exit'){terminal.writeln(`\r\n[exit ${value.exitCode??''}]`);}state.appendActivity(`terminal · ${value.type}`);};current.onclose=()=>{if(socket===current)status='Detached';};current.onerror=()=>{if(socket===current)status='Connection error';};}
  function resolveApproval(decision:'approve'|'deny'){send({type:'nested_approval_resolve',requestId:`approval-${++request}`,approvalId:approval,decision});approval='';}
  function resize(){fit.fit();send({type:'resize',requestId:`resize-${++request}`,cols:terminal.cols,rows:terminal.rows});}
  function detach(){send({type:'detach',requestId:`detach-${++request}`});}
  function stop(){if(confirm('Stop this remote terminal session?'))send({type:'stop',requestId:`stop-${++request}`});}
  onMount(()=>{terminal=new Terminal({convertEol:true,fontFamily:'JetBrains Mono, ui-monospace, monospace',fontSize:12,theme:{background:'#080b0f',foreground:'#d8e2ec',cursor:'#d3fa72',selectionBackground:'#334154'}});fit=new FitAddon();terminal.loadAddon(fit);terminal.open(host);fit.fit();terminal.onData(data=>send({type:'input',requestId:`input-${++request}`,bodyBase64:encoded(data)}));const observer=new ResizeObserver(resize);observer.observe(host);return()=>{observer.disconnect();socket?.close();terminal.dispose();};});
</script>
<section class="panel terminal-panel"><header><div class="terminal-target"><input bind:value={target} placeholder="Device or Connection" aria-label="Terminal target"><input class="session-input" bind:value={sessionId} placeholder="Session ID (optional)" aria-label="Terminal session"><label><input type="checkbox" bind:checked={newSession} disabled={Boolean(sessionId)}>new</label><button onclick={connect}>{socket?.readyState===WebSocket.OPEN?'Restart':'Attach'}</button></div><span>{status}</span><div>{#if approval}<button onclick={()=>resolveApproval('approve')}>Approve</button><button onclick={()=>resolveApproval('deny')}>Deny</button>{/if}<button onclick={()=>send({type:'interrupt',requestId:`interrupt-${++request}`})}>Ctrl+C</button><button onclick={detach}>Detach</button><button class="danger" onclick={stop}>Stop</button></div></header><div class="terminal" bind:this={host}></div></section>
