<script lang="ts">
  import { onMount } from 'svelte'; import { Terminal } from '@xterm/xterm'; import { FitAddon } from '@xterm/addon-fit';
  import Plus from '@lucide/svelte/icons/plus'; import MoreVertical from '@lucide/svelte/icons/more-vertical'; import RotateCw from '@lucide/svelte/icons/rotate-cw'; import Pencil from '@lucide/svelte/icons/pencil'; import Square from '@lucide/svelte/icons/square'; import Archive from '@lucide/svelte/icons/archive'; import ArchiveRestore from '@lucide/svelte/icons/archive-restore'; import X from '@lucide/svelte/icons/x';
  import { api, atlasWebSocket } from '../lib/api.js'; import type { WorkbenchState } from '../lib/workbench-state.js';import DocumentationHelp from './DocumentationHelp.svelte';
  type Session={id:string;title?:string;status?:string;deviceId?:string;deviceName?:string;archivedAt?:string;kind?:string;diagnosticSessionId?:string;processId?:string;runId?:string};
  export let params:{target?:string;profile?:string;session?:string;panelId?:string;newSession?:boolean;requestId?:string}={}; export let state:WorkbenchState;
  let host:HTMLDivElement,target=params.target??(state.snapshot().contextId.startsWith('device:')?state.snapshot().contextId:''),sessionId=params.session??'',streamId='',newSession=Boolean(params.newSession),terminal:Terminal,fit:FitAddon,socket:WebSocket|undefined,status='Opening…',request=0,approval='',sessions:Session[]=[],counts={total:0,active:0,live:0,detached:0,archived:0},menu='',dialog:{kind:'rename'|'stop'|'archive';session:Session}|undefined,title='',disposed=false,retries=0,reconnectTimer:any,generation=0,lastRequest='',createWarning=false;
  const colors=['#d3fa72','#62d9cc','#8da7ff','#f0a8ff','#ffb86b','#ff8585'],color=(id:string)=>colors[[...id].reduce((sum,char)=>sum+char.charCodeAt(0),0)%colors.length];
  const send=(value:Record<string,unknown>)=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify(value));
  const encoded=(value:string)=>{const bytes=new TextEncoder().encode(value);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
  const deviceId=()=>target.startsWith('device:')?target.slice(7):'';
  async function loadSessions(){try{const query=new URLSearchParams();if(params.profile)query.set('profile',params.profile);if(deviceId())query.set('deviceId',deviceId());const value=await api<any>(`/api/fngk/sessions?${query}`);sessions=value.sessions??[];counts=value.counts??{total:sessions.length,active:sessions.filter(item=>!item.archivedAt).length,live:0,detached:0,archived:sessions.filter(item=>item.archivedAt).length};return sessions;}catch(error){state.appendActivity(`sessions unavailable · ${(error as Error).message}`);return []}}
  async function bootstrap(explicit=false){const available=await loadSessions();if(disposed)return;if(!explicit&&!sessionId&&!newSession){const reusable=available.find(item=>!item.archivedAt&&!['stopped','exited','failed'].includes(String(item.status??'').toLowerCase()));if(reusable)sessionId=reusable.id;else newSession=true;}connect(true);}
  function connect(force=false){
    if(!target.trim()||disposed)return;if(socket&&!force&&(socket.readyState===WebSocket.OPEN||socket.readyState===WebSocket.CONNECTING))return;
    clearTimeout(reconnectTimer);const token=++generation;socket?.close();terminal.reset();terminal.writeln(`\x1b[38;2;211;250;114mFNGK Atlas\x1b[0m  attaching to ${target}…`);status=retries?'Reconnecting…':'Connecting…';
    const selection=sessionId?`&session=${encodeURIComponent(sessionId)}`:newSession?'&new=1':'',current=atlasWebSocket(`/api/fngk/terminals?target=${encodeURIComponent(target)}${selection}${params.profile?`&profile=${encodeURIComponent(params.profile)}`:''}`);socket=current;
    current.onmessage=event=>{if(socket!==current||token!==generation)return;const value=JSON.parse(event.data);if(value.type==='ready'){sessionId=String(value.sessionId??sessionId);streamId=String(value.streamId??streamId);newSession=false;retries=0;status='Live';window.dispatchEvent(new CustomEvent('atlas:terminal-ready',{detail:{panelId:params.panelId,session:sessionId,streamId}}));terminal.writeln(`\x1b[2mconnected · ${value.target??target} · ${value.recordingMode??'recorded'}\x1b[0m`);resize();void loadSessions();}else if(value.type==='output'||value.type==='replay'){try{terminal.write(Uint8Array.from(atob(value.bodyBase64),c=>c.charCodeAt(0)));}catch{}}else if(value.type==='approval'){approval=String(value.approvalId);terminal.writeln(`\r\n\x1b[33mApproval required: ${value.approvalId}\x1b[0m`);}else if(value.type==='collaboration'){status=`Live · ${value.mode??value.collaborationMode??'collaborative'}`;}else if(value.type==='error'){terminal.writeln(`\r\n\x1b[31m${value.message??value.code}\x1b[0m`);}else if(value.type==='exit'){status='Exited';terminal.writeln(`\r\n[exit ${value.exitCode??''}]`);void loadSessions();}state.appendActivity(`terminal · ${value.type}`);};
    current.onclose=event=>{if(socket!==current||token!==generation||disposed)return;socket=undefined;if(event.code===1000){status='Detached';return}status='Interrupted';if(retries<4)reconnectTimer=setTimeout(()=>connect(),Math.min(5000,400*2**retries++));};current.onerror=()=>{if(socket===current)status='Connection error';};
  }
  function resolveApproval(decision:'approve'|'deny'){send({type:'nested_approval_resolve',requestId:`approval-${++request}`,approvalId:approval,decision});approval='';}
  function resize(){if(!terminal||!fit)return;try{fit.fit();send({type:'resize',requestId:`resize-${++request}`,cols:terminal.cols,rows:terminal.rows});}catch{}}
  function openSession(session:Session){menu='';if(session.kind==='managed-process'){if(session.diagnosticSessionId)window.dispatchEvent(new CustomEvent('atlas:open-logs',{detail:{diagnosticId:session.diagnosticSessionId}}));return}target=session.deviceId?`device:${session.deviceId}`:target;sessionId=session.id;newSession=false;retries=0;connect(true);}
  function createSession(){menu='';if(counts.active>=5){createWarning=true;return}startNewSession();}
  function startNewSession(){createWarning=false;sessionId='';newSession=true;retries=0;connect(true);}
  function ask(kind:'rename'|'stop'|'archive',session:Session){menu='';dialog={kind,session};title=session.title??'';}
  async function perform(){if(!dialog)return;const {kind,session}=dialog;try{await api(`/api/fngk/sessions/${encodeURIComponent(session.id)}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:kind,profile:params.profile,title:kind==='rename'?title:undefined,confirm:kind!=='rename'})});state.appendActivity(`terminal ${kind} · ${session.title??session.id}`);dialog=undefined;await loadSessions();if(kind==='stop'&&session.id===sessionId){socket?.close();status='Terminated';}}catch(error){status=(error as Error).message;}}
  async function restore(session:Session){menu='';try{await api(`/api/fngk/sessions/${encodeURIComponent(session.id)}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'restore',profile:params.profile})});await loadSessions();}catch(error){status=(error as Error).message;}}
  function applyRequest(){if(!terminal||!params.requestId||params.requestId===lastRequest)return;lastRequest=params.requestId;const nextTarget=params.target??target,targetChanged=nextTarget!==target;target=nextTarget;if(params.session||params.newSession||targetChanged){sessionId=params.session??'';newSession=Boolean(params.newSession);retries=0;void bootstrap(Boolean(params.session||params.newSession));}}
  $: applyRequest();
  onMount(()=>{terminal=new Terminal({convertEol:true,cursorBlink:true,cursorStyle:'block',fontFamily:'JetBrains Mono, ui-monospace, monospace',fontSize:12,theme:{background:'#080b0f',foreground:'#d8e2ec',cursor:'#d3fa72',cursorAccent:'#080b0f',selectionBackground:'#334154'}});fit=new FitAddon();terminal.loadAddon(fit);terminal.open(host);fit.fit();terminal.focus();terminal.onData(data=>send({type:'input',requestId:`input-${++request}`,bodyBase64:encoded(data)}));const observer=new ResizeObserver(()=>requestAnimationFrame(resize));observer.observe(host);lastRequest=params.requestId??'';void bootstrap(Boolean(sessionId||newSession));return()=>{disposed=true;clearTimeout(reconnectTimer);generation++;observer.disconnect();socket?.close(1000);terminal.dispose();};});
</script>

<DocumentationHelp topicId="terminals" label="Terminal documentation"/>
<section class="panel terminal-panel">
  <header><div class="terminal-target"><strong>{sessions.find(item=>item.id===sessionId)?.title??(target||'No remote Device selected')}</strong>{#if sessionId}<small title={streamId}>{sessionId.slice(0,8)}</small>{/if}</div><span class:live={status.startsWith('Live')}>{status}</span><small class="terminal-counts">{counts.active} active · {counts.live} live · {counts.detached} detached</small><div>{#if approval}<button onclick={()=>resolveApproval('approve')}>Approve</button><button onclick={()=>resolveApproval('deny')}>Deny</button>{/if}<button title="Close terminal panel" onclick={()=>window.dispatchEvent(new CustomEvent('atlas:close-terminal',{detail:{panelId:params.panelId}}))}><X size={13}/></button></div></header>
  <div class="terminal-body"><div class="terminal" bind:this={host}></div><nav class="terminal-rail" aria-label="Terminal sessions"><div class="terminal-rail-heading"><span>SESSIONS</span><button class="new-session" title="New terminal session" aria-label="New terminal session" onclick={createSession}><Plus size={14}/></button></div><div class="terminal-session-list">
    {#each sessions as session}<div class="terminal-rail-item" style={`--session-color:${color(session.id)}`}><button class:active={session.id===sessionId} class:archived={Boolean(session.archivedAt)} class="session-select" title={`${session.title??'Terminal'} · ${session.status??'unknown'}`} onclick={()=>openSession(session)}><span class="session-glyph">{(session.title??session.deviceName??'T').slice(0,1).toUpperCase()}</span><span class="session-label"><b>{session.title??session.deviceName??`Terminal ${session.id.slice(0,6)}`}</b><small>{session.kind==='managed-process'?'managed · ':''}{session.status??(session.archivedAt?'archived':'available')}</small></span><i></i></button>{#if session.kind!=='managed-process'}<button class="session-more" aria-label={`Actions for ${session.title??'terminal'}`} title="Session actions" onclick={()=>menu=menu===session.id?'':session.id}><MoreVertical size={13}/></button>{/if}{#if menu===session.id}<div class="session-menu">{#if session.archivedAt}<button onclick={()=>restore(session)}><ArchiveRestore size={12}/>Restore</button>{:else}<button onclick={()=>ask('rename',session)}><Pencil size={12}/>Rename</button><button onclick={()=>{menu='';sessionId=session.id;newSession=false;retries=0;connect(true)}}><RotateCw size={12}/>Reconnect</button><button onclick={()=>ask('stop',session)}><Square size={12}/>Terminate</button><button onclick={()=>ask('archive',session)}><Archive size={12}/>Archive</button>{/if}</div>{/if}</div>{/each}
  </div></nav></div>
  {#if dialog}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true"><h2>{dialog.kind==='rename'?'Rename terminal':dialog.kind==='stop'?'Terminate terminal?':'Archive terminal?'}</h2>{#if dialog.kind==='rename'}<input bind:value={title} aria-label="Terminal title"/>{:else}<p>{dialog.session.title??dialog.session.id} will {dialog.kind==='stop'?'stop on the Device':'move to archived sessions'}.</p>{/if}<div><button onclick={()=>dialog=undefined}>Cancel</button><button class:danger={dialog.kind!=='rename'} onclick={perform}>{dialog.kind==='rename'?'Save':'Confirm'}</button></div></div></div>{/if}
  {#if createWarning}<div class="atlas-dialog-backdrop"><div class="atlas-dialog" role="dialog" aria-modal="true" aria-labelledby="terminal-limit-title"><h2 id="terminal-limit-title">Create another terminal?</h2><p>This Device already has {counts.active} active sessions. Existing detached sessions can be reattached from the rail.</p><div><button onclick={()=>createWarning=false}>Cancel</button><button onclick={startNewSession}>Create session</button></div></div></div>{/if}
</section>
