<script lang="ts">
  import {onMount} from 'svelte';
  import Search from '@lucide/svelte/icons/search';import X from '@lucide/svelte/icons/x';
  import {api} from '../lib/api.js';import type {AtlasCommandRegistry} from '../lib/command-registry.js';import {UnifiedSearchCollection,type UnifiedSearchItem,type UnifiedSearchProvider,type UnifiedSearchScope} from '../lib/unified-search.js';import type {WorkbenchState} from '../lib/workbench-state.js';
  export let state:WorkbenchState;export let commands:AtlasCommandRegistry;
  let input:HTMLInputElement,query='',scope:UnifiedSearchScope='context',type='all',items:UnifiedSearchItem[]=[],open=false,loading=false,error='',timer:any,active=0;
  const score=(rank:unknown,base=40)=>base-(Number(rank)||0);
  const indexed:UnifiedSearchProvider=async(request,signal)=>{const context=request.scope==='context'?`&contextId=${encodeURIComponent(request.contextId)}`:'';const value=await api<any>(`/api/search?q=${encodeURIComponent(request.query)}${context}&limit=100`,{signal});return (value.items??[]).map((item:any)=>({id:`${item.type}:${item.entityId}`,type:item.type,label:item.label??item.entityId,contextId:item.contextId,path:item.path,detail:item.detail,provenance:item.source??'atlas-index',score:score(item.rank,70)}))};
  const files:UnifiedSearchProvider=async(request,signal)=>{const value=await api<any>(`/api/files/search?contextId=${encodeURIComponent(request.contextId)}&path=%2F&query=${encodeURIComponent(request.query)}&mode=all&limit=100`,{signal});return (value.matches??[]).map((item:any)=>({id:`file:${request.contextId}:${item.path}:${item.line??0}`,type:'file',label:item.path.split('/').at(-1)??item.path,contextId:request.contextId,path:item.path,line:item.line,detail:item.preview,provenance:`live filesystem · ${value.route?.kind??'route'}`,score:item.line?65:55}))};
  const contexts:UnifiedSearchProvider=async(request,signal)=>{const value=await api<any>('/api/contexts',{signal}),wanted=request.query.toLocaleLowerCase();return (value.contexts??[]).filter((item:any)=>`${item.name} ${item.id} ${item.kind}`.toLocaleLowerCase().includes(wanted)).map((item:any)=>({id:`context:${item.id}`,type:'context',label:item.name,contextId:item.id,detail:`${item.kind} · ${item.online?'reachable':'offline'}`,provenance:'FNGK namespace',score:45}))};
  const sessions:UnifiedSearchProvider=async(request,signal)=>{if(!request.contextId.startsWith('device:'))return[];const value=await api<any>(`/api/fngk/sessions?deviceId=${encodeURIComponent(request.contextId.slice(7))}`,{signal}),wanted=request.query.toLocaleLowerCase();return (value.sessions??[]).filter((item:any)=>`${item.title??''} ${item.id} ${item.status??''}`.toLocaleLowerCase().includes(wanted)).map((item:any)=>({id:`terminal:${item.id}`,type:'terminal',label:item.title??`Terminal ${item.id.slice(0,8)}`,contextId:request.contextId,detail:item.status??'unknown',provenance:'FNGK terminal sessions',score:50,action:item.id}))};
  const commandProvider:UnifiedSearchProvider=async request=>commands.search(request.query).map(command=>({id:`command:${command.id}`,type:'command',label:command.label,detail:command.shortcut,provenance:'Atlas commands',score:80,action:command.id}));
  const collection=new UnifiedSearchCollection([commandProvider,indexed,files,contexts,sessions]);
  $: visible=type==='all'?items:items.filter(item=>item.type===type);
  function schedule(){clearTimeout(timer);open=Boolean(query.trim());if(!open){collection.cancel();items=[];return}timer=setTimeout(run,130)}
  async function run(){loading=true;error='';const result=await collection.search({query,contextId:state.snapshot().contextId,scope,limit:120});if(!result.stale){items=result.items;active=0;error=result.errors[0]??''}loading=false}
  async function choose(item:UnifiedSearchItem){open=false;if(item.type==='command'&&item.action){await commands.execute(item.action);return}if(item.type==='context'&&item.contextId){state.setContext(item.contextId);window.dispatchEvent(new CustomEvent('atlas:context',{detail:item.contextId}));return}if(item.type==='terminal'){window.dispatchEvent(new CustomEvent('atlas:open-terminal',{detail:{contextId:item.contextId,sessionId:item.action}}));return}if(item.path&&item.type==='file'){window.dispatchEvent(new CustomEvent('atlas:open-file',{detail:{contextId:item.contextId??state.snapshot().contextId,path:item.path,pinned:true,line:item.line}}));return}state.select({id:item.id.replace(/^[^:]+:/,''),type:item.type,contextId:item.contextId,path:item.path,line:item.line,label:item.label});window.dispatchEvent(new Event('atlas:graph-refresh'))}
  function keydown(event:KeyboardEvent){if(event.key==='Escape'){open=false;input.blur();return}if(!open)return;if(event.key==='ArrowDown'){event.preventDefault();active=Math.min(visible.length-1,active+1)}if(event.key==='ArrowUp'){event.preventDefault();active=Math.max(0,active-1)}if(event.key==='Enter'&&visible[active]){event.preventDefault();void choose(visible[active])}}
  function focus(event?:Event){const detail=(event as CustomEvent<{query?:string}>)?.detail;if(detail?.query!==undefined){query=detail.query;schedule()}open=Boolean(query.trim());input.focus();input.select()}
  onMount(()=>{window.addEventListener('atlas:focus-search',focus);window.addEventListener('atlas:search-query',focus);return()=>{clearTimeout(timer);collection.cancel();window.removeEventListener('atlas:focus-search',focus);window.removeEventListener('atlas:search-query',focus)}});
</script>
<div class="unified-search" class:open><div class="unified-search-box"><Search size={14}/><input bind:this={input} bind:value={query} oninput={schedule} onkeydown={keydown} onfocus={()=>open=Boolean(query.trim())} aria-label="Search Atlas" placeholder="Search files, symbols, commands, processes…"/><select bind:value={scope} onchange={schedule} aria-label="Search scope"><option value="context">This context</option><option value="all">All contexts</option></select>{#if query}<button aria-label="Clear search" title="Clear search" onclick={()=>{query='';items=[];open=false;input.focus()}}><X size={12}/></button>{/if}<kbd>⌘K</kbd></div>
{#if open}<section class="unified-search-popover"><header><span>ONE COLLECTION</span><label>Type<select bind:value={type}><option value="all">Everything</option>{#each [...new Set(items.map(item=>item.type))] as value}<option value={value}>{value}</option>{/each}</select></label></header><div role="listbox" aria-label="Unified search results">{#each visible as item,index}<button role="option" aria-selected={index===active} class:active={index===active} onclick={()=>choose(item)}><span class="result-type">{item.type}</span><b>{item.label}</b><small>{item.path}{item.line?`:${item.line}`:''}{item.detail?`${item.path?' · ':''}${item.detail}`:''}</small><em>{item.contextId??'global'} · {item.provenance}</em></button>{/each}{#if loading}<p>Searching Atlas and the live filesystem…</p>{:else if !visible.length}<p>{error||'No matching evidence in this scope.'}</p>{/if}</div></section>{/if}</div>
