<script lang="ts">
  import { onDestroy, onMount, mount, unmount } from 'svelte';
  import { createDockview, themeAbyssSpaced, type GroupPanelPartInitParameters, type IContentRenderer, type ITabRenderer, type TabPartInitParameters } from 'dockview';
  import { writable } from 'svelte/store';
  import {clampLowerPanelHeight,clampSidebarWidth,installWorkspaceSplitters} from '../lib/workspace-splitters.js';
  import {isPermanentPanel,isWorkspaceFallbackVisible,shellLayoutVersion} from '../lib/workbench-shell.js';
  import PanelHost from './PanelHost.svelte';
  import SaveAsDialog from './SaveAsDialog.svelte';
  import {PanelRegistry,type AtlasPanelDescriptor} from '../lib/panel-registry.js';
  import {atlasBuffers,type AtlasBuffer} from '../lib/buffer-store.js';
  import {readWorkspaceSnapshot,writeWorkspaceSnapshot,sanitizeWorkspaceLayout,type SafeWorkspaceSnapshot} from '../lib/workspace-persistence.js';
  import type { WorkbenchState } from '../lib/workbench-state.js';
  import type {WorkspaceRootsStore} from '../lib/workspace-roots.js';
  import {findDocumentationAction,findDocumentationTopic} from '../lib/documentation.js';
  import {deviceAppearanceStore} from '../lib/device-appearance.js';

  export let state: WorkbenchState;export let roots:WorkspaceRootsStore;
  let host: HTMLDivElement; let pendingClose: { api: any; title: string } | null = null; let empty = false;let minimized:AtlasPanelDescriptor[]=[];let saveAsBuffer:AtlasBuffer|undefined;let discardSaveAsBuffer='';let cancelSaveAs=()=>{saveAsBuffer=undefined;discardSaveAsBuffer=''};let removeDocumentationListeners=()=>{};onDestroy(()=>removeDocumentationListeners());
  const dirtyPanels = new Set<string>();
  const panelRegistry=new PanelRegistry();
  const retainedRenderers=new Map<string,Renderer>();
  const retaining=new Set<string>();

  class Renderer implements IContentRenderer {
    element=document.createElement('div'); component:any; params=writable<Record<string,unknown>>({});kind:string;id:string;
    constructor(kind:string,id:string){this.kind=kind;this.id=id;this.element.className='dock-panel-host';}
    init(parameters:GroupPanelPartInitParameters){if(this.component)return;this.params.set(parameters.params??{});this.component=mount(PanelHost,{target:this.element,props:{kind:this.kind,paramsStore:this.params,state}});}
    update(event:{params:Record<string,unknown>}){this.params.update(value=>({...value,...event.params}));}
    dispose(){if(retaining.has(this.id)){retainedRenderers.set(this.id,this);return;}if(this.component){void unmount(this.component);this.component=undefined;}retainedRenderers.delete(this.id);}
  }
  class AtlasTab implements ITabRenderer {
    element=document.createElement('div');title=document.createElement('span');minimize=document.createElement('button');close=document.createElement('button');subscriptions:{dispose():void}[]=[];panelId='';
    constructor(){this.element.className='atlas-file-tab atlas-tab';this.title.className='atlas-file-tab-title';this.minimize.className='atlas-tab-minimize';this.minimize.type='button';this.minimize.textContent='−';this.close.className='atlas-file-tab-close';this.close.type='button';this.close.textContent='×';this.element.append(this.title,this.minimize,this.close);}
    init(parameters:TabPartInitParameters){this.panelId=parameters.api.id;this.element.dataset.panelId=this.panelId;const sidebar=['atlas.devices','atlas.filesystem','atlas.inspector'].includes(this.panelId),workspace=this.panelId==='atlas.workspace',operations=this.panelId==='atlas.operations',collapsible=['atlas.device-details','atlas.inspector','atlas.operations'].includes(this.panelId),update=(title:string)=>{this.title.textContent=title;const action=sidebar?`Collapse ${title} sidebar`:collapsible?`Collapse ${title}`:operations?'Minimize Operations dock':`Minimize ${title}`;this.minimize.setAttribute('aria-label',action);this.minimize.title=action;this.close.setAttribute('aria-label',`Close ${title}`);this.close.title=`Close ${title}`},applyAppearance=(value:Record<string,unknown>)=>{const contextId=typeof value.contextId==='string'?value.contextId:typeof value.target==='string'?value.target:'';const deviceId=contextId.startsWith('device:')?contextId.slice('device:'.length):'';const color=deviceId?deviceAppearanceStore.get(deviceId).color:undefined;this.element.classList.toggle('preview',value.preview===true);this.element.classList.toggle('device-tinted',Boolean(color));if(color)this.element.style.setProperty('--atlas-device-color',`var(--atlas-device-${color})`);else this.element.style.removeProperty('--atlas-device-color');};update(parameters.title);applyAppearance(parameters.api.getParameters());if(sidebar||operations)this.close.remove();if(workspace){this.element.classList.add('atlas-workspace-anchor');this.minimize.remove();this.close.remove();}if(operations)this.element.classList.add('atlas-operations-anchor');const refreshAppearance=()=>applyAppearance(parameters.api.getParameters());window.addEventListener('atlas:device-appearance-changed',refreshAppearance);this.subscriptions.push(parameters.api.onDidTitleChange(event=>update(event.title)),parameters.api.onDidParametersChange(value=>applyAppearance(value)),{dispose:()=>window.removeEventListener('atlas:device-appearance-changed',refreshAppearance)});this.minimize.onclick=event=>{event.stopPropagation();window.dispatchEvent(sidebar?new CustomEvent('atlas:toggle-sidebar-collapse',{detail:{panelId:this.panelId}}):collapsible?new CustomEvent('atlas:toggle-panel-collapse',{detail:{panelId:this.panelId}}):operations?new Event('atlas:minimize-operations'):new CustomEvent('atlas:minimize-panel',{detail:{panelId:this.panelId}}))};this.close.onclick=event=>{event.stopPropagation();if(!dirtyPanels.has(this.panelId))parameters.api.close();else window.dispatchEvent(new CustomEvent('atlas:confirm-close',{detail:{api:parameters.api,title:parameters.title}}));};}
    dispose(){for(const subscription of this.subscriptions)subscription.dispose();}
  }

  onMount(()=>{
    let dock:ReturnType<typeof createDockview>;const minimizing=new Set<string>(),responsiveMinimized=new Set<string>(),responsiveCollapsed=new Set<'left'|'right'>();let narrowMode=false,constrainingLowerPanels=false;const sidebarWidths={left:clampSidebarWidth(undefined,host.clientWidth),right:clampSidebarWidth(undefined,host.clientWidth)};
    // The mounted workspace owns its scope. Selecting a Device does not replace live editors or terminals.
    const ownerScope={profile:state.snapshot().connection.profile??'default',contextId:state.snapshot().contextId};
    const workspaceScope=()=>ownerScope;
    const remember=(panel:any)=>panelRegistry.remember({id:panel.id,kind:panel.api.component,title:panel.title??panel.id,params:panel.api.getParameters()});
    const minimizePanel=(panel:any)=>{if(panel.id==='atlas.devices')sidebarWidths.left=Math.round((panel.api.group.api.boundingBox?.width??sidebarWidths.left)+4);if(panel.id==='atlas.filesystem')sidebarWidths.right=Math.round((panel.api.group.api.boundingBox?.width??sidebarWidths.right)+4);remember(panel);panelRegistry.minimize(panel.id);minimizing.add(panel.id);retaining.add(panel.id);dock.removePanel(panel);retaining.delete(panel.id);};
    dock=createDockview(host,{theme:{...themeAbyssSpaced,gap:6},createComponent:({name,id})=>{const existing=retainedRenderers.get(id);if(existing){retainedRenderers.delete(id);return existing;}return new Renderer(name,id);},defaultTabComponent:'atlas-tab',createTabComponent:()=>new AtlasTab(),getTabContextMenuItems:({panel}:any)=>{if(['atlas.workspace','atlas.operations'].includes(panel.id))return [];const sidebar=['atlas.devices','atlas.filesystem','atlas.inspector'].includes(panel.id);return [{label:'Minimize',action:()=>minimizePanel(panel)},'separator','float','maximize',...(sidebar?[]:['separator',...(dirtyPanels.has(panel.id)?[]:['close','closeOthers','closeAll'])])] as any}});
    const disposeSplitters=installWorkspaceSplitters(host,dock);
    localStorage.removeItem('atlas.workbench.v2');localStorage.removeItem('atlas.workbench.v3');localStorage.removeItem('atlas.workbench.v4');localStorage.removeItem('atlas.workbench.v5');localStorage.removeItem('atlas.workbench.v6');
    const scope=workspaceScope(),saved:SafeWorkspaceSnapshot|undefined=readWorkspaceSnapshot(localStorage,scope.profile,scope.contextId),collapsedPanels=new Set<string>(),collapsedSidebars=new Set<'left'|'right'>();let restored=false;
    if(saved)try{const value:any=saved.layout;if(value?.version===shellLayoutVersion&&value.layout){if(Number.isFinite(value.sidebarWidths?.left))sidebarWidths.left=clampSidebarWidth(value.sidebarWidths.left,host.clientWidth);if(Number.isFinite(value.sidebarWidths?.right))sidebarWidths.right=clampSidebarWidth(value.sidebarWidths.right,host.clientWidth);if(Array.isArray(value.collapsedPanels))for(const id of value.collapsedPanels)if(['atlas.device-details','atlas.inspector','atlas.operations'].includes(id))collapsedPanels.add(id);if(Array.isArray(value.sidebarCollapsed))for(const side of value.sidebarCollapsed)if(side==='left'||side==='right')collapsedSidebars.add(side);dock.fromJSON(value.layout);restored=Boolean(dock.getPanel('atlas.workspace'));if(!restored)dock.clear();}}catch{dock.clear();}
    const seed=()=>{
      const workspace=dock.getPanel('atlas.workspace')??dock.addPanel({id:'atlas.workspace',title:'Workspace',component:'workspace'});
      const navigator=dock.addPanel({id:'atlas.devices',title:'Devices',component:'devices',initialWidth:sidebarWidths.left,position:{referencePanel:workspace,direction:'left'}});
      dock.addPanel({id:'atlas.device-details',title:'Device details',component:'device-details',initialHeight:clampLowerPanelHeight(undefined,host.clientHeight),position:{referencePanel:navigator,direction:'below'}});
      const files=dock.addPanel({id:'atlas.filesystem',title:'Filesystem',component:'filesystem',initialWidth:sidebarWidths.right,position:{referencePanel:workspace,direction:'right'}});
      dock.addPanel({id:'atlas.inspector',title:'Inspector',component:'details',initialHeight:clampLowerPanelHeight(undefined,host.clientHeight),position:{referencePanel:files,direction:'below'}});
      workspace.api.setActive();
    };
    if(!restored){dock.clear();seed();}
    if(!localStorage.getItem('atlas.workspace-welcome.v1')){dock.getPanel('atlas.workspace')?.api.setActive();localStorage.setItem('atlas.workspace-welcome.v1','1');}
    for(const panel of [...dock.panels]){const params=panel.api.getParameters<{bufferId?:string}>();if(params.bufferId&&!atlasBuffers.get(params.bufferId)){dock.removePanel(panel);continue}remember(panel)}
    try{const legacy=JSON.parse(localStorage.getItem('atlas.minimized-panels.v1')??'[]'),descriptors=saved?.panels??[];if(Array.isArray(descriptors))for(const descriptor of descriptors){if(descriptor?.params?.bufferId&&!atlasBuffers.get(String(descriptor.params.bufferId)))continue;if(descriptor.minimized===false||dock.getPanel(descriptor.id))continue;if(typeof descriptor?.kind!=='string'||typeof descriptor?.title!=='string')continue;panelRegistry.remember(descriptor as AtlasPanelDescriptor);panelRegistry.minimize(descriptor.id)}}catch{}
    const syncWorkspace=()=>{const ordinary=dock.panels.filter(panel=>!isPermanentPanel(panel.id)&&!operational(panel.id,panel.api.component)).map(panel=>panel.id),workspace=dock.getPanel('atlas.workspace'),showWorkspace=isWorkspaceFallbackVisible(ordinary),workspaceTab=host.querySelector<HTMLElement>('[data-panel-id="atlas.workspace"]');if(workspaceTab)workspaceTab.style.display=showWorkspace?'':'none';if(workspace&&showWorkspace)workspace.api.setActive();for(const id of ['atlas.operations','atlas.devices','atlas.filesystem','atlas.device-details','atlas.inspector']){const anchor=dock.getPanel(id);if(!anchor)continue;const group=anchor.api.group,onlyAnchor=group.panels.length===1;group.header.hidden=onlyAnchor;group.relayout();}};
    const syncEmpty=()=>{empty=dock.panels.length===0;}; syncEmpty();syncWorkspace();
    const workspaceValue=()=>({version:shellLayoutVersion,layout:sanitizeWorkspaceLayout(dock.toJSON()),sidebarWidths,collapsedPanels:[...collapsedPanels],sidebarCollapsed:[...collapsedSidebars]});
    const persist=()=>{if(narrowMode)return;const left=dock.getPanel('atlas.devices'),right=dock.getPanel('atlas.filesystem');if(left&&right){if(!collapsedSidebars.has('left'))sidebarWidths.left=clampSidebarWidth((left.api.group.api.boundingBox?.width??sidebarWidths.left)+4,host.clientWidth);if(!collapsedSidebars.has('right'))sidebarWidths.right=clampSidebarWidth((right.api.group.api.boundingBox?.width??sidebarWidths.right)+4,host.clientWidth)}const value=workspaceValue();state.setLayout(value);const activeScope=workspaceScope();writeWorkspaceSnapshot(localStorage,activeScope.profile,activeScope.contextId,{version:1,layout:value,panels:panelRegistry.persistable()});};
    const updateMinimized=()=>{minimized=panelRegistry.all().filter(value=>value.minimized&&!responsiveMinimized.has(value.id));const activeScope=workspaceScope();writeWorkspaceSnapshot(localStorage,activeScope.profile,activeScope.contextId,{version:1,layout:workspaceValue(),panels:panelRegistry.persistable()});(host as any).__atlasMinimizedPanels=minimized;window.dispatchEvent(new CustomEvent('atlas:minimized-panels',{detail:minimized}))};updateMinimized();
    function operational(id:string,component?:string){return ['atlas.operations','atlas.terminal','atlas.metrics','atlas.activity','atlas.observability'].includes(id)||id.startsWith('atlas.terminal:')||component==='logs'||component==='terminal'||/^deployment:.+:(runs|logs|browser|history)$/.test(id)}
    const rightSidebar=(id:string)=>['atlas.filesystem','atlas.intelligence'].includes(id);
    const willDrop=dock.onWillDrop((event:any)=>{const panel=event.panel,target=event.group;if(!panel||!target)return;const ids=new Set<string>(target.panels.map((value:any)=>String(value.id))),component=panel.api.component;if(ids.has('atlas.devices')&&panel.id!=='atlas.devices')event.preventDefault();else if([...ids].some(rightSidebar)&&!rightSidebar(panel.id))event.preventDefault();else if(ids.has('atlas.inspector')&&panel.id!=='atlas.inspector')event.preventDefault();else if(ids.has('atlas.operations')&&!operational(panel.id,component))event.preventDefault();else if(operational(panel.id,component)&&!ids.has('atlas.operations'))event.preventDefault();else if((panel.id==='atlas.devices'||rightSidebar(panel.id)||panel.id==='atlas.inspector')&&!ids.has(panel.id)&&!(rightSidebar(panel.id)&&[...ids].some(rightSidebar)))event.preventDefault();});
    const constrainLowerPanels=()=>{if(constrainingLowerPanels)return;for(const id of ['atlas.device-details','atlas.inspector']){const panel=dock.getPanel(id),height=panel?.api.group.api.boundingBox?.height;if(!panel||!height)continue;if(height<=36)continue;const clamped=clampLowerPanelHeight(height,host.clientHeight);if(Math.abs(clamped-height)<2)continue;constrainingLowerPanels=true;panel.api.group.api.setSize({height:clamped});queueMicrotask(()=>constrainingLowerPanels=false);}};
    const layout=dock.onDidLayoutChange(()=>{constrainLowerPanels();persist()}),added=dock.onDidAddPanel(()=>queueMicrotask(syncWorkspace)),removed=dock.onDidRemovePanel((panel:any)=>{const wasMinimized=minimizing.delete(panel.id),params=panel.api.getParameters() as {bufferId?:string};if(!wasMinimized){dirtyPanels.delete(panel.id);panelRegistry.forget(panel.id);if(params.bufferId)atlasBuffers.remove(params.bufferId)}if(panel.id==='atlas.devices'&&dock.panels.length>0&&!wasMinimized){const reference=dock.getPanel('atlas.workspace')??dock.panels[0];const added=dock.addPanel({id:'atlas.devices',title:'Devices',component:'devices',position:reference?{referencePanel:reference,direction:'left'}:undefined});remember(added);}updateMinimized();syncEmpty();queueMicrotask(syncWorkspace);persist();});
    const restorePanel=(id:string)=>{const descriptor=panelRegistry.restore(id);if(!descriptor)return;let panel=dock.getPanel(id);if(!panel){const sidebar=id==='atlas.devices'?'left':rightSidebar(id)?'right':undefined,isOperational=operational(id,descriptor.kind),reference=id==='atlas.intelligence'?(dock.getPanel('atlas.filesystem')??dock.getPanel('atlas.workspace')!):sidebar?dock.getPanel('atlas.workspace')??dock.panels[0]:isOperational?ensureOperations():dock.getPanel('atlas.workspace')??dock.panels[0];panel=dock.addPanel({id:descriptor.id,title:descriptor.title,component:descriptor.kind,tabComponent:descriptor.kind==='file'?'guarded-file':undefined,params:descriptor.params,renderer:['file','terminal','agent-chat'].includes(descriptor.kind)?'always':undefined,initialWidth:sidebar?sidebarWidths[sidebar]:undefined,position:reference?{referencePanel:reference,...(sidebar&&id!=='atlas.intelligence'?{direction:sidebar}:{})}:undefined});}panel.api.setActive();updateMinimized();syncEmpty();};
    const adaptNarrowLayout=()=>{const narrow=window.innerWidth<=700;if(narrow===narrowMode)return;if(narrow){narrowMode=true;for(const side of ['left','right'] as const){if(collapsedSidebars.has(side))continue;const panel=dock.getPanel(side==='left'?'atlas.devices':'atlas.filesystem');if(!panel)continue;responsiveCollapsed.add(side);collapsedSidebars.add(side);panel.api.group.api.setSize({width:36});}return}narrowMode=false;for(const side of responsiveCollapsed){collapsedSidebars.delete(side);dock.getPanel(side==='left'?'atlas.devices':'atlas.filesystem')?.api.group.api.setSize({width:sidebarWidths[side]});}responsiveCollapsed.clear();updateMinimized();persist()};
    const forgetPanel=(id:string)=>{if(dirtyPanels.has(id)){restorePanel(id);return;}retainedRenderers.get(id)?.dispose();panelRegistry.forget(id);updateMinimized()};
    (host as any).__atlasHasDirty=()=>dirtyPanels.size>0||atlasBuffers.hasDirty();(host as any).__atlasRestorePanel=restorePanel;(host as any).__atlasForgetPanel=forgetPanel;
    const filePanels=new Map<string,string>();let previewId:string|undefined,previewResource='';
    for(const panel of dock.panels){const params=panel.api.getParameters<{contextId?:string;path?:string}>();if(panel.api.component==='file'&&params.contextId&&params.path)filePanels.set(`${params.contextId}:${params.path}`,panel.id);}
    const openFile=(event:Event)=>{const resource=(event as CustomEvent<{contextId:string;path:string;pinned?:boolean;line?:number}>).detail,key=`${resource.contextId}:${resource.path}`,mapped=filePanels.get(key);if(mapped){if(panelRegistry.get(mapped)?.minimized)restorePanel(mapped);const panel=dock.getPanel(mapped);if(panel){if(resource.pinned){panel.api.updateParameters({...panel.api.getParameters(),pinned:true,preview:false});if(mapped===previewId){previewId=undefined;previewResource='';}}panel.api.setActive();window.dispatchEvent(new CustomEvent('atlas:file-reveal',{detail:{panelId:mapped,line:resource.line}}));return;}filePanels.delete(key);}if(!resource.pinned&&previewId){const current=dock.getPanel(previewId);if(current&&!dirtyPanels.has(previewId)){filePanels.delete(previewResource);current.api.updateParameters({...resource,panelId:previewId,preview:true});previewResource=key;filePanels.set(key,previewId);current.api.setTitle(resource.path.split('/').at(-1)??resource.path);current.api.setActive();return;}}const id=resource.pinned?`file:${key}`:`file:preview:${crypto.randomUUID()}`;if(!resource.pinned){previewId=id;previewResource=key;}filePanels.set(key,id);dock.addPanel({id,title:resource.path.split('/').at(-1)??resource.path,component:'file',tabComponent:'guarded-file',params:{...resource,panelId:id,preview:!resource.pinned},renderer:'always',position:{referencePanel:ensureBase()}});};
    const newBuffer=(event?:Event)=>{const detail=(event as CustomEvent<{contextId?:string;content?:string;suggestedDirectory?:string;proposedPath?:string;openSaveAs?:boolean;discardOnCancel?:boolean}>)?.detail??{},buffer=atlasBuffers.create({contextId:detail.contextId??state.snapshot().contextId,content:detail.content,suggestedDirectory:detail.suggestedDirectory,proposedPath:detail.proposedPath}),id=`buffer:${buffer.id}`,reference=ensureBase();const panel=dock.addPanel({id,title:buffer.name,component:'file',tabComponent:'guarded-file',params:{contextId:buffer.contextId,bufferId:buffer.id,panelId:id},renderer:'always',position:{referencePanel:reference}});remember(panel);panel.api.setActive();if(detail.openSaveAs){saveAsBuffer=buffer;discardSaveAsBuffer=detail.discardOnCancel?buffer.id:''}};
    const requestSaveBuffer=(event:Event)=>{const id=(event as CustomEvent<{bufferId:string}>).detail?.bufferId,buffer=id?atlasBuffers.get(id):undefined;if(buffer)saveAsBuffer=buffer;};
    const bufferSaved=(event:Event)=>{const detail=(event as CustomEvent<{bufferId?:string;panelId?:string;contextId:string;path:string}>).detail;if(detail.panelId){const panel=dock.getPanel(detail.panelId);if(panel){panel.api.updateParameters({...panel.api.getParameters(),preview:false});panel.api.setTitle(detail.path.split('/').at(-1)??detail.path)}dirtyPanels.delete(detail.panelId)}if(saveAsBuffer?.id===detail.bufferId){saveAsBuffer=undefined;discardSaveAsBuffer=''}window.dispatchEvent(new CustomEvent('atlas:filesystem-reveal',{detail:{contextId:detail.contextId,path:detail.path}}));};
    const dirtyFile=(event:Event)=>{const detail=(event as CustomEvent<{panelId?:string;dirty:boolean}>).detail,id=detail.panelId;if(!id)return;const panel=dock.getPanel(id);if(detail.dirty){dirtyPanels.add(id);if(id===previewId){previewId=undefined;previewResource='';}if(panel){panel.api.updateParameters({...panel.api.getParameters(),preview:false});if(!panel.title?.endsWith(' ●'))panel.api.setTitle((panel.title??'File')+' ●')}}else{dirtyPanels.delete(id);if(panel)panel.api.setTitle((panel.title??'File').replace(/ ●$/,''));}};
    const ensureBase=()=>{if(!dock.getPanel('atlas.workspace')){dock.clear();seed();}return dock.getPanel('atlas.workspace')!;};
    const ensureOperations=()=>{ensureBase();return dock.getPanel('atlas.operations')??dock.addPanel({id:'atlas.operations',title:'Operations',component:'operations',position:{referencePanel:ensureBase(),direction:'below'},initialHeight:300})};
    const openOperations=()=>{let panel=dock.getPanel('atlas.activity');if(!panel)panel=dock.addPanel({id:'atlas.activity',title:'Activity & runs',component:'output',position:{referencePanel:ensureOperations()}});panel.api.setActive();panel.api.group.api.setSize({height:300});};
    const openMetrics=()=>{let panel=dock.getPanel('atlas.metrics');if(!panel)panel=dock.addPanel({id:'atlas.metrics',title:'Functions & coverage',component:'metrics',position:{referencePanel:ensureOperations()}});panel.api.setActive();panel.api.group.api.setSize({height:300});};
    const openObservability=()=>{let panel=dock.getPanel('atlas.observability');if(!panel)panel=dock.addPanel({id:'atlas.observability',title:'Observability',component:'observability',position:{referencePanel:ensureOperations()}});panel.api.setActive();panel.api.group.api.setSize({height:300});};
    const openPorts=(event?:Event)=>{const contextId=(event as CustomEvent<{contextId?:string}>)?.detail?.contextId??state.snapshot().contextId;let panel=dock.getPanel('atlas.ports');if(!panel)panel=dock.addPanel({id:'atlas.ports',title:'HTTP ports',component:'port-sharing',renderer:'always',params:{contextId},position:{referencePanel:dock.getPanel('atlas.observatory')??ensureBase()}});else panel.api.updateParameters({contextId});panel.api.setActive();};
    const openHandoff=(event?:Event)=>{const targetContextId=(event as CustomEvent<{contextId?:string}>)?.detail?.contextId??state.snapshot().contextId,id='atlas.fngk-handoff';let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Install FNGK head',component:'fngk-handoff',renderer:'always',params:{targetContextId},position:{referencePanel:ensureBase()}});else panel.api.updateParameters({targetContextId});panel.api.setActive();};
    const openDeviceLifecycle=()=>{const contextId=state.snapshot().contextId,id='atlas.device-lifecycle';let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Device lifecycle',component:'device-lifecycle',renderer:'always',params:{contextId},position:{referencePanel:dock.getPanel('atlas.observatory')??ensureBase()}});else panel.api.updateParameters({contextId});panel.api.setActive();};
    const openDeviceSessions=()=>{const id='atlas.device-sessions';if(panelRegistry.get(id)?.minimized)restorePanel(id);let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Device Sessions',component:'device-sessions',renderer:'always',position:{referencePanel:ensureBase()}});panel.api.setActive();syncEmpty();};
    const openAgentChat=()=>{const id='atlas.agent-chat';if(panelRegistry.get(id)?.minimized)restorePanel(id);let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Agent Chat',component:'agent-chat',renderer:'always',position:{referencePanel:ensureBase()}});panel.api.setActive();syncEmpty();};
    const openAppConnections=()=>{const id='atlas.app-connections';if(panelRegistry.get(id)?.minimized)restorePanel(id);let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'App connections',component:'app-connections',position:{referencePanel:ensureBase()}});panel.api.setActive();syncEmpty();};
    const openDeviceAtlas=()=>{let panel=dock.getPanel('atlas.observatory');if(!panel)panel=dock.addPanel({id:'atlas.observatory',title:'Device Atlas',component:'atlas',position:{referencePanel:ensureBase()}});panel.api.setActive();};
    const openDocumentation=(event?:Event)=>{const requested=(event as CustomEvent<{topicId?:string}>)?.detail?.topicId,topic=requested?findDocumentationTopic(requested):undefined;const id='atlas.documentation';if(panelRegistry.get(id)?.minimized)restorePanel(id);let panel=dock.getPanel(id);if(!panel){panel=dock.addPanel({id,title:'Documentation',component:'documentation',params:{topicId:requested??topic?.id},position:{referencePanel:ensureBase()}});remember(panel)}else panel.api.updateParameters({topicId:requested??topic?.id});panel.api.setActive();syncEmpty();};
    const openDocumentationAction=(event:Event)=>{const detail=(event as CustomEvent<{topicId?:string;action?:{event?:string}}>).detail,action=findDocumentationAction(detail?.topicId,detail?.action?.event);if(!action)return;window.dispatchEvent(new CustomEvent(action.event,{detail:action.detail}));};
    const openTerminal=(event?:Event)=>{const resource=(event as CustomEvent<{contextId?:string;target?:string;title?:string;newSession?:boolean;create?:boolean}>)?.detail??{},selected=resource.contextId??state.snapshot().contextId,target=resource.target??(selected.startsWith('device:')?selected:''),id=resource.create||resource.newSession?`atlas.terminal:${crypto.randomUUID()}`:'atlas.terminal';if(panelRegistry.get(id)?.minimized)restorePanel(id);let panel=dock.getPanel(id);const request={target,profile:state.snapshot().connection.profile,requestId:crypto.randomUUID(),panelId:id};if(!panel)panel=dock.addPanel({id,title:resource.title??'Terminal',component:'terminal',renderer:'always',params:request,position:{referencePanel:ensureOperations()}});else if(target!==panel.api.getParameters<{target?:string}>().target)panel.api.updateParameters(request);panel.api.setActive();syncEmpty();};
    const closeTerminal=(event:Event)=>{const id=(event as CustomEvent<{panelId?:string}>).detail?.panelId;if(id)dock.getPanel(id)?.api.close();};
    const openDatabase=(event:Event)=>{const contextId=(event as CustomEvent<{contextId?:string}>).detail?.contextId??state.snapshot().contextId,id=`database:${contextId}`;let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Databases',component:'database',renderer:'always',params:{contextId},position:{referencePanel:ensureBase()}});panel.api.setActive();};
    const openLiveProject=(event:Event)=>{const detail=(event as CustomEvent<{contextId?:string;repositoryPath?:string}>).detail??{},contextId=detail.contextId??state.snapshot().contextId,id=`live-project:${contextId}`;let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Live project',component:'live-project',renderer:'always',params:{contextId,repositoryPath:detail.repositoryPath},position:{referencePanel:dock.getPanel('atlas.observatory')??ensureBase()}});panel.api.setActive();};
    const openDeployment=(event:Event)=>{const detail=(event as CustomEvent<{contextId?:string;repositoryPath?:string}>).detail??{},contextId=detail.contextId??state.snapshot().contextId,id=`deployment:${contextId}:journey`;let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Deployment journey',component:'deployment',renderer:'always',params:{contextId,repositoryPath:detail.repositoryPath,view:'journey'},position:{referencePanel:dock.getPanel('atlas.observatory')??ensureBase()}});panel.api.setActive();syncEmpty();};
    const openIntelligence=()=>{const id='atlas.intelligence';let panel=dock.getPanel(id);focusFiles();if(!panel)panel=dock.addPanel({id,title:'Intelligence',component:'intelligence',renderer:'always',position:{referencePanel:dock.getPanel('atlas.filesystem')!}});panel.api.setActive();};
    const openLogs=(event:Event)=>{const detail=(event as CustomEvent<{diagnosticId?:string}>).detail;if(!detail?.diagnosticId)return;const id=`logs:${detail.diagnosticId}`;let panel=dock.getPanel(id);if(!panel)panel=dock.addPanel({id,title:'Logs',component:'logs',renderer:'always',params:{diagnosticId:detail.diagnosticId},position:{referencePanel:ensureOperations()}});panel.api.setActive();};
    const sidebarForPanel=(id:string):'left'|'right'|undefined=>id==='atlas.devices'?'left':['atlas.filesystem','atlas.inspector'].includes(id)?'right':undefined;
    const toggleSidebarCollapse=(event:Event)=>{const id=(event as CustomEvent<{panelId?:string}>).detail?.panelId,side=id?sidebarForPanel(id):undefined;if(!side)return;const panel=dock.getPanel(side==='left'?'atlas.devices':'atlas.filesystem');if(!panel)return;if(collapsedSidebars.has(side)){collapsedSidebars.delete(side);panel.api.group.api.setSize({width:sidebarWidths[side]});}else{const width=panel.api.group.api.boundingBox?.width??sidebarWidths[side];if(width>48)sidebarWidths[side]=clampSidebarWidth(width,host.clientWidth);collapsedSidebars.add(side);panel.api.group.api.setSize({width:36});}persist();};
    const expandSidebar=(side:'left'|'right')=>{if(!collapsedSidebars.delete(side))return;const panel=dock.getPanel(side==='left'?'atlas.devices':'atlas.filesystem');panel?.api.group.api.setSize({width:sidebarWidths[side]});persist();};
    const focusFiles=()=>{ensureBase();expandSidebar('right');if(panelRegistry.get('atlas.filesystem')?.minimized)restorePanel('atlas.filesystem');let panel=dock.getPanel('atlas.filesystem');if(!panel)panel=dock.addPanel({id:'atlas.filesystem',title:'Filesystem',component:'filesystem',initialWidth:sidebarWidths.right,position:{referencePanel:ensureBase(),direction:'right'}});panel.api.setActive();syncEmpty();};
    const openRoot=(event:Event)=>{const detail=(event as CustomEvent<{contextId?:string;path?:string}>).detail,contextId=detail?.contextId??state.snapshot().contextId,path=detail?.path;if(!path)return;state.setContext(contextId);focusFiles();queueMicrotask(()=>window.dispatchEvent(new CustomEvent('atlas:filesystem-root',{detail:{contextId,path}})));};
    const focusNavigator=()=>{ensureBase();expandSidebar('left');if(panelRegistry.get('atlas.devices')?.minimized)restorePanel('atlas.devices');let panel=dock.getPanel('atlas.devices');if(!panel)panel=dock.addPanel({id:'atlas.devices',title:'Devices',component:'devices',initialWidth:sidebarWidths.left,position:{referencePanel:ensureBase(),direction:'left'}});panel.api.setActive();syncEmpty()};
    const minimizeRequested=(event:Event)=>{const id=(event as CustomEvent<{panelId?:string}>).detail?.panelId,panel=id?dock.getPanel(id):undefined;if(panel)minimizePanel(panel)};
    const togglePanelCollapse=(event:Event)=>{const id=(event as CustomEvent<{panelId?:string}>).detail?.panelId;if(!id||!['atlas.device-details','atlas.inspector','atlas.operations'].includes(id))return;const panel=dock.getPanel(id),height=panel?.api.group.api.boundingBox?.height;if(!panel||!height)return;const collapsed=height<=36;if(collapsed)collapsedPanels.delete(id);else collapsedPanels.add(id);panel.api.group.api.setSize({height:collapsed?clampLowerPanelHeight(undefined,host.clientHeight):32});persist();};
    const minimizeOperations=()=>{const anchor=dock.getPanel('atlas.operations');if(!anchor)return;for(const panel of [...anchor.api.group.panels])minimizePanel(panel);updateMinimized();syncEmpty();persist()};
    const confirm=(event:Event)=>pendingClose=(event as CustomEvent<any>).detail;
    const unload=(event:BeforeUnloadEvent)=>{if(dirtyPanels.size||atlasBuffers.hasDirty())event.preventDefault();};
    window.addEventListener('atlas:open-logs',openLogs);
    window.addEventListener('atlas:open-intelligence',openIntelligence);
    window.addEventListener('atlas:open-documentation',openDocumentation);window.addEventListener('atlas:open-documentation-action',openDocumentationAction);removeDocumentationListeners=()=>{window.removeEventListener('atlas:open-documentation',openDocumentation);window.removeEventListener('atlas:open-documentation-action',openDocumentationAction)};
    window.addEventListener('atlas:open-operations',openOperations);window.addEventListener('atlas:minimize-operations',minimizeOperations);window.addEventListener('atlas:toggle-panel-collapse',togglePanelCollapse);window.addEventListener('atlas:toggle-sidebar-collapse',toggleSidebarCollapse);window.addEventListener('atlas:focus-metrics',openMetrics);window.addEventListener('atlas:open-observability',openObservability);window.addEventListener('atlas:open-ports',openPorts);window.addEventListener('atlas:open-fngk-handoff',openHandoff);window.addEventListener('atlas:open-device-lifecycle',openDeviceLifecycle);window.addEventListener('atlas:open-device-sessions',openDeviceSessions);window.addEventListener('atlas:open-agent-chat',openAgentChat);window.addEventListener('atlas:open-app-connections',openAppConnections);window.addEventListener('atlas:open-device-atlas',openDeviceAtlas);
    cancelSaveAs=()=>{const bufferId=discardSaveAsBuffer;saveAsBuffer=undefined;discardSaveAsBuffer='';if(!bufferId)return;const panelId=`buffer:${bufferId}`;dirtyPanels.delete(panelId);const panel=dock.getPanel(panelId);if(panel)panel.api.close();else atlasBuffers.remove(bufferId)};window.addEventListener('atlas:open-file',openFile);window.addEventListener('atlas:new-buffer',newBuffer);window.addEventListener('atlas:save-buffer',requestSaveBuffer);window.addEventListener('atlas:buffer-saved',bufferSaved);window.addEventListener('atlas:file-dirty',dirtyFile);window.addEventListener('atlas:open-terminal',openTerminal);window.addEventListener('atlas:close-terminal',closeTerminal);window.addEventListener('atlas:open-database',openDatabase);window.addEventListener('atlas:open-live-project',openLiveProject);window.addEventListener('atlas:open-deployment',openDeployment);window.addEventListener('atlas:focus-files',focusFiles);window.addEventListener('atlas:open-root',openRoot);window.addEventListener('atlas:context',focusNavigator);window.addEventListener('atlas:minimize-panel',minimizeRequested);window.addEventListener('atlas:confirm-close',confirm);window.addEventListener('beforeunload',unload);window.addEventListener('resize',adaptNarrowLayout);setTimeout(adaptNarrowLayout,80);
    requestAnimationFrame(()=>{sidebarWidths.left=clampSidebarWidth(sidebarWidths.left,host.clientWidth);sidebarWidths.right=clampSidebarWidth(sidebarWidths.right,host.clientWidth);dock.layout(host.clientWidth,host.clientHeight);if(!restored){dock.getPanel('atlas.devices')?.api.group.api.setSize({width:sidebarWidths.left});dock.getPanel('atlas.filesystem')?.api.group.api.setSize({width:sidebarWidths.right})}for(const side of collapsedSidebars)dock.getPanel(side==='left'?'atlas.devices':'atlas.filesystem')?.api.group.api.setSize({width:36});for(const id of collapsedPanels)dock.getPanel(id)?.api.group.api.setSize({height:32});host.dataset.layoutReady='true';persist()});
    return()=>{disposeSplitters();window.removeEventListener('atlas:open-logs',openLogs);window.removeEventListener('atlas:open-intelligence',openIntelligence);window.removeEventListener('atlas:open-operations',openOperations);window.removeEventListener('atlas:minimize-operations',minimizeOperations);window.removeEventListener('atlas:toggle-panel-collapse',togglePanelCollapse);window.removeEventListener('atlas:toggle-sidebar-collapse',toggleSidebarCollapse);window.removeEventListener('atlas:focus-metrics',openMetrics);window.removeEventListener('atlas:open-observability',openObservability);window.removeEventListener('atlas:open-ports',openPorts);window.removeEventListener('atlas:open-fngk-handoff',openHandoff);window.removeEventListener('atlas:open-device-atlas',openDeviceAtlas);window.removeEventListener('atlas:open-device-lifecycle',openDeviceLifecycle);window.removeEventListener('atlas:open-device-sessions',openDeviceSessions);window.removeEventListener('atlas:open-agent-chat',openAgentChat);window.removeEventListener('atlas:open-app-connections',openAppConnections);window.removeEventListener('atlas:open-file',openFile);window.removeEventListener('atlas:new-buffer',newBuffer);window.removeEventListener('atlas:save-buffer',requestSaveBuffer);window.removeEventListener('atlas:buffer-saved',bufferSaved);window.removeEventListener('atlas:file-dirty',dirtyFile);window.removeEventListener('atlas:open-terminal',openTerminal);window.removeEventListener('atlas:close-terminal',closeTerminal);window.removeEventListener('atlas:open-database',openDatabase);window.removeEventListener('atlas:open-live-project',openLiveProject);window.removeEventListener('atlas:open-deployment',openDeployment);window.removeEventListener('atlas:focus-files',focusFiles);window.removeEventListener('atlas:open-root',openRoot);window.removeEventListener('atlas:context',focusNavigator);window.removeEventListener('atlas:minimize-panel',minimizeRequested);window.removeEventListener('atlas:confirm-close',confirm);window.removeEventListener('beforeunload',unload);window.removeEventListener('resize',adaptNarrowLayout);willDrop.dispose();layout.dispose();added.dispose();removed.dispose();dock.dispose();for(const renderer of [...retainedRenderers.values()])renderer.dispose();};
  });
</script>

<div class="workbench">
  <div class="root-dock atlas-dock" bind:this={host}></div>
  {#if empty}<section class="dock-empty-recovery" aria-label="Restore Atlas panels"><strong>Atlas workspace is empty</strong><p>Restore a panel to continue working.</p><div><button onclick={()=>window.dispatchEvent(new Event('atlas:focus-search'))}>Search</button><button onclick={()=>window.dispatchEvent(new Event('atlas:focus-files'))}>Filesystem</button><button onclick={()=>window.dispatchEvent(new Event('atlas:open-terminal'))}>Terminal</button><button onclick={()=>window.dispatchEvent(new Event('atlas:shortcuts'))}>Command palette</button></div></section>{/if}
  {#if saveAsBuffer}<SaveAsDialog buffer={saveAsBuffer} roots={roots.forContext(saveAsBuffer.contextId)} oncancel={cancelSaveAs} onsave={(path)=>window.dispatchEvent(new CustomEvent('atlas:save-buffer-as',{detail:{bufferId:saveAsBuffer!.id,path}}))}/>{/if}
  {#if pendingClose}<div class="atlas-dialog-backdrop" role="presentation"><div class="atlas-dialog" role="dialog" aria-modal="true" aria-labelledby="close-title"><h2 id="close-title">Discard changes?</h2><p>{pendingClose.title} has unsaved changes.</p><div><button onclick={()=>pendingClose=null}>Keep editing</button><button class="danger" onclick={()=>{const panel=pendingClose!;pendingClose=null;dirtyPanels.delete(panel.api.id);panel.api.close();}}>Discard</button></div></div></div>{/if}
</div>
<style>
  .workbench{position:relative}.dock-empty-recovery{position:absolute;inset:0;display:grid;place-content:center;justify-items:center;gap:8px;background:#080b0f;color:#dbe5ee;text-align:center}.dock-empty-recovery strong{font-size:16px}.dock-empty-recovery p{margin:0;color:#8996a5;font-size:12px}.dock-empty-recovery div{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}.dock-empty-recovery button{padding:7px 11px;font-size:11px}
</style>
