import {randomUUID} from 'node:crypto';
import type {CommandExecutor} from '../transports/terminal-command.js';
import {FngkProcessClient} from '../fngk/process-client.js';
import type {DiagnosticRegistry} from '../diagnostics/registry.js';
import {PortDiscoveryService} from './discovery.js';
import {PortShareStore} from './store.js';
import type {PublishedPort} from './types.js';

type ExecuteResult={output:Buffer;exitCode:number};
export class PortSharingService{
  readonly discovery:PortDiscoveryService;
  #expiryTimers=new Map<string,NodeJS.Timeout>();
  constructor(readonly store:PortShareStore,readonly fngk:FngkProcessClient,readonly options:{executorFor:(contextId:string)=>Promise<CommandExecutor>;diagnostics:DiagnosticRegistry}){this.discovery=new PortDiscoveryService(options.executorFor);for(const value of store.activePublished())this.#scheduleExpiry(value)}
  async scan(contextId:string,signal?:AbortSignal){const result=await this.discovery.scan(contextId,signal);this.store.upsertCandidates(contextId,result.candidates);for(const old of this.store.candidates(contextId).filter(v=>v.stale))this.store.markStale(old.id);return{...result,candidates:this.store.candidates(contextId),published:this.store.published(contextId)}}
  list(contextId:string){this.store.expire();return{contextId,candidates:this.store.candidates(contextId),published:this.store.published(contextId)}}
  async #execute(contextId:string,action:'publish'|'unpublish',port:number,signal?:AbortSignal):Promise<ExecuteResult>{if(contextId==='local'){const result=action==='publish'?await this.fngk.publishPort(port,{signal}):await this.fngk.unpublishPort(port,{signal});return{output:Buffer.from(JSON.stringify(result)),exitCode:0}}return(await this.options.executorFor(contextId)).execute(`fngk ${action} ${port} --json`,{timeoutMs:30_000,signal})}
  async publish(candidateId:string,input:{confirm?:boolean;expiresInMs?:number;signal?:AbortSignal}):Promise<PublishedPort>{
    if(input.confirm!==true)throw Object.assign(new Error('Publishing an HTTP listener requires confirmation.'),{code:'confirmation_required'});const candidate=this.store.getCandidate(candidateId);if(!candidate)throw Object.assign(new Error('Port candidate was not found.'),{code:'candidate_not_found'});const existing=this.store.publishedForCandidate(candidateId);if(existing?.status==='published')return existing;const refreshed=await this.scan(candidate.contextId,input.signal),current=refreshed.candidates.find(value=>value.id===candidateId&&!value.stale);if(!current)throw Object.assign(new Error('The listener changed or disappeared since it was scanned.'),{code:'candidate_stale'});if(current.probe!=='http')throw Object.assign(new Error('Only a verified HTTP listener can be published.'),{code:'port_not_http'});
    const diagnostic=this.options.diagnostics.create({kind:'port-sharing',contextId:candidate.contextId,command:`fngk publish ${candidate.port} --json`,metadata:{candidateId,port:candidate.port}});this.options.diagnostics.update(diagnostic.id,{status:'running'});
    try{const result=await this.#execute(candidate.contextId,'publish',candidate.port,input.signal),text=result.output.toString('utf8').trim();this.options.diagnostics.append(diagnostic.id,'stdout',text);if(result.exitCode!==0)throw Object.assign(new Error(`FNGK publish exited with code ${result.exitCode}.`),{code:'publish_failed'});let value:any;try{value=JSON.parse(text)}catch{if(/Public route:|Connection:/i.test(text))throw Object.assign(new Error('The installed FNGK predates fngk.publish.v1. Install exact head and converge its daemon.'),{code:'fngk_incompatible'});throw Object.assign(new Error('FNGK returned malformed publish output.'),{code:'publish_protocol_invalid'})}if(value.protocolVersion!=='fngk.publish.v1'||value.type!=='published'||!value.connectionId||!value.hostname)throw Object.assign(new Error('FNGK returned an unsupported publish protocol.'),{code:'publish_protocol_invalid'});let publicUrl:URL;try{publicUrl=new URL(String(value.url||`https://${value.hostname}`))}catch{throw Object.assign(new Error('FNGK returned an invalid public route URL.'),{code:'publish_protocol_invalid'})}if(publicUrl.username||publicUrl.password||!['http:','https:'].includes(publicUrl.protocol))throw Object.assign(new Error('FNGK returned an unsafe public route URL.'),{code:'publish_protocol_invalid'});const now=new Date(),ttl=input.expiresInMs===undefined?undefined:Math.min(86_400_000,Math.max(60_000,Number(input.expiresInMs))),published:PublishedPort={id:existing?.id??randomUUID(),candidateId,contextId:candidate.contextId,port:candidate.port,connectionId:String(value.connectionId),hostname:String(value.hostname).slice(0,253),url:publicUrl.toString().slice(0,2048),publishedAt:now.toISOString(),expiresAt:ttl?new Date(now.getTime()+ttl).toISOString():undefined,status:'published',diagnosticSessionId:diagnostic.id};this.options.diagnostics.update(diagnostic.id,{status:'running',metadata:{candidateId,port:candidate.port,connectionId:published.connectionId}});this.store.savePublished(published);this.#scheduleExpiry(published);return published}catch(error){this.options.diagnostics.update(diagnostic.id,{status:'failed',errorCode:String((error as any)?.code??'publish_failed'),error:(error as Error).message});if(existing)this.store.update(existing.id,'failed',{error:(error as Error).message});throw Object.assign(error as Error,{diagnosticSessionId:diagnostic.id})}
  }
  async stop(candidateId:string,input:{confirm?:boolean;signal?:AbortSignal}){if(input.confirm!==true)throw Object.assign(new Error('Stopping a public route requires confirmation.'),{code:'confirmation_required'});const published=this.store.publishedForCandidate(candidateId);if(!published||published.status==='stopped')return published??{stopped:true};const result=await this.#execute(published.contextId,'unpublish',published.port,input.signal);if(result.exitCode!==0)throw Object.assign(new Error('FNGK could not stop the published target.'),{code:'unpublish_failed'});try{const value=JSON.parse(result.output.toString('utf8'));if(value.protocolVersion!=='fngk.publish.v1'||value.type!=='unpublished')throw new Error()}catch{throw Object.assign(new Error('FNGK returned an unsupported unpublish protocol.'),{code:'publish_protocol_invalid'})}const timer=this.#expiryTimers.get(candidateId);if(timer)clearTimeout(timer);this.#expiryTimers.delete(candidateId);return this.store.update(published.id,'stopped',{stoppedAt:new Date().toISOString()})}
  #scheduleExpiry(value:PublishedPort){const expires=value.expiresAt?Date.parse(value.expiresAt):NaN;if(!Number.isFinite(expires))return;const previous=this.#expiryTimers.get(value.candidateId);if(previous)clearTimeout(previous);const timer=setTimeout(()=>{this.#expiryTimers.delete(value.candidateId);void this.stop(value.candidateId,{confirm:true}).catch(error=>this.store.update(value.id,'failed',{error:`Expiry unpublish failed: ${(error as Error).message}`}))},Math.max(0,expires-Date.now()));timer.unref();this.#expiryTimers.set(value.candidateId,timer)}
  close(){for(const timer of this.#expiryTimers.values())clearTimeout(timer);this.#expiryTimers.clear()}
  async reconcile(contextId:string,signal?:AbortSignal){await this.scan(contextId,signal);return this.list(contextId)}
}
