import {DatabaseSync} from 'node:sqlite';
import {dirname} from 'node:path';
import {mkdirSync} from 'node:fs';
import type {HttpPortCandidate,PublishedPort,PortShareStatus} from './types.js';

export class PortShareStore{
  readonly db:DatabaseSync;
  constructor(file:string){if(file!==':memory:')mkdirSync(dirname(file),{recursive:true});this.db=new DatabaseSync(file);this.db.exec(`
    PRAGMA journal_mode=WAL;
    CREATE TABLE IF NOT EXISTS atlas_port_candidates(id TEXT PRIMARY KEY,context_id TEXT NOT NULL,address TEXT NOT NULL,port INTEGER NOT NULL,protocol TEXT NOT NULL,state TEXT NOT NULL,pid INTEGER,process_label TEXT,process_command TEXT,cwd TEXT,exposure TEXT NOT NULL,probe TEXT NOT NULL,probe_status INTEGER,probe_title TEXT,probe_path TEXT NOT NULL,observed_at TEXT NOT NULL,stale INTEGER NOT NULL DEFAULT 0);
    CREATE INDEX IF NOT EXISTS atlas_port_candidates_context ON atlas_port_candidates(context_id,stale,port);
    CREATE TABLE IF NOT EXISTS atlas_published_ports(id TEXT PRIMARY KEY,candidate_id TEXT NOT NULL,context_id TEXT NOT NULL,port INTEGER NOT NULL,connection_id TEXT NOT NULL,hostname TEXT NOT NULL,url TEXT NOT NULL,published_at TEXT NOT NULL,stopped_at TEXT,expires_at TEXT,status TEXT NOT NULL,diagnostic_session_id TEXT,error TEXT);
    CREATE INDEX IF NOT EXISTS atlas_published_ports_context ON atlas_published_ports(context_id,status,port);
  `)}
  upsertCandidates(contextId:string,values:HttpPortCandidate[]){const ids=new Set(values.map(v=>v.id)),statement=this.db.prepare(`INSERT INTO atlas_port_candidates(id,context_id,address,port,protocol,state,pid,process_label,process_command,cwd,exposure,probe,probe_status,probe_title,probe_path,observed_at,stale) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET address=excluded.address,port=excluded.port,pid=excluded.pid,process_label=excluded.process_label,process_command=excluded.process_command,cwd=excluded.cwd,exposure=excluded.exposure,probe=excluded.probe,probe_status=excluded.probe_status,probe_title=excluded.probe_title,probe_path=excluded.probe_path,observed_at=excluded.observed_at,stale=0`);this.db.exec('BEGIN');try{this.db.prepare('UPDATE atlas_port_candidates SET stale=1 WHERE context_id=?').run(contextId);for(const v of values)statement.run(v.id,v.contextId,v.address,v.port,v.protocol,v.state,v.pid??null,v.processLabel?.slice(0,200)??null,v.processCommand?.slice(0,500)??null,v.cwd?.slice(0,2000)??null,v.exposure,v.probe,v.probeStatus??null,v.probeTitle?.slice(0,200)??null,v.probePath,v.observedAt,v.stale?1:0);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}return ids.size}
  candidates(contextId:string):HttpPortCandidate[]{return this.db.prepare('SELECT * FROM atlas_port_candidates WHERE context_id=? ORDER BY stale,port,address').all(contextId).map((r:any)=>this.#candidate(r))}
  getCandidate(id:string):HttpPortCandidate|undefined{const row=this.db.prepare('SELECT * FROM atlas_port_candidates WHERE id=?').get(id) as any;return row&&this.#candidate(row)}
  savePublished(value:PublishedPort){this.db.prepare(`INSERT INTO atlas_published_ports(id,candidate_id,context_id,port,connection_id,hostname,url,published_at,stopped_at,expires_at,status,diagnostic_session_id,error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET connection_id=excluded.connection_id,hostname=excluded.hostname,url=excluded.url,stopped_at=excluded.stopped_at,expires_at=excluded.expires_at,status=excluded.status,diagnostic_session_id=excluded.diagnostic_session_id,error=excluded.error`).run(value.id,value.candidateId,value.contextId,value.port,value.connectionId,value.hostname,value.url,value.publishedAt,value.stoppedAt??null,value.expiresAt??null,value.status,value.diagnosticSessionId??null,value.error?.slice(0,500)??null);return value}
  published(contextId:string):PublishedPort[]{return this.db.prepare('SELECT * FROM atlas_published_ports WHERE context_id=? ORDER BY published_at DESC').all(contextId).map((r:any)=>this.#published(r))}
  activePublished():PublishedPort[]{return this.db.prepare("SELECT * FROM atlas_published_ports WHERE status='published' ORDER BY published_at").all().map((r:any)=>this.#published(r))}
  publishedForCandidate(candidateId:string){const row=this.db.prepare("SELECT * FROM atlas_published_ports WHERE candidate_id=? AND status IN ('publishing','published','stale','failed') ORDER BY published_at DESC LIMIT 1").get(candidateId) as any;return row&&this.#published(row)}
  update(id:string,status:PortShareStatus,patch:{stoppedAt?:string;error?:string}={}){this.db.prepare('UPDATE atlas_published_ports SET status=?,stopped_at=COALESCE(?,stopped_at),error=? WHERE id=?').run(status,patch.stoppedAt??null,patch.error?.slice(0,500)??null,id);const row=this.db.prepare('SELECT * FROM atlas_published_ports WHERE id=?').get(id) as any;return row&&this.#published(row)}
  markStale(candidateId:string){this.db.prepare("UPDATE atlas_published_ports SET status='stale' WHERE candidate_id=? AND status='published'").run(candidateId)}
  expire(now=new Date()){for(const row of this.db.prepare("SELECT id FROM atlas_published_ports WHERE expires_at IS NOT NULL AND expires_at<=? AND status='published'").all(now.toISOString()) as any[])this.update(row.id,'stale')}
  close(){this.db.close()}
  #candidate(r:any):HttpPortCandidate{return{id:r.id,contextId:r.context_id,address:r.address,port:Number(r.port),protocol:'http',state:'listening',pid:r.pid===null?undefined:Number(r.pid),processLabel:r.process_label??undefined,processCommand:r.process_command??undefined,cwd:r.cwd??undefined,exposure:r.exposure,probe:r.probe,probeStatus:r.probe_status===null?undefined:Number(r.probe_status),probeTitle:r.probe_title??undefined,probePath:r.probe_path,observedAt:r.observed_at,stale:Boolean(r.stale)}}
  #published(r:any):PublishedPort{return{id:r.id,candidateId:r.candidate_id,contextId:r.context_id,port:Number(r.port),connectionId:r.connection_id,hostname:r.hostname,url:r.url,publishedAt:r.published_at,stoppedAt:r.stopped_at??undefined,expiresAt:r.expires_at??undefined,status:r.status,diagnosticSessionId:r.diagnostic_session_id??undefined,error:r.error??undefined}}
}
