import { expect, test } from '@playwright/test';
import { writeFile } from 'node:fs/promises';

test('opens the persisted responsive Atlas workbench, files, and a real JSONL terminal', async ({ page }) => {
  const errors: string[] = []; page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByText('ATLAS', { exact: true })).toBeVisible();
  await expect(page.getByText('FILESYSTEM', { exact: true })).toBeVisible();
  await expect(page.locator('.dv-dockview')).toHaveCount(2);
  await expect(page.getByRole('button', { name: 'package.json' })).toBeVisible();
  await page.getByRole('button', { name: 'package.json' }).click();
  await expect(page.locator('.cm-editor')).toBeVisible();
  await expect(page.locator('.cm-content')).toContainText('fngk-atlas');
  expect(errors).toEqual([]);
  await writeFile('/tmp/fngk-atlas-browser-root/package.json','{"name":"changed-outside-atlas"}\n');
  await page.locator('.cm-content').pressSequentially(' ');
  await page.getByRole('button',{name:'Save'}).click();
  await expect(page.locator('.file-panel header')).toContainText('Conflict: file changed on host');
  let closePrompted = false;
  page.once('dialog', async dialog => { closePrompted = true; expect(dialog.message()).toContain('discard unsaved changes'); await dialog.dismiss(); });
  await page.getByRole('button', { name: /Close package\.json/ }).click();
  expect(closePrompted).toBe(true);
  await expect(page.locator('.file-panel')).toHaveCount(1);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: /Close package\.json/ }).click();
  await expect(page.locator('.file-panel')).toHaveCount(0);
  await page.getByRole('button', { name: 'package.json' }).dblclick();
  await expect(page.locator('.cm-editor')).toBeVisible();
  await page.getByRole('button',{name:/binary\.dat/}).click();
  await expect(page.locator('.file-panel:visible header')).toContainText('Binary file · 4 bytes · read-only');
  await expect(page.locator('.file-panel:visible .cm-editor')).toHaveCount(0);
  await page.locator('.explorer').getByRole('button',{name:/package\.json/}).click();await expect(page.locator('.file-panel')).toHaveCount(2);
  const target = page.getByLabel('Terminal target'); await target.fill('fixture-device'); await page.getByRole('button', { name: 'Attach' }).click();
  await expect(page.locator('.terminal-panel header')).toContainText('Live · session-1');
  await expect(page.locator('.xterm-rows')).toContainText('connected');
  await page.locator('.xterm-helper-textarea').pressSequentially('λ');
  await page.getByText('Activity',{exact:true}).click();
  await expect(page.locator('.output-panel pre')).toContainText('terminal · input_ack');
  await page.reload();
  await expect(page.locator('.dv-dockview')).toHaveCount(2);
  await expect(page.getByText('package.json', { exact: true }).first()).toBeVisible();
  await page.setViewportSize({ width: 620, height: 760 });
  await expect(page.locator('.workbench')).toBeVisible(); await expect(page.locator('.explorer')).toBeHidden(); await expect(page.locator('.bottom-dock')).toBeVisible();
  await page.evaluate(()=>localStorage.setItem('atlas.workbench.v1',JSON.stringify({version:1,central:{broken:true},bottom:{broken:true}})));await page.reload();
  await expect(page.getByText('Atlas graph',{exact:true})).toBeVisible();await expect(page.getByText('Terminal',{exact:true})).toBeVisible();
  expect(errors.filter(message=>!message.includes('409 (Conflict)'))).toEqual([]);
});
