import {expect,test} from '@playwright/test';

test('renders contextual search and safe filesystem actions in the FNGK Atlas workbench',async({page})=>{
  const errors:string[]=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');await expect(page.getByText('FNGK Atlas',{exact:true}).first()).toBeVisible();await expect(page.locator('.dv-dockview')).toHaveCount(1);
  await expect(page.locator('.context-rail')).toBeVisible();await expect(page.getByText('Architecture',{exact:true}).first()).toBeVisible();await expect(page.getByText('Functions & coverage',{exact:true}).first()).toBeVisible();await expect(page.getByText('Filesystem',{exact:true}).first()).toBeVisible();await page.locator('.context-rail').getByRole('button',{name:'Atlas process host'}).click();
  await expect(page.getByRole('button',{name:/package\.json/})).toBeVisible();
  await page.getByLabel('Search filesystem').fill('package');await expect(page.getByText('/package.json',{exact:true})).toBeVisible();await page.getByLabel('Search filesystem').fill('');
  const binary=page.locator('.tree-row',{hasText:'binary.dat'});await binary.click({button:'right'});await page.getByRole('menuitem',{name:'Move to trash'}).click();await page.getByRole('button',{name:'Move to trash'}).click();await expect(page.locator('.trash-notice')).toContainText('Restore');await page.locator('.trash-notice').getByRole('button',{name:'Restore'}).click();await expect(page.locator('.trash-notice')).toHaveCount(0);
  await page.getByRole('button',{name:/package\.json/}).click();
  await expect(page.locator('.cm-editor')).toBeVisible();await expect(page.locator('.cm-content')).toContainText('fngk-atlas');await expect(page.locator('.cm-gutters')).toBeVisible();
  await page.locator('.cm-content').click();await expect(page.locator('.cm-cursor')).toBeVisible();
  await page.locator('.context-rail').getByRole('button',{name:/kigathi/}).click();await page.locator('.context-sidebar').getByRole('button',{name:'Open terminal',exact:true}).click();await expect(page.getByText('Terminal',{exact:true}).first()).toBeVisible();await expect(page.locator('.terminal-panel header')).toContainText('Live · session-1');
  const separators=page.locator('.dv-sash');expect(await separators.count()).toBeGreaterThan(1);
  await page.reload();await expect(page.locator('.dv-dockview')).toHaveCount(1);await expect(page.getByText('Filesystem',{exact:true}).first()).toBeVisible();
  await page.locator('.context-rail').getByRole('button',{name:'Atlas process host'}).click();await page.route('**/api/files/search?**',async route=>{await new Promise(resolve=>setTimeout(resolve,350));await route.fulfill({contentType:'application/json',body:JSON.stringify({matches:[{path:'/stale-file.txt',type:'file'}]})});});await page.getByLabel('Search filesystem').fill('stale');await page.locator('.context-rail').getByRole('button',{name:/kigathi/}).click();await page.waitForTimeout(600);await expect(page.getByText('/stale-file.txt',{exact:true})).toHaveCount(0);
  await page.route('**/api/search?**',async route=>{await new Promise(resolve=>setTimeout(resolve,350));await route.fulfill({contentType:'application/json',body:JSON.stringify({items:[{entityId:'stale',type:'function',label:'stale indexed result',path:'src/stale.ts',contextId:'local',repositoryRoot:'/safe-root'}]})});});await page.locator('.context-rail').getByRole('button',{name:'Atlas process host'}).click();await page.getByLabel('Search selected context').fill('stale');await page.locator('.context-rail').getByRole('button',{name:/kigathi/}).click();await page.waitForTimeout(600);await expect(page.getByText('stale indexed result',{exact:true})).toHaveCount(0);
  expect(errors).toEqual([]);
});
