import {verify,createPublicKey} from 'node:crypto';
import {readdir,readFile,stat} from 'node:fs/promises';
import path from 'node:path';
import type {CommandExecutor} from '../transports/terminal-command.js';
import {runInterpreter,validateInterpreterManifest} from './interpreter.js';
import {canonicalSigningPayload} from './registry.js';
import type {InterpreterInput,InterpreterManifest,InterpreterOutput} from './types.js';

export const ATLAS_DEVICE_ADAPTER_VERSION='atlas.device-adapter.v1' as const;
export interface DeviceAdapterManifest{protocolVersion:typeof ATLAS_DEVICE_ADAPTER_VERSION;id:string;version:string;publisher:string;displayName:string;description?:string;command:string;timeoutMs?:number;maxRecords?:number;interpreter:InterpreterManifest}
export interface RegisteredDeviceAdapter{manifest:DeviceAdapterManifest;trusted:boolean;source:'signed'|'development';error?:string}

export function validateDeviceAdapter(value:unknown):{ok:true;manifest:DeviceAdapterManifest}|{ok:false;errors:string[]}{const item=value as Partial<DeviceAdapterManifest>,errors:string[]=[];if(!item||typeof item!=='object')return{ok:false,errors:['adapter must be an object']};if(item.protocolVersion!==ATLAS_DEVICE_ADAPTER_VERSION)errors.push(`protocolVersion must be ${ATLAS_DEVICE_ADAPTER_VERSION}`);for(const field of ['id','version','publisher','displayName','command'] as const)if(typeof item[field]!=='string'||!item[field])errors.push(`${field} is required`);if(String(item.command??'').length>8192)errors.push('command exceeds 8192 characters');if((item.timeoutMs??10_000)>30_000)errors.push('timeoutMs exceeds 30000');if((item.maxRecords??1000)>5000)errors.push('maxRecords exceeds 5000');const interpreter=validateInterpreterManifest(item.interpreter);if(!interpreter.ok)errors.push(...interpreter.errors.map(error=>`interpreter: ${error}`));return errors.length?{ok:false,errors}:{ok:true,manifest:item as DeviceAdapterManifest}}

export async function runDeviceAdapter(manifest:DeviceAdapterManifest,executor:CommandExecutor,contextId:string):Promise<{inputs:InterpreterInput[];output:InterpreterOutput}>{const checked=validateDeviceAdapter(manifest);if(!checked.ok)throw Object.assign(new Error(checked.errors.join('; ')),{code:'invalid_device_adapter'});const result=await executor.execute(manifest.command,{timeoutMs:Math.max(100,manifest.timeoutMs??10_000)});if(result.exitCode!==0)throw Object.assign(new Error(`Device adapter exited with code ${result.exitCode}.`),{code:'device_adapter_failed'});if(result.output.length>4*1024*1024)throw Object.assign(new Error('Device adapter output exceeded 4 MiB.'),{code:'output_limit'});const at=new Date().toISOString(),inputs:InterpreterInput[]=[];for(const [index,line] of result.output.toString('utf8').split(/\r?\n/).entries()){if(!line.trim())continue;if(inputs.length>=(manifest.maxRecords??1000))break;let record:any;try{record=JSON.parse(line)}catch{throw Object.assign(new Error(`Device adapter returned invalid JSONL at line ${index+1}.`),{code:'adapter_protocol_error'})}if(!record||typeof record.kind!=='string'||typeof record.label!=='string')throw Object.assign(new Error(`Device adapter record ${index+1} requires kind and label.`),{code:'adapter_protocol_error'});inputs.push({id:`adapter:${manifest.id}:${String(record.sourceId??index)}`,contextId,kind:record.kind,label:record.label,attributes:record.attributes&&typeof record.attributes==='object'?record.attributes:{},observedAt:typeof record.observedAt==='string'?record.observedAt:at,stale:Boolean(record.stale),source:`device-adapter:${manifest.id}`})}return{inputs,output:runInterpreter(manifest.interpreter,inputs)}}

async function files(root?:string){const found:string[]=[];if(!root)return found;for(const name of await readdir(root).catch(()=>[])){const target=path.join(root,name),info=await stat(target).catch(()=>null);if(info?.isDirectory())found.push(path.join(target,'adapter.json'));else if(name.endsWith('.json'))found.push(target)}return found}
export async function loadDeviceAdapters(options:{production?:boolean;signedDir?:string;devDir?:string;trust?:Record<string,string>}={}):Promise<RegisteredDeviceAdapter[]>{const result:RegisteredDeviceAdapter[]=[];for(const [root,source] of [[options.signedDir,'signed'],[options.devDir,options.production?undefined:'development']] as const){if(!source)continue;for(const file of await files(root)){try{const raw=JSON.parse(await readFile(file,'utf8')),candidate=raw.manifest??raw,checked=validateDeviceAdapter(candidate);if(!checked.ok)throw new Error(checked.errors.join('; '));if(result.some(value=>value.manifest.id===checked.manifest.id))throw new Error('adapter id is already registered');if(source==='signed'){const key=options.trust?.[checked.manifest.publisher];if(!key)throw new Error(`publisher ${checked.manifest.publisher} is not trusted`);if(!verify(null,canonicalSigningPayload(checked.manifest),createPublicKey({key:Buffer.from(key,'base64'),format:'der',type:'spki'}),Buffer.from(String(raw.signature??''),'base64')))throw new Error('adapter signature is invalid')}result.push({manifest:checked.manifest,trusted:source==='signed',source})}catch(error){result.push({manifest:{protocolVersion:ATLAS_DEVICE_ADAPTER_VERSION,id:`invalid:${path.basename(file)}`,version:'0',publisher:'unknown',displayName:path.basename(file),command:'false',interpreter:{protocolVersion:'atlas.interpreter.v1',ontologyVersion:'atlas.world.v1',id:'invalid',version:'0',publisher:'unknown',displayName:'Invalid',inputs:[],outputKinds:[],outputPredicates:[],rules:[]}},trusted:false,source,error:(error as Error).message})}}}return result}
