import {createHash} from 'node:crypto';
import {ATLAS_INTERPRETER_VERSION,ATLAS_WORLD_VERSION,type AtlasAssertion,type AtlasEntity,type InterpreterCondition,type InterpreterInput,type InterpreterManifest,type InterpreterOutput} from './types.js';

const now=()=>new Date().toISOString();
export const worldId=(contextId:string,namespace:string,kind:string,key:string)=>`world:${createHash('sha256').update(`${contextId}\0${namespace}\0${kind}\0${key}`).digest('hex').slice(0,28)}`;
const get=(input:InterpreterInput,path:string):unknown=>path.split('.').reduce<any>((value,key)=>value&&typeof value==='object'?value[key]:undefined,path==='label'?{label:input.label}:{kind:input.kind,source:input.source,attributes:input.attributes});
function condition(input:InterpreterInput,value:InterpreterCondition):boolean{const actual=get(input,value.field);switch(value.op){case'exists':return actual!==undefined&&actual!==null;case'eq':return actual===value.value;case'contains':return String(actual??'').toLowerCase().includes(String(value.value??'').toLowerCase());case'matches':try{return new RegExp(String(value.value??''),'i').test(String(actual??''))}catch{return false}case'in':return Array.isArray(value.value)&&value.value.includes(actual)}}
const matches=(input:InterpreterInput,when:InterpreterManifest['rules'][number]['when'])=>(!when.all||when.all.every(value=>condition(input,value)))&&(!when.any||when.any.some(value=>condition(input,value)));

export function validateInterpreterManifest(value:unknown):{ok:true;manifest:InterpreterManifest}|{ok:false;errors:string[]}{
 const errors:string[]=[],item=value as Partial<InterpreterManifest>;
 if(!item||typeof item!=='object')return{ok:false,errors:['manifest must be an object']};
 if(item.protocolVersion!==ATLAS_INTERPRETER_VERSION)errors.push(`protocolVersion must be ${ATLAS_INTERPRETER_VERSION}`);if(item.ontologyVersion!==ATLAS_WORLD_VERSION)errors.push(`ontologyVersion must be ${ATLAS_WORLD_VERSION}`);
 for(const field of ['id','version','publisher','displayName'] as const)if(typeof item[field]!=='string'||!item[field])errors.push(`${field} is required`);
 if(!Array.isArray(item.inputs)||item.inputs.length>50)errors.push('inputs must contain at most 50 kinds');if(!Array.isArray(item.rules)||item.rules.length>200)errors.push('rules must contain at most 200 entries');
 if(item.stage&&!['recognize','enrich','present'].includes(item.stage))errors.push('stage must be recognize, enrich, or present');
 if(!Array.isArray(item.outputKinds)||item.outputKinds.length>100)errors.push('outputKinds must contain at most 100 kinds');if(!Array.isArray(item.outputPredicates)||item.outputPredicates.length>100)errors.push('outputPredicates must contain at most 100 predicates');
 for(const rule of item.rules??[]){if(!rule?.id||!rule.emit?.explanation)errors.push('every rule requires id and explanation');if((rule.when?.all?.length??0)+(rule.when?.any?.length??0)>20)errors.push(`${rule.id??'rule'} has too many conditions`);for(const test of [...(rule.when?.all??[]),...(rule.when?.any??[])])if(!['eq','contains','matches','exists','in'].includes(test.op))errors.push(`${rule.id}: unsupported condition ${test.op}`);const kind=rule.emit?.kind;if(kind&&Array.isArray(item.outputKinds)&&!item.outputKinds.includes(kind))errors.push(`${rule.id}: undeclared output kind ${kind}`);const predicate=rule.emit?.predicate??(rule.emit?.capability?'provides-capability':undefined);if(predicate&&Array.isArray(item.outputPredicates)&&!item.outputPredicates.includes(predicate))errors.push(`${rule.id}: undeclared output predicate ${predicate}`)}
 if((item.views?.length??0)>20)errors.push('views must contain at most 20 entries');for(const view of item.views??[]){if(!view.id||!view.title)errors.push('every view requires id and title');if(view.appliesTo.length>50)errors.push(`${view.id}: appliesTo must contain at most 50 kinds`);if(view.sections.length>20)errors.push(`${view.id}: views contain at most 20 sections`)}
 return errors.length?{ok:false,errors}:{ok:true,manifest:item as InterpreterManifest};
}

export function runInterpreter(manifest:InterpreterManifest,inputs:InterpreterInput[],clock=now):InterpreterOutput{
 const checked=validateInterpreterManifest(manifest);if(!checked.ok)throw Object.assign(new Error(checked.errors.join('; ')),{code:'invalid_interpreter'});
 const maxInput=Math.min(10_000,manifest.budgets?.maxInput??5000),maxEntities=Math.min(5000,manifest.budgets?.maxEntities??2000),maxAssertions=Math.min(10_000,manifest.budgets?.maxAssertions??5000),derivedAt=clock(),entities=new Map<string,AtlasEntity>(),assertions=new Map<string,AtlasAssertion>();
 for(const input of inputs.slice(0,maxInput)){if(!manifest.inputs.includes('*')&&!manifest.inputs.includes(input.kind))continue;for(const rule of manifest.rules){if(!matches(input,rule.when))continue;const kind=rule.emit.kind??input.kind,label=rule.emit.label??input.label,key=rule.emit.idFrom?String(get(input,rule.emit.idFrom)??input.id):input.id,id=worldId(input.contextId,manifest.id,kind,key),observedAt=input.observedAt||derivedAt;
  if(rule.emit.kind&&!entities.has(id)&&entities.size<maxEntities)entities.set(id,{id,contextId:input.contextId,kind,namespace:manifest.id,label,aliases:[input.label].filter(value=>value!==label),attributes:{sourceId:input.id,...input.attributes},firstObservedAt:observedAt,lastObservedAt:observedAt,stale:Boolean(input.stale)});
  const predicate=rule.emit.predicate??(rule.emit.capability?'provides-capability':undefined);if(predicate&&assertions.size<maxAssertions){let objectId:string|undefined;if(rule.emit.capability||rule.emit.objectKind){const objectKind=rule.emit.objectKind??'capability',objectLabel=rule.emit.capability??rule.emit.objectLabel??objectKind;objectId=worldId(input.contextId,manifest.id,objectKind,objectLabel);if(!entities.has(objectId)&&entities.size<maxEntities)entities.set(objectId,{id:objectId,contextId:input.contextId,kind:objectKind,namespace:manifest.id,label:objectLabel,aliases:[],attributes:{},firstObservedAt:observedAt,lastObservedAt:observedAt,stale:Boolean(input.stale)})}const aid=worldId(input.contextId,manifest.id,'assertion',`${rule.id}:${input.id}:${predicate}:${objectId??''}`);assertions.set(aid,{id:aid,contextId:input.contextId,subjectId:id,predicate,objectId,classification:rule.emit.classification??'derived',confidence:Math.max(0,Math.min(1,rule.emit.confidence??.8)),explanation:rule.emit.explanation,evidence:[{observationId:input.id,method:input.source}],interpreterId:manifest.id,interpreterVersion:manifest.version,observedAt,derivedAt,stale:Boolean(input.stale)})}
 }}return{entities:[...entities.values()],assertions:[...assertions.values()],views:manifest.views??[]};
}

export const workloadInterpreter:InterpreterManifest={protocolVersion:ATLAS_INTERPRETER_VERSION,ontologyVersion:ATLAS_WORLD_VERSION,id:'atlas.workloads',version:'1.0.0',publisher:'atlas',displayName:'Atlas workload semantics',inputs:['service','process','container','repository','database','port'],outputKinds:['workload','capability'],outputPredicates:['provides-capability'],rules:[
 {id:'workload',when:{any:[{field:'kind',op:'in',value:['service','container','repository','database']}]},emit:{kind:'workload',classification:'derived',confidence:.82,explanation:'Operational evidence was grouped into a workload.'}},
 {id:'postgres',when:{any:[{field:'label',op:'matches',value:'postgres(?:ql)?'},{field:'attributes.engine',op:'eq',value:'postgres'}]},emit:{kind:'workload',capability:'relational-storage',confidence:.98,explanation:'PostgreSQL identity or protocol evidence provides relational storage.'}},
 {id:'signal',when:{any:[{field:'label',op:'matches',value:'signal|fngk'},{field:'attributes.command',op:'matches',value:'signal|fngk'}]},emit:{kind:'workload',capability:'remote-machine-control',confidence:.9,explanation:'Signal/FNGK runtime evidence provides remote machine control.'}},
 {id:'docker',when:{any:[{field:'label',op:'matches',value:'docker|containerd'},{field:'kind',op:'eq',value:'container'}]},emit:{kind:'workload',capability:'container-orchestration',confidence:.88,explanation:'Container runtime evidence provides container orchestration.'}},
 {id:'http',when:{all:[{field:'kind',op:'eq',value:'port'}],any:[{field:'attributes.protocol',op:'matches',value:'http'},{field:'label',op:'matches',value:':(?:80|443|3000|4173|8000)\\b'}]},emit:{kind:'workload',capability:'http-serving',confidence:.72,explanation:'A conventional or identified HTTP listener provides HTTP serving.'}}
]};
