import {ATLAS_WORLD_VERSION,type AtlasAssertion,type AtlasEntity,type AtlasProjection} from './types.js';

const lensKinds:Record<string,Set<string>>={overview:new Set(['device','environment','workload','capability','identity','data-store','interface']),runtime:new Set(['device','workload','service','process','job','container','runtime','port','socket','interface']),code:new Set(['workload','repository','package','module','class','function','test']),data:new Set(['workload','capability','data-store','database','table','file']),network:new Set(['workload','interface','port','socket','http-endpoint','external-system']),security:new Set(['device','workload','identity','interface','port','configuration']),activity:new Set(['workload','event','operation','process'])};
export function projectWorld(contextId:string,entities:AtlasEntity[],assertions:AtlasAssertion[],options:{rootId?:string;lens?:string;level?:number;budget?:number;cursor?:string}={}):AtlasProjection{
 const lens=lensKinds[options.lens??'overview']?options.lens??'overview':'overview',level=Math.max(0,Math.min(4,options.level??0)),allowed=lensKinds[lens],byId=new Map(entities.map(value=>[value.id,value])),rootId=options.rootId&&byId.has(options.rootId)?options.rootId:entities.find(value=>value.kind==='device')?.id??entities[0]?.id??`device:${contextId}`;
 let candidates=entities.filter(value=>allowed.has(value.kind)||value.id===rootId);const related=assertions.filter(value=>!value.objectId||byId.has(value.objectId));
 if(options.rootId){const ids=new Set([rootId]);for(let depth=0;depth<=Math.max(1,level);depth++)for(const assertion of related)if(ids.has(assertion.subjectId)||assertion.objectId&&ids.has(assertion.objectId)){ids.add(assertion.subjectId);if(assertion.objectId)ids.add(assertion.objectId)}candidates=candidates.filter(value=>ids.has(value.id));}
 const offset=Math.max(0,Number.parseInt(Buffer.from(options.cursor??'MA==','base64url').toString('utf8'))||0),budget=Math.min(500,Math.max(1,options.budget??100)),page=candidates.sort((a,b)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label)).slice(offset,offset+budget),ids=new Set(page.map(value=>value.id)),edges=related.filter(value=>value.objectId&&ids.has(value.subjectId)&&ids.has(value.objectId)).map(value=>({id:value.id,source:value.subjectId,target:value.objectId!,type:value.predicate,classification:value.classification,confidence:value.confidence,stale:value.stale})),counts=new Map<string,number>();for(const value of candidates.slice(offset+budget))counts.set(value.kind,(counts.get(value.kind)??0)+1);
 const breadcrumb:AtlasProjection['breadcrumbs']=[];let current=byId.get(rootId),guard=0;while(current&&guard++<12){breadcrumb.unshift({id:current.id,label:current.label,kind:current.kind});current=current.parentId?byId.get(current.parentId):undefined}
 return{protocolVersion:ATLAS_WORLD_VERSION,contextId,rootId,lens,level,nodes:page,edges,aggregates:[...counts].map(([kind,count])=>({kind,count})),breadcrumbs:breadcrumb,availableExpansions:level<4?[{level:level+1,label:['Workloads','Runtime and interfaces','Software components','Functions and evidence'][level]??'More detail'}]:[],cursor:offset+budget<candidates.length?Buffer.from(String(offset+budget)).toString('base64url'):undefined,errors:[]};
}
