import {ATLAS_WORLD_VERSION,type AtlasAssertion,type AtlasEntity,type AtlasProjection} from './types.js';

const lensKinds:Record<string,Set<string>>={overview:new Set(['device','environment','workload','capability','identity','data-store','interface']),runtime:new Set(['device','workload','service','process','job','container','runtime','port','socket','interface']),code:new Set(['workload','repository','package','module','class','function','test']),data:new Set(['workload','capability','data-store','database','table','file']),network:new Set(['workload','interface','port','socket','http-endpoint','external-system']),security:new Set(['device','workload','identity','interface','port','configuration']),activity:new Set(['workload','event','operation','process'])};
const detailLevel:Record<string,Record<string,number>>={
 overview:{device:0,environment:0,workload:0,capability:0,identity:0,'data-store':0,interface:0},
 runtime:{device:0,workload:0,service:1,container:1,runtime:1,process:2,job:2,port:2,socket:2,interface:2},
 code:{workload:0,repository:0,package:1,module:2,class:3,test:3,function:4},
 data:{workload:0,capability:0,'data-store':0,database:1,table:2,file:3},
 network:{workload:0,interface:0,'external-system':1,port:2,socket:2,'http-endpoint':3},
 security:{device:0,workload:0,identity:1,interface:1,port:2,configuration:3},
 activity:{workload:0,process:1,operation:2,event:3},
};
export function projectWorld(contextId:string,entities:AtlasEntity[],assertions:AtlasAssertion[],options:{rootId?:string;lens?:string;level?:number;budget?:number;cursor?:string}={}):AtlasProjection{
 const lens=lensKinds[options.lens??'overview']?options.lens??'overview':'overview',level=Math.max(0,Math.min(4,options.level??0)),allowed=lensKinds[lens],byId=new Map(entities.map(value=>[value.id,value])),rootId=options.rootId&&byId.has(options.rootId)?options.rootId:entities.find(value=>value.kind==='device')?.id??entities[0]?.id??`device:${contextId}`;
 const related=assertions.filter(value=>!value.objectId||byId.has(value.objectId));let allCandidates=entities.filter(value=>allowed.has(value.kind)||value.id===rootId);
 if(options.rootId){const ids=new Set([rootId]);for(let depth=0;depth<=Math.max(1,level);depth++)for(const assertion of related)if(ids.has(assertion.subjectId)||assertion.objectId&&ids.has(assertion.objectId)){ids.add(assertion.subjectId);if(assertion.objectId)ids.add(assertion.objectId)}allCandidates=allCandidates.filter(value=>ids.has(value.id));}
 const candidates=allCandidates.filter(value=>value.id===rootId||(detailLevel[lens]?.[value.kind]??4)<=level),offset=Math.max(0,Number.parseInt(Buffer.from(options.cursor??'MA==','base64url').toString('utf8'))||0),budget=Math.min(500,Math.max(1,options.budget??100)),sorted=candidates.sort((a,b)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label)),visible=sorted.slice(offset,offset+budget),strongest=(id:string)=>related.filter(value=>value.subjectId===id||value.objectId===id).sort((a,b)=>b.confidence-a.confidence)[0],page=visible.map(value=>{const evidence=strongest(value.id);return{...value,classification:evidence?.classification,confidence:evidence?.confidence}}),ids=new Set(page.map(value=>value.id)),edges=related.filter(value=>value.objectId&&ids.has(value.subjectId)&&ids.has(value.objectId)).map(value=>({id:value.id,source:value.subjectId,target:value.objectId!,type:value.predicate,classification:value.classification,confidence:value.confidence,stale:value.stale})),counts=new Map<string,number>();for(const value of [...allCandidates.filter(value=>value.id!==rootId&&(detailLevel[lens]?.[value.kind]??4)>level),...sorted.slice(offset+budget)])counts.set(value.kind,(counts.get(value.kind)??0)+1);
 const breadcrumb:AtlasProjection['breadcrumbs']=[];let current=byId.get(rootId),guard=0;while(current&&guard++<12){breadcrumb.unshift({id:current.id,label:current.label,kind:current.kind});current=current.parentId?byId.get(current.parentId):undefined}
 const workloads=entities.filter(value=>value.kind==='workload'&&(!options.rootId||value.id===rootId||value.workloadId===rootId));
 const cards=workloads.slice(0,80).map(value=>{const relatedAssertions=related.filter(item=>item.subjectId===value.id),caps=relatedAssertions.filter(item=>item.predicate==='provides-capability').map(item=>byId.get(item.objectId??'')?.label).filter(Boolean) as string[],members=Number((value.attributes.memberObservationIds as unknown[]|undefined)?.length??0);return{id:value.id,kind:'workload',title:value.label,status:(value.stale?'stale':'current') as 'current'|'stale',purpose:caps.length?caps.join(' · '):'Observed workload',facts:[{label:'Evidence',value:String(members)},{label:'Capabilities',value:String(caps.length)},{label:'Confidence',value:`${Math.round(Math.max(...relatedAssertions.map(item=>item.confidence),.5)*100)}%`}],confidence:Math.max(...relatedAssertions.map(item=>item.confidence),.5)}});
 const attention=entities.filter(value=>value.stale&&value.kind==='workload').slice(0,5).map(value=>`${value.label} is stale`);
 return{protocolVersion:ATLAS_WORLD_VERSION,contextId,rootId,lens,level,nodes:page,edges,aggregates:[...counts].map(([kind,count])=>({kind,count})),cards:!options.rootId&&lens==='overview'&&level===0?cards:undefined,synthesis:{title:options.rootId?(byId.get(rootId)?.label??'Selected entity'):'Device overview',summary:options.rootId?'Inspecting the selected semantic entity and its connected evidence.':`${cards.length} logical workload${cards.length===1?'':'s'} resolved from the current Device evidence.`,attention},breadcrumbs:breadcrumb,availableExpansions:level<4?[{level:level+1,label:['Workloads','Runtime and interfaces','Software components','Functions and evidence'][level]??'More detail'}]:[],cursor:offset+budget<candidates.length?Buffer.from(String(offset+budget)).toString('base64url'):undefined,errors:[]};
}
