import {readdir,readFile,stat} from 'node:fs/promises';import path from 'node:path';import {verify,createPublicKey} from 'node:crypto';import {validateInterpreterManifest} from './interpreter.js';import type {InterpreterManifest} from './types.js';
export interface RegisteredInterpreter{manifest:InterpreterManifest;trusted:boolean;source:'builtin'|'signed'|'development';error?:string}
export const canonicalSigningPayload=(value:unknown)=>Buffer.from(canonical(value));
const canonical=(value:any):string=>value===null||typeof value!=='object'?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(',')}]`:`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
export const interpreterSigningPayload=(manifest:InterpreterManifest)=>canonicalSigningPayload(manifest);
async function manifests(root:string){const found:string[]=[];for(const name of await readdir(root).catch(()=>[])){const target=path.join(root,name),info=await stat(target).catch(()=>null);if(info?.isDirectory())found.push(path.join(target,'interpreter.json'));else if(name.endsWith('.json'))found.push(target)}return found}
export async function loadInterpreterRegistry(options:{production?:boolean;signedDir?:string;devDir?:string;trust?:Record<string,string>;builtins?:InterpreterManifest[]}={}):Promise<RegisteredInterpreter[]>{const result:RegisteredInterpreter[]=(options.builtins??[]).map(manifest=>({manifest,trusted:true,source:'builtin'})),seen=new Set(result.map(value=>value.manifest.id));
 for(const file of options.signedDir?await manifests(options.signedDir):[]){try{const envelope=JSON.parse(await readFile(file,'utf8')),checked=validateInterpreterManifest(envelope.manifest);if(!checked.ok)throw new Error(checked.errors.join('; '));const key=options.trust?.[checked.manifest.publisher];if(!key)throw new Error(`publisher ${checked.manifest.publisher} is not trusted`);const publicKey=createPublicKey({key:Buffer.from(key,'base64'),format:'der',type:'spki'}),signature=Buffer.from(String(envelope.signature??''),'base64');if(!verify(null,interpreterSigningPayload(checked.manifest),publicKey,signature))throw new Error('interpreter signature is invalid');if(seen.has(checked.manifest.id))throw new Error('interpreter id is already registered');seen.add(checked.manifest.id);result.push({manifest:checked.manifest,trusted:true,source:'signed'})}catch(error){result.push({manifest:{protocolVersion:'atlas.interpreter.v1',ontologyVersion:'atlas.world.v1',id:`invalid:${path.basename(file)}`,version:'0',publisher:'unknown',displayName:path.basename(file),inputs:[],outputKinds:[],outputPredicates:[],rules:[]},trusted:false,source:'signed',error:(error as Error).message})}}
 if(options.devDir&&!options.production)for(const file of await manifests(options.devDir)){try{const raw=JSON.parse(await readFile(file,'utf8')),checked=validateInterpreterManifest(raw.manifest??raw);if(!checked.ok)throw new Error(checked.errors.join('; '));if(seen.has(checked.manifest.id))throw new Error('interpreter id is already registered');seen.add(checked.manifest.id);result.push({manifest:checked.manifest,trusted:false,source:'development'})}catch(error){result.push({manifest:{protocolVersion:'atlas.interpreter.v1',ontologyVersion:'atlas.world.v1',id:`invalid:${path.basename(file)}`,version:'0',publisher:'development',displayName:path.basename(file),inputs:[],outputKinds:[],outputPredicates:[],rules:[]},trusted:false,source:'development',error:(error as Error).message})}}
 return result}
