import {createHash} from 'node:crypto';
import {ATLAS_INTERPRETER_VERSION,ATLAS_WORLD_VERSION,type AtlasAssertion,type AtlasEntity,type AtlasObservation,type InterpreterInput,type InterpreterManifest,type InterpreterOutput} from './types.js';
import {runInterpreter,workloadInterpreter,worldId} from './interpreter.js';
import {projectWorld} from './projector.js';
import {WorldStore} from './store.js';
import type {RegisteredInterpreter} from './registry.js';

const kindMap:Record<string,string>={filesystem:'data-store',endpoint:'http-endpoint',external:'external-system',flow:'resource',coverage:'resource',command:'operation',terminal:'operation',output:'event'};
const legacyManifest:InterpreterManifest={protocolVersion:ATLAS_INTERPRETER_VERSION,ontologyVersion:ATLAS_WORLD_VERSION,id:'atlas.compatibility',version:'1.0.0',publisher:'atlas',displayName:'Atlas compatibility interpreter',inputs:['*'],outputKinds:[],outputPredicates:[],rules:[]};
const stable=(value:string)=>createHash('sha256').update(value).digest('hex').slice(0,28);
export class WorldService{
 constructor(readonly store:WorldStore,readonly extensions:RegisteredInterpreter[]=[]){for(const item of extensions)this.store.register(item.manifest,item.trusted,item.source,item.error)}
 refresh(contextId:string,nodes:any[],edges:any[],device?:{id?:string;name?:string;online?:boolean}){const at=new Date().toISOString(),deviceId=worldId(contextId,'atlas.core','device',contextId),observations:AtlasObservation[]=nodes.slice(0,10000).map(node=>({id:`observation:${stable(`${contextId}:node:${node.id}`)}`,contextId,kind:String(node.type??'resource'),source:'atlas-existing-evidence',sourceId:String(node.id),observedAt:String(node.observedAt??at),facts:{label:node.label??node.name??node.id,...node},sensitivity:'safe-metadata'}));observations.push(...edges.slice(0,20000).map(edge=>({id:`observation:${stable(`${contextId}:edge:${edge.id}`)}`,contextId,kind:'relationship',source:'atlas-existing-evidence',sourceId:String(edge.id),observedAt:String(edge.observedAt??at),facts:{...edge},sensitivity:'safe-metadata' as const})));this.store.putObservations(observations);
  const sourceNodes=nodes.slice(0,10000),mapped=new Map<string,string>(),entities:AtlasEntity[]=[{id:deviceId,contextId,kind:'device',namespace:'atlas.core',label:device?.name??(contextId==='local'?'Atlas process host':contextId.replace(/^device:/,'')),aliases:[contextId],attributes:{online:device?.online??true,sourceId:device?.id??contextId},firstObservedAt:at,lastObservedAt:at,stale:device?.online===false}],assertions:AtlasAssertion[]=[];
  for(const node of sourceNodes){const kind=kindMap[String(node.type)]??String(node.type??'resource');mapped.set(String(node.id),worldId(contextId,legacyManifest.id,kind,String(node.id)))}
  for(const node of sourceNodes){const kind=kindMap[String(node.type)]??String(node.type??'resource'),id=mapped.get(String(node.id))!;entities.push({id,contextId,kind,namespace:legacyManifest.id,label:String(node.label??node.name??node.id),aliases:[String(node.qualifiedName??''),String(node.path??'')].filter(Boolean),parentId:node.parent?mapped.get(String(node.parent)):undefined,attributes:{...node,legacyId:node.id},firstObservedAt:String(node.observedAt??at),lastObservedAt:String(node.observedAt??at),stale:Boolean(node.stale)});assertions.push(this.assertion(contextId,deviceId,'contains',id,node,at))}
  for(const edge of edges.slice(0,20000)){const source=mapped.get(String(edge.source)),target=mapped.get(String(edge.target));if(source&&target)assertions.push(this.assertion(contextId,source,String(edge.type??'related-to'),target,edge,at))}
  const compatibility:InterpreterOutput={entities,assertions,views:[{id:'atlas.core.evidence',title:'Evidence',appliesTo:['*'],priority:0,sections:[{kind:'properties',title:'Identity'},{kind:'relationships',title:'Relationships'},{kind:'evidence',title:'Why Atlas believes this'},{kind:'timeline',title:'Recent changes'}]}]};this.store.register(legacyManifest);this.store.sync(contextId,legacyManifest,compatibility);
  const inputs:InterpreterInput[]=nodes.slice(0,10000).map(node=>({id:`observation:${stable(`${contextId}:node:${node.id}`)}`,contextId,kind:String(node.type??'resource'),label:String(node.label??node.name??node.id),attributes:{...(node.metadata??node),legacyId:node.id},observedAt:String(node.observedAt??at),stale:Boolean(node.stale),source:'atlas-existing-evidence'}));const semantic=runInterpreter(workloadInterpreter,inputs);for(const entity of semantic.entities)if(entity.kind==='workload'){const contained=this.assertion(contextId,deviceId,'contains',entity.id,{source:'workload-interpreter'},at,'derived',.82,'The workload was derived from evidence observed on this Device.');contained.interpreterId=workloadInterpreter.id;contained.interpreterVersion=workloadInterpreter.version;semantic.assertions.push(contained);const legacyId=String(entity.attributes.legacyId??'');const realized=legacyId&&mapped.get(legacyId);if(realized){const assertion=this.assertion(contextId,entity.id,'realizes',realized,{source:'workload-interpreter'},at,'derived',.9,'The workload is realized by this observed runtime or software entity.');assertion.interpreterId=workloadInterpreter.id;assertion.interpreterVersion=workloadInterpreter.version;semantic.assertions.push(assertion)}}this.store.register(workloadInterpreter);this.store.sync(contextId,workloadInterpreter,semantic);for(const item of this.extensions){if(item.error)continue;try{this.store.sync(contextId,item.manifest,runInterpreter(item.manifest,inputs))}catch(error){this.store.register(item.manifest,item.trusted,item.source,(error as Error).message)}}
 }
 ingest(manifest:InterpreterManifest,inputs:InterpreterInput[],output:InterpreterOutput){this.store.putObservations(inputs.map(input=>({id:input.id,contextId:input.contextId,kind:input.kind,source:input.source,sourceId:input.id,observedAt:input.observedAt,facts:{label:input.label,...input.attributes},sensitivity:'safe-metadata'})));this.store.register(manifest);for(const contextId of new Set(inputs.map(value=>value.contextId)))this.store.sync(contextId,manifest,{entities:output.entities.filter(value=>value.contextId===contextId),assertions:output.assertions.filter(value=>value.contextId===contextId),views:output.views})}
 private assertion(contextId:string,subjectId:string,predicate:string,objectId:string,evidence:any,at:string,classification:AtlasAssertion['classification']='observed',confidence=.95,explanation='Existing Atlas evidence directly supports this relationship.'):AtlasAssertion{const id=worldId(contextId,'atlas.compatibility','assertion',`${subjectId}:${predicate}:${objectId}`);return{id,contextId,subjectId,predicate,objectId,classification,confidence,explanation,evidence:[{observationId:String(evidence.id??evidence.source??objectId),method:'atlas-existing-evidence'}],interpreterId:'atlas.compatibility',interpreterVersion:'1.0.0',observedAt:String(evidence.observedAt??at),derivedAt:at,stale:Boolean(evidence.stale)}}
 projection(contextId:string,options:Parameters<typeof projectWorld>[3]){return projectWorld(contextId,this.store.entities(contextId),this.store.assertions(contextId),options)}
}
