import {DatabaseSync} from 'node:sqlite';
import {dirname} from 'node:path';
import {mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import type {AtlasAssertion,AtlasEntity,AtlasObservation,AtlasViewDescriptor,InterpreterManifest,InterpreterOutput} from './types.js';
import type {AtlasCorrection} from './corrections.js';

const json=(value:unknown)=>JSON.stringify(value??{}),hash=(value:unknown)=>createHash('sha256').update(json(value)).digest('hex');
const observationSchema=`
  CREATE TABLE IF NOT EXISTS atlas_world_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS atlas_world_observations(id TEXT PRIMARY KEY,context_id TEXT NOT NULL,kind TEXT NOT NULL,source TEXT NOT NULL,source_id TEXT NOT NULL,observed_at TEXT NOT NULL,scan_id TEXT,route_json TEXT NOT NULL,facts_json TEXT NOT NULL,sensitivity TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS atlas_world_observations_context ON atlas_world_observations(context_id,observed_at DESC);
  CREATE TABLE IF NOT EXISTS atlas_world_corrections(id TEXT PRIMARY KEY,context_id TEXT NOT NULL,subject_id TEXT NOT NULL,kind TEXT NOT NULL,value_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(context_id,subject_id,kind));
  CREATE INDEX IF NOT EXISTS atlas_world_corrections_subject ON atlas_world_corrections(context_id,subject_id);
`;
const derivedSchema=`
  CREATE TABLE IF NOT EXISTS atlas_world_entities(id TEXT PRIMARY KEY,context_id TEXT NOT NULL,kind TEXT NOT NULL,namespace TEXT NOT NULL,label TEXT NOT NULL,aliases_json TEXT NOT NULL,parent_id TEXT,workload_id TEXT,attributes_json TEXT NOT NULL,first_observed_at TEXT NOT NULL,last_observed_at TEXT NOT NULL,stale INTEGER NOT NULL DEFAULT 0,content_hash TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS atlas_world_entities_context_kind ON atlas_world_entities(context_id,kind);
  CREATE TABLE IF NOT EXISTS atlas_world_assertions(id TEXT PRIMARY KEY,context_id TEXT NOT NULL,subject_id TEXT NOT NULL,predicate TEXT NOT NULL,object_id TEXT,value_json TEXT,classification TEXT NOT NULL,confidence REAL NOT NULL,explanation TEXT NOT NULL,evidence_json TEXT NOT NULL,interpreter_id TEXT NOT NULL,interpreter_version TEXT NOT NULL,observed_at TEXT NOT NULL,derived_at TEXT NOT NULL,stale INTEGER NOT NULL DEFAULT 0,content_hash TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS atlas_world_assertions_subject ON atlas_world_assertions(context_id,subject_id,predicate);
  CREATE TABLE IF NOT EXISTS atlas_world_changes(id INTEGER PRIMARY KEY AUTOINCREMENT,context_id TEXT NOT NULL,item_id TEXT NOT NULL,item_type TEXT NOT NULL,change_type TEXT NOT NULL,interpreter_id TEXT NOT NULL,changed_at TEXT NOT NULL,summary_json TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS atlas_world_changes_context_time ON atlas_world_changes(context_id,changed_at DESC);
  CREATE TABLE IF NOT EXISTS atlas_world_interpreters(id TEXT PRIMARY KEY,version TEXT NOT NULL,publisher TEXT NOT NULL,manifest_json TEXT NOT NULL,trusted INTEGER NOT NULL,source TEXT NOT NULL,status TEXT NOT NULL,error TEXT,updated_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS atlas_world_views(id TEXT NOT NULL,interpreter_id TEXT NOT NULL,descriptor_json TEXT NOT NULL,PRIMARY KEY(id,interpreter_id));
  CREATE TABLE IF NOT EXISTS atlas_world_samples(context_id TEXT NOT NULL,entity_id TEXT NOT NULL,metric TEXT NOT NULL,value REAL NOT NULL,unit TEXT NOT NULL,observed_at TEXT NOT NULL,PRIMARY KEY(context_id,entity_id,metric,observed_at));
  CREATE INDEX IF NOT EXISTS atlas_world_samples_context_time ON atlas_world_samples(context_id,observed_at DESC);
  CREATE VIRTUAL TABLE IF NOT EXISTS atlas_world_search USING fts5(context_id UNINDEXED,entity_id UNINDEXED,kind UNINDEXED,label,aliases,detail,namespace UNINDEXED,tokenize='unicode61');
`;
const dropDerivedSchema=`
  DROP TABLE IF EXISTS atlas_world_search;
  DROP TABLE IF EXISTS atlas_world_views;
  DROP TABLE IF EXISTS atlas_world_interpreters;
  DROP TABLE IF EXISTS atlas_world_samples;
  DROP TABLE IF EXISTS atlas_world_changes;
  DROP TABLE IF EXISTS atlas_world_assertions;
  DROP TABLE IF EXISTS atlas_world_entities;
`;
export interface WorldSample{contextId:string;entityId:string;metric:string;value:number;unit:string;observedAt:string}
export class WorldStore{
 readonly db:DatabaseSync;
 constructor(file:string){if(file!==':memory:')mkdirSync(dirname(file),{recursive:true});this.db=new DatabaseSync(file);this.db.exec(`PRAGMA journal_mode=WAL;${observationSchema}`);if(this.schemaVersion()!==2)this.resetDerivedWorld();else this.db.exec(derivedSchema)}
 schemaVersion(){return Number((this.db.prepare("SELECT value FROM atlas_world_meta WHERE key='schema_version'").get() as any)?.value??0)}
 resetDerivedWorld(){this.db.exec('BEGIN IMMEDIATE');try{this.db.exec(dropDerivedSchema);this.db.exec(derivedSchema);this.db.prepare("INSERT INTO atlas_world_meta(key,value) VALUES('schema_version','2') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
 putObservations(values:AtlasObservation[]){const stmt=this.db.prepare(`INSERT INTO atlas_world_observations(id,context_id,kind,source,source_id,observed_at,scan_id,route_json,facts_json,sensitivity) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,source=excluded.source,source_id=excluded.source_id,observed_at=excluded.observed_at,scan_id=excluded.scan_id,route_json=excluded.route_json,facts_json=excluded.facts_json,sensitivity=excluded.sensitivity WHERE kind<>excluded.kind OR source<>excluded.source OR source_id<>excluded.source_id OR COALESCE(scan_id,'')<>COALESCE(excluded.scan_id,'') OR route_json<>excluded.route_json OR facts_json<>excluded.facts_json OR sensitivity<>excluded.sensitivity`);this.db.exec('BEGIN');try{for(const value of values.slice(0,10000))stmt.run(value.id,value.contextId,value.kind,value.source,value.sourceId,value.observedAt,value.scanId??null,json(value.route),json(value.facts),value.sensitivity);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
 observations(contextId:string){return(this.db.prepare('SELECT * FROM atlas_world_observations WHERE context_id=? ORDER BY observed_at,id').all(contextId) as any[]).map(row=>({id:row.id,contextId:row.context_id,kind:row.kind,source:row.source,sourceId:row.source_id,observedAt:row.observed_at,scanId:row.scan_id??undefined,route:JSON.parse(row.route_json),facts:JSON.parse(row.facts_json),sensitivity:row.sensitivity})) as AtlasObservation[]}
 putSamples(values:WorldSample[]){if(!values.length)return;const insert=this.db.prepare('INSERT INTO atlas_world_samples(context_id,entity_id,metric,value,unit,observed_at) VALUES(?,?,?,?,?,?) ON CONFLICT(context_id,entity_id,metric,observed_at) DO UPDATE SET value=excluded.value,unit=excluded.unit'),contexts=new Map<string,string>();this.db.exec('BEGIN');try{for(const value of values.slice(0,20000)){if(!Number.isFinite(value.value))continue;insert.run(value.contextId,value.entityId,value.metric,value.value,value.unit,value.observedAt);const latest=contexts.get(value.contextId);if(!latest||value.observedAt>latest)contexts.set(value.contextId,value.observedAt)}for(const [contextId,latest] of contexts){this.db.prepare("DELETE FROM atlas_world_samples WHERE context_id=? AND julianday(observed_at)<julianday(?)-1").run(contextId,latest);this.db.prepare('DELETE FROM atlas_world_samples WHERE rowid IN (SELECT rowid FROM atlas_world_samples WHERE context_id=? ORDER BY observed_at DESC,rowid DESC LIMIT -1 OFFSET 10000)').run(contextId)}this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
 samples(contextId:string,entityId?:string,since?:string){let rows:any[];if(entityId&&since)rows=this.db.prepare('SELECT * FROM atlas_world_samples WHERE context_id=? AND entity_id=? AND observed_at>=? ORDER BY observed_at,metric').all(contextId,entityId,since) as any[];else if(entityId)rows=this.db.prepare('SELECT * FROM atlas_world_samples WHERE context_id=? AND entity_id=? ORDER BY observed_at,metric').all(contextId,entityId) as any[];else if(since)rows=this.db.prepare('SELECT * FROM atlas_world_samples WHERE context_id=? AND observed_at>=? ORDER BY observed_at,metric').all(contextId,since) as any[];else rows=this.db.prepare('SELECT * FROM atlas_world_samples WHERE context_id=? ORDER BY observed_at,metric').all(contextId) as any[];return rows.map(row=>({contextId:row.context_id,entityId:row.entity_id,metric:row.metric,value:row.value,unit:row.unit,observedAt:row.observed_at})) as WorldSample[]}
 register(manifest:InterpreterManifest,trusted=true,source='builtin',error?:string){this.db.prepare(`INSERT INTO atlas_world_interpreters(id,version,publisher,manifest_json,trusted,source,status,error,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,publisher=excluded.publisher,manifest_json=excluded.manifest_json,trusted=excluded.trusted,source=excluded.source,status=excluded.status,error=excluded.error,updated_at=excluded.updated_at`).run(manifest.id,manifest.version,manifest.publisher,json(manifest),trusted?1:0,source,error?'error':'healthy',error??null,new Date().toISOString())}
 sync(contextId:string,manifest:InterpreterManifest,output:InterpreterOutput){const at=new Date().toISOString(),entityUpsert=this.db.prepare(`INSERT INTO atlas_world_entities(id,context_id,kind,namespace,label,aliases_json,parent_id,workload_id,attributes_json,first_observed_at,last_observed_at,stale,content_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,namespace=excluded.namespace,label=excluded.label,aliases_json=excluded.aliases_json,parent_id=excluded.parent_id,workload_id=excluded.workload_id,attributes_json=excluded.attributes_json,last_observed_at=excluded.last_observed_at,stale=excluded.stale,content_hash=excluded.content_hash`),assertionUpsert=this.db.prepare(`INSERT INTO atlas_world_assertions(id,context_id,subject_id,predicate,object_id,value_json,classification,confidence,explanation,evidence_json,interpreter_id,interpreter_version,observed_at,derived_at,stale,content_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_id=excluded.object_id,value_json=excluded.value_json,classification=excluded.classification,confidence=excluded.confidence,explanation=excluded.explanation,evidence_json=excluded.evidence_json,interpreter_version=excluded.interpreter_version,observed_at=excluded.observed_at,derived_at=excluded.derived_at,stale=excluded.stale,content_hash=excluded.content_hash`),change=this.db.prepare('INSERT INTO atlas_world_changes(context_id,item_id,item_type,change_type,interpreter_id,changed_at,summary_json) VALUES(?,?,?,?,?,?,?)'),searchDelete=this.db.prepare('DELETE FROM atlas_world_search WHERE entity_id=?'),searchInsert=this.db.prepare('INSERT INTO atlas_world_search(context_id,entity_id,kind,label,aliases,detail,namespace) VALUES(?,?,?,?,?,?,?)'),entityDelete=this.db.prepare('DELETE FROM atlas_world_entities WHERE id=?'),assertionDelete=this.db.prepare('DELETE FROM atlas_world_assertions WHERE id=?');this.db.exec('BEGIN');try{
  const ownedEntities=this.db.prepare('SELECT id,content_hash contentHash FROM atlas_world_entities WHERE context_id=? AND namespace=?').all(contextId,manifest.id) as Array<{id:string;contentHash:string}>,priorEntities=new Map(ownedEntities.map(value=>[value.id,value.contentHash])),ownedAssertions=this.db.prepare('SELECT id,content_hash contentHash FROM atlas_world_assertions WHERE context_id=? AND interpreter_id=?').all(contextId,manifest.id) as Array<{id:string;contentHash:string}>,priorAssertions=new Map(ownedAssertions.map(value=>[value.id,value.contentHash])),entityIds=new Set(output.entities.map(value=>value.id)),assertionIds=new Set(output.assertions.map(value=>value.id));
  for(const value of output.entities){const content=hash({...value,firstObservedAt:undefined,lastObservedAt:undefined}),prior=priorEntities.get(value.id);if(prior===content)continue;entityUpsert.run(value.id,value.contextId,value.kind,value.namespace,value.label,json(value.aliases),value.parentId??null,value.workloadId??null,json(value.attributes),value.firstObservedAt,value.lastObservedAt,value.stale?1:0,content);change.run(contextId,value.id,'entity',prior?'changed':'introduced',manifest.id,at,json({kind:value.kind,label:value.label}));searchDelete.run(value.id);searchInsert.run(value.contextId,value.id,value.kind,value.label,value.aliases.join(' '),json(value.attributes),value.namespace)}
  for(const value of output.assertions){const content=hash({...value,observedAt:undefined,derivedAt:undefined}),prior=priorAssertions.get(value.id);if(prior===content)continue;assertionUpsert.run(value.id,value.contextId,value.subjectId,value.predicate,value.objectId??null,value.value===undefined?null:json(value.value),value.classification,value.confidence,value.explanation,json(value.evidence),value.interpreterId,value.interpreterVersion,value.observedAt,value.derivedAt,value.stale?1:0,content);change.run(contextId,value.id,'assertion',prior?'changed':'introduced',manifest.id,at,json({predicate:value.predicate,subjectId:value.subjectId,objectId:value.objectId}))}
  for(const value of ownedAssertions)if(!assertionIds.has(value.id)){change.run(contextId,value.id,'assertion','withdrawn',manifest.id,at,'{}');assertionDelete.run(value.id)}
  for(const value of ownedEntities)if(!entityIds.has(value.id)){change.run(contextId,value.id,'entity','withdrawn',manifest.id,at,'{}');searchDelete.run(value.id);entityDelete.run(value.id)}
  const existingViews=new Map((this.db.prepare('SELECT id,descriptor_json descriptor FROM atlas_world_views WHERE interpreter_id=?').all(manifest.id) as Array<{id:string;descriptor:string}>).map(value=>[value.id,value.descriptor])),nextViews=new Set((output.views??[]).map(value=>value.id)),viewUpsert=this.db.prepare('INSERT INTO atlas_world_views(id,interpreter_id,descriptor_json) VALUES(?,?,?) ON CONFLICT(id,interpreter_id) DO UPDATE SET descriptor_json=excluded.descriptor_json'),viewDelete=this.db.prepare('DELETE FROM atlas_world_views WHERE id=? AND interpreter_id=?');for(const value of output.views??[]){const descriptor=json(value);if(existingViews.get(value.id)!==descriptor)viewUpsert.run(value.id,manifest.id,descriptor)}for(const id of existingViews.keys())if(!nextViews.has(id))viewDelete.run(id,manifest.id);
  this.prune(contextId,at);this.db.exec('COMMIT')
 }catch(error){this.db.exec('ROLLBACK');throw error}}
 private prune(contextId:string,at:string){this.db.prepare('DELETE FROM atlas_world_changes WHERE context_id=? AND julianday(changed_at)<julianday(?)-7').run(contextId,at);this.db.prepare('DELETE FROM atlas_world_changes WHERE id IN (SELECT id FROM atlas_world_changes WHERE context_id=? ORDER BY changed_at DESC,id DESC LIMIT -1 OFFSET 25000)').run(contextId);this.db.prepare('DELETE FROM atlas_world_observations WHERE context_id=? AND julianday(observed_at)<julianday(?)-7').run(contextId,at)}
 entities(contextId:string){return(this.db.prepare('SELECT * FROM atlas_world_entities WHERE context_id=? ORDER BY kind,label').all(contextId) as any[]).map(row=>({id:row.id,contextId:row.context_id,kind:row.kind,namespace:row.namespace,label:row.label,aliases:JSON.parse(row.aliases_json),parentId:row.parent_id??undefined,workloadId:row.workload_id??undefined,attributes:JSON.parse(row.attributes_json),firstObservedAt:row.first_observed_at,lastObservedAt:row.last_observed_at,stale:Boolean(row.stale)})) as AtlasEntity[]}
 assertions(contextId:string,entityId?:string){const rows=entityId?this.db.prepare('SELECT * FROM atlas_world_assertions WHERE context_id=? AND (subject_id=? OR object_id=?) ORDER BY confidence DESC').all(contextId,entityId,entityId):this.db.prepare('SELECT * FROM atlas_world_assertions WHERE context_id=? ORDER BY confidence DESC').all(contextId);return(rows as any[]).map(row=>({id:row.id,contextId:row.context_id,subjectId:row.subject_id,predicate:row.predicate,objectId:row.object_id??undefined,value:row.value_json?JSON.parse(row.value_json):undefined,classification:row.classification,confidence:row.confidence,explanation:row.explanation,evidence:JSON.parse(row.evidence_json),interpreterId:row.interpreter_id,interpreterVersion:row.interpreter_version,observedAt:row.observed_at,derivedAt:row.derived_at,stale:Boolean(row.stale)})) as AtlasAssertion[]}
 entity(id:string){const found=(this.db.prepare('SELECT context_id contextId FROM atlas_world_entities WHERE id=?').get(id) as any);if(!found)return null;const entities=this.entities(found.contextId),entity=entities.find(value=>value.id===id),assertions=this.assertions(found.contextId,id),relatedIds=new Set(assertions.flatMap(value=>[value.subjectId,value.objectId].filter(Boolean) as string[]));return{entity,assertions,relatedEntities:entities.filter(value=>relatedIds.has(value.id)),views:(this.db.prepare('SELECT descriptor_json descriptor FROM atlas_world_views').all() as any[]).map(value=>JSON.parse(value.descriptor) as AtlasViewDescriptor).filter(value=>value.appliesTo.includes('*')||value.appliesTo.includes(entity?.kind??'')).sort((a,b)=>(b.priority??0)-(a.priority??0)||a.title.localeCompare(b.title))}}
 timeline(contextId:string,itemId?:string,limit=200){const rows=itemId?this.db.prepare('SELECT * FROM atlas_world_changes WHERE context_id=? AND item_id=? ORDER BY changed_at DESC LIMIT ?').all(contextId,itemId,Math.min(500,limit)):this.db.prepare('SELECT * FROM atlas_world_changes WHERE context_id=? ORDER BY changed_at DESC LIMIT ?').all(contextId,Math.min(500,limit));return(rows as any[]).map(row=>({id:row.id,itemId:row.item_id,itemType:row.item_type,changeType:row.change_type,interpreterId:row.interpreter_id,changedAt:row.changed_at,summary:JSON.parse(row.summary_json)}))}
 search(contextId:string,query:string,limit=100){const tokens=query.normalize('NFKC').trim().split(/\s+/).map(value=>value.replace(/[^\p{L}\p{N}_.:/-]/gu,'')).filter(Boolean).slice(0,8);if(!tokens.length)return[];const match=tokens.map(value=>`"${value.replaceAll('"','')}"*`).join(' AND ');try{return this.db.prepare('SELECT s.context_id contextId,s.entity_id entityId,s.kind,s.label,s.detail,s.namespace,bm25(atlas_world_search) rank,e.workload_id workloadId,owner.label workloadLabel FROM atlas_world_search s LEFT JOIN atlas_world_entities e ON e.id=s.entity_id LEFT JOIN atlas_world_entities owner ON owner.id=e.workload_id WHERE atlas_world_search MATCH ? AND s.context_id=? ORDER BY rank LIMIT ?').all(match,contextId,Math.min(250,limit))}catch{return[]}}
 corrections(contextId:string,subjectId?:string):AtlasCorrection[]{const rows=subjectId?this.db.prepare('SELECT * FROM atlas_world_corrections WHERE context_id=? AND subject_id=? ORDER BY kind').all(contextId,subjectId):this.db.prepare('SELECT * FROM atlas_world_corrections WHERE context_id=? ORDER BY subject_id,kind').all(contextId);return(rows as any[]).map(row=>({id:row.id,contextId:row.context_id,subjectId:row.subject_id,kind:row.kind,value:JSON.parse(row.value_json),createdAt:row.created_at,updatedAt:row.updated_at}))}
 correctionById(id:string):AtlasCorrection|undefined{const row=this.db.prepare('SELECT * FROM atlas_world_corrections WHERE id=?').get(id) as any;return row?{id:row.id,contextId:row.context_id,subjectId:row.subject_id,kind:row.kind,value:JSON.parse(row.value_json),createdAt:row.created_at,updatedAt:row.updated_at}:undefined}
 putCorrection(value:{id:string;contextId:string;subjectId:string;kind:string;value:unknown;createdAt:string;updatedAt:string}){this.db.prepare('INSERT INTO atlas_world_corrections(id,context_id,subject_id,kind,value_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(context_id,subject_id,kind) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at').run(value.id,value.contextId,value.subjectId,value.kind,json(value.value),value.createdAt,value.updatedAt)}
 deleteCorrections(contextId:string,subjectId:string,kind?:string){return kind?this.db.prepare('DELETE FROM atlas_world_corrections WHERE context_id=? AND subject_id=? AND kind=?').run(contextId,subjectId,kind).changes:this.db.prepare('DELETE FROM atlas_world_corrections WHERE context_id=? AND subject_id=?').run(contextId,subjectId).changes}
 interpreters(){return(this.db.prepare('SELECT id,version,publisher,trusted,source,status,error,updated_at updatedAt FROM atlas_world_interpreters ORDER BY id').all() as any[]).map(value=>({...value,trusted:Boolean(value.trusted)}))}
 close(){this.db.close()}
}
