import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {afterEach,describe,expect,it} from 'vitest';
import {runInterpreter,validateInterpreterManifest,workloadInterpreter} from '../../src/world/interpreter.js';
import {projectWorld} from '../../src/world/projector.js';
import {WorldService} from '../../src/world/service.js';
import {WorldStore} from '../../src/world/store.js';

const cleanups:Array<()=>Promise<void>>=[];afterEach(async()=>{while(cleanups.length)await cleanups.pop()?.()});
describe('semantic Device atlas',()=>{
 it('validates and deterministically executes data-only interpreter specifications',()=>{expect(validateInterpreterManifest(workloadInterpreter)).toMatchObject({ok:true});const input=[{id:'process:1',contextId:'device:one',kind:'process',label:'postgres',attributes:{command:'/usr/bin/postgres'},observedAt:'2026-09-14T00:00:00Z',source:'terminal'}],left=runInterpreter(workloadInterpreter,input,()=> '2026-09-14T00:01:00Z'),right=runInterpreter(workloadInterpreter,input,()=> '2026-09-14T00:01:00Z');expect(left).toEqual(right);expect(left.entities).toEqual(expect.arrayContaining([expect.objectContaining({kind:'workload'}),expect.objectContaining({kind:'capability',label:'relational-storage'})]));expect(left.assertions).toContainEqual(expect.objectContaining({predicate:'provides-capability',classification:'derived',confidence:.98}))});
 it('lifts existing evidence into workloads, provenance, search, and bounded projections',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'atlas-world-')),store=new WorldStore(path.join(directory,'atlas.db')),world=new WorldService(store);cleanups.push(async()=>{store.close();await rm(directory,{recursive:true,force:true})});world.refresh('device:one',[{id:'service:signal',type:'service',label:'Signal API',metadata:{command:'node dist/server.js'}},{id:'process:postgres',type:'process',label:'postgres',metadata:{command:'/usr/bin/postgres'}},{id:'port:3000',type:'port',label:':3000',metadata:{protocol:'http'}}],[{id:'runs',source:'service:signal',target:'port:3000',type:'served_by'}],{name:'kigathi',online:true});const entities=store.entities('device:one'),assertions=store.assertions('device:one');expect(entities).toEqual(expect.arrayContaining([expect.objectContaining({kind:'device',label:'kigathi'}),expect.objectContaining({kind:'workload'}),expect.objectContaining({kind:'capability',label:'remote-machine-control'})]));expect(assertions.some(value=>value.predicate==='provides-capability')).toBe(true);expect(store.search('device:one','Signal')).not.toHaveLength(0);const projection=projectWorld('device:one',entities,assertions,{lens:'overview',budget:3});expect(projection.protocolVersion).toBe('atlas.world.v1');expect(projection.nodes.length).toBeLessThanOrEqual(3);expect(projection.cursor||projection.aggregates.length).toBeTruthy();expect(store.interpreters()).toHaveLength(2)});
 it('retains conflicting assertions instead of silently replacing them',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'atlas-world-')),store=new WorldStore(path.join(directory,'atlas.db'));cleanups.push(async()=>{store.close();await rm(directory,{recursive:true,force:true})});const entity={id:'entity',contextId:'local',kind:'workload',namespace:'one',label:'Web',aliases:[],attributes:{},firstObservedAt:'2026-09-14T00:00:00Z',lastObservedAt:'2026-09-14T00:00:00Z',stale:false},manifest={...workloadInterpreter,id:'one'},manifestTwo={...workloadInterpreter,id:'two'},base={contextId:'local',subjectId:'entity',predicate:'provides-capability',classification:'inferred' as const,confidence:.5,explanation:'fixture',evidence:[],interpreterVersion:'1',observedAt:'2026-09-14T00:00:00Z',derivedAt:'2026-09-14T00:00:00Z',stale:false};store.sync('local',manifest,{entities:[entity],assertions:[{...base,id:'a',interpreterId:'one',value:'http'}],views:[]});store.sync('local',manifestTwo,{entities:[],assertions:[{...base,id:'b',interpreterId:'two',value:'not-http'}],views:[]});expect(store.assertions('local','entity')).toHaveLength(2)});
 it('reveals finer code structure by semantic zoom and preserves mixed-kind parents',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'atlas-world-')),store=new WorldStore(path.join(directory,'atlas.db')),world=new WorldService(store);cleanups.push(async()=>{store.close();await rm(directory,{recursive:true,force:true})});world.refresh('local',[{id:'repo',type:'repository',label:'Atlas'},{id:'module',type:'module',label:'world.ts',parent:'repo'},{id:'fn',type:'function',label:'projectWorld',parent:'module'}],[],{name:'host',online:true});const entities=store.entities('local'),repo=entities.find(value=>value.label==='Atlas')!,module=entities.find(value=>value.label==='world.ts')!,fn=entities.find(value=>value.label==='projectWorld')!;expect(module.parentId).toBe(repo.id);expect(fn.parentId).toBe(module.id);expect(projectWorld('local',entities,store.assertions('local'),{lens:'code',level:0}).nodes.map(value=>value.kind)).not.toContain('function');expect(projectWorld('local',entities,store.assertions('local'),{lens:'code',level:4}).nodes.map(value=>value.kind)).toContain('function')});
});
