import { createHash } from 'node:crypto';
import path from 'node:path';
import ts from 'typescript';
import { FileService } from '../files/file-service.js';

export interface RepositoryTarget { contextId: string; path: string; revision?: string }
export interface AnalysisBatch { nodes: any[]; edges: any[]; complete: boolean; index: RepositoryIndex }
export interface RepositoryIndex { id: string; contextId: string; root: string; revision?: string; fingerprint: string; nodes: any[]; edges: any[]; summary: Record<string, unknown> }
const sourceExtensions = new Set(['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.svelte', '.py', '.php', '.go']);
const ignored = new Set(['.git', '.worktrees', 'node_modules', 'vendor', 'dist', 'build', 'web-dist', '.svelte-kit', 'coverage', '.next', '.cache', 'target', '__pycache__', '.atlas']);
const digest = (value: string) => createHash('sha256').update(value).digest('hex').slice(0, 20);
const idFor = (root: string, kind: string, key: string) => `${kind}:${digest(`${root}\0${key}`)}`;
const normalize = (value: string) => value.replaceAll('\\', '/').replace(/^\.\//, '');
const branchKinds = new Set([ts.SyntaxKind.IfStatement, ts.SyntaxKind.ForStatement, ts.SyntaxKind.ForInStatement, ts.SyntaxKind.ForOfStatement, ts.SyntaxKind.WhileStatement, ts.SyntaxKind.DoStatement, ts.SyntaxKind.CaseClause, ts.SyntaxKind.CatchClause, ts.SyntaxKind.ConditionalExpression]);

function inferredFlows(text:string) {
  const values:Array<{kind:string;label:string;edge:string}>=[],seen=new Set<string>();
  const collect=(kind:string,edge:string,pattern:RegExp)=>{for(const match of text.matchAll(pattern)){const label=match[1]??match[2];const key=`${kind}:${label}`;if(label&&!seen.has(key)){seen.add(key);values.push({kind,label,edge});}}};
  collect('endpoint','handles',/\.(?:get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/gi);
  collect('endpoint','requests',/fetch\s*\(\s*['"`]([^'"`]+)['"`]/gi);
  collect('event','emits',/\.emit\s*\(\s*['"`]([^'"`]+)['"`]/gi);
  collect('event','subscribes',/\.(?:on|once|subscribe)\s*\(\s*['"`]([^'"`]+)['"`]/gi);
  collect('table','queries',/\b(?:from|into|update|join)\s+["`]?([a-z_][\w.]*)/gi);
  return values;
}

function scriptKind(extension: string) { return extension === '.tsx' ? ts.ScriptKind.TSX : extension === '.jsx' ? ts.ScriptKind.JSX : ['.js', '.mjs', '.cjs'].includes(extension) ? ts.ScriptKind.JS : ts.ScriptKind.TS; }
function functionName(node: any, source: ts.SourceFile): string {
  if (node.name?.getText) return node.name.getText(source); const parent = node.parent;
  if (ts.isVariableDeclaration(parent) || ts.isPropertyAssignment(parent) || ts.isMethodDeclaration(parent)) return parent.name?.getText(source) ?? '<anonymous>';
  return '<anonymous>';
}
function analyzeTypeScript(text: string, file: string) {
  const extension = path.posix.extname(file), script = extension === '.svelte' ? [...text.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(match => match[1]).join('\n') : text;
  const source = ts.createSourceFile(file, script, ts.ScriptTarget.Latest, true, scriptKind(extension)), functions: any[] = [], imports: string[] = [];
  for (const statement of source.statements) if (ts.isImportDeclaration(statement) && ts.isStringLiteral(statement.moduleSpecifier)) imports.push(statement.moduleSpecifier.text);
  const visit = (node: ts.Node, parentQualified = '') => {
    const isFunction = ts.isFunctionDeclaration(node) || ts.isMethodDeclaration(node) || ts.isFunctionExpression(node) || ts.isArrowFunction(node) || ts.isConstructorDeclaration(node) || ts.isGetAccessorDeclaration(node) || ts.isSetAccessorDeclaration(node); let qualified = parentQualified;
    if (isFunction) {
      const value = node as ts.FunctionLikeDeclaration, name = ts.isConstructorDeclaration(node) ? 'constructor' : functionName(node, source), start = source.getLineAndCharacterOfPosition(node.getStart(source)), endLine = source.getLineAndCharacterOfPosition(node.end).line + 1;
      qualified = parentQualified ? `${parentQualified}.${name}` : name; let branches = 0, statements = 0, maximumNesting = 0; const calls: string[] = [];
      const scan = (child: ts.Node, depth = 0) => { if (child !== node && ts.isFunctionLike(child)) return; if (branchKinds.has(child.kind)) branches++; if (ts.isBinaryExpression(child) && [ts.SyntaxKind.AmpersandAmpersandToken, ts.SyntaxKind.BarBarToken, ts.SyntaxKind.QuestionQuestionToken].includes(child.operatorToken.kind)) branches++; if (ts.isStatement(child)) statements++; if (ts.isCallExpression(child)) calls.push(child.expression.getText(source).slice(0, 160)); const next = branchKinds.has(child.kind) ? depth + 1 : depth; maximumNesting = Math.max(maximumNesting, next); ts.forEachChild(child, value => scan(value, next)); };
      if (value.body) scan(value.body); const parameters = value.parameters.map(parameter => ({ name: parameter.name.getText(source), optional: Boolean(parameter.questionToken || parameter.initializer), rest: Boolean(parameter.dotDotDotToken), type: parameter.type?.getText(source) ?? null })), modifiers = ts.canHaveModifiers(node) ? ts.getModifiers(node)?.map(modifier => modifier.getText(source)) ?? [] : [];
      functions.push({ name, qualifiedName: qualified, kind: ts.SyntaxKind[node.kind], line: start.line + 1, column: start.character + 1, endLine, physicalLines: endLine - start.line, executableLines: Math.max(1, statements), statements, complexity: branches + 1, maxNesting: maximumNesting, parameters, arity: parameters.length, requiredArity: parameters.filter(parameter => !parameter.optional && !parameter.rest).length, async: modifiers.includes('async'), exported: modifiers.includes('export'), calls: [...new Set(calls)], language: extension === '.svelte' ? 'Svelte' : 'TypeScript/JavaScript' });
    }
    ts.forEachChild(node, child => visit(child, qualified));
  };
  visit(source); return { functions, imports };
}
function analyzeStructural(text: string, extension: string) {
  const functions: any[] = [], lines = text.split(/\r?\n/), pattern = extension === '.go' ? /^\s*func\s+(?:\([^)]*\)\s*)?([\w$]+)\s*\(([^)]*)\)/ : extension === '.py' ? /^\s*(?:async\s+)?def\s+([\w$]+)\s*\(([^)]*)\)/ : /^\s*(?:public\s+|private\s+|protected\s+|static\s+|final\s+|abstract\s+)*function\s+&?\s*([\w$]+)\s*\(([^)]*)\)/;
  for (let index = 0; index < lines.length; index++) { const match = lines[index].match(pattern); if (!match) continue; const parameters = match[2].trim() ? match[2].split(',').map(rawValue => { const raw = rawValue.trim(), pieces = raw.split(/\s+/), python = extension === '.py'; return { name: python ? raw.split(/[=:]/)[0].replace(/^\*+/, '') : extension === '.go' ? pieces[0]?.replace(/^\.\.\./, '') : pieces.at(-1)?.replace(/^&?\$/, ''), optional: python ? raw.includes('=') || raw.startsWith('*') : extension === '.php' ? raw.includes('=') : false, rest: raw.includes('...') || raw.startsWith('*'), type: null }; }) : []; const indent = lines[index].match(/^\s*/)?.[0].length ?? 0; let end = index; if (extension === '.py') { while (end + 1 < lines.length && (!lines[end + 1].trim() || (lines[end + 1].match(/^\s*/)?.[0].length ?? 0) > indent)) end++; } else { let depth = 0, started = false; for (let cursor = index; cursor < lines.length; cursor++) { for (const character of lines[cursor]) { if (character === '{') { depth++; started = true; } else if (character === '}') depth--; } end = cursor; if (started && depth <= 0) break; } } const body = lines.slice(index, end + 1).join('\n'), branches = (body.match(/\b(if|for|foreach|while|case|catch)\b|&&|\|\|/g) ?? []).length; functions.push({ name: match[1], qualifiedName: match[1], kind: extension === '.go' ? 'GoFunc' : extension === '.py' ? 'PythonFunction' : 'PhpFunction', line: index + 1, column: indent + 1, endLine: end + 1, physicalLines: end - index + 1, executableLines: Math.max(1, end - index + 1), statements: Math.max(1, end - index), complexity: branches + 1, maxNesting: 0, parameters, arity: parameters.length, requiredArity: parameters.filter(parameter => !parameter.optional && !parameter.rest).length, async: extension === '.py' && /async\s+def/.test(lines[index]), exported: extension === '.go' ? /^[A-Z]/.test(match[1]) : extension === '.py' ? !match[1].startsWith('_') : true, calls: [], language: extension === '.go' ? 'Go' : extension === '.py' ? 'Python' : 'PHP', analysisConfidence: 'structural' }); }
  return { functions, imports: [] as string[] };
}

export async function* analyzeRepository(repository: RepositoryTarget, files: FileService, signal?: AbortSignal, options: { maxFiles?: number; batchSize?: number } = {}): AsyncIterable<AnalysisBatch> {
  const maximum = options.maxFiles ?? 6000, batchSize = options.batchSize ?? 200, queue = [repository.path], sourcePaths: string[] = [], manifestPaths: string[] = [];
  while (queue.length && sourcePaths.length + manifestPaths.length < maximum) { if (signal?.aborted) throw Object.assign(new Error('Analysis cancelled.'), { code: 'cancelled' }); const directory = queue.pop()!; let cursor: string | null | undefined; do { const page = await files.list({ contextId: repository.contextId, path: directory }, { limit: 500, cursor }); for (const item of page.items) { if (item.type === 'directory' && !ignored.has(item.name)) queue.push(item.path); else if (item.type === 'file' && sourceExtensions.has(path.posix.extname(item.name).toLowerCase())) sourcePaths.push(item.path); else if (item.type === 'file' && ['package.json', 'composer.json', 'go.mod', 'pyproject.toml', 'requirements.txt'].includes(item.name)) manifestPaths.push(item.path); if (sourcePaths.length + manifestPaths.length >= maximum) break; } cursor = page.nextCursor; } while (cursor && sourcePaths.length + manifestPaths.length < maximum); }
  const rootKey = `${repository.contextId}:${repository.path}`, repoId = idFor(rootKey, 'repo', repository.path), nodes: any[] = [{ id: repoId, type: 'repository', label: path.posix.basename(repository.path), path: repository.path, root: repository.path, parent: null, contextId: repository.contextId }], edges: any[] = [], packages: any[] = [];
  for (const manifestPath of manifestPaths) { const opened = await files.read({ contextId: repository.contextId, path: manifestPath }); const relativeDirectory = normalize(path.posix.relative(repository.path, path.posix.dirname(manifestPath))) || '.', name = path.posix.basename(manifestPath); let manifest: any = {}; try { manifest = opened.text ? JSON.parse(opened.text) : {}; } catch {} const ecosystem = name === 'package.json' ? 'npm' : name === 'composer.json' ? 'Composer' : name === 'go.mod' ? 'Go modules' : 'Python', packageNode = { id: idFor(rootKey, 'package', `${ecosystem}:${relativeDirectory}`), type: 'package', label: manifest.name ?? relativeDirectory, path: relativeDirectory, parent: repoId, ecosystem, dependencies: name === 'package.json' ? { runtime: manifest.dependencies ?? {}, development: manifest.devDependencies ?? {} } : { runtime: manifest.require ?? {} } }; packages.push(packageNode); nodes.push(packageNode); edges.push({ id: `contains:${repoId}:${packageNode.id}`, source: repoId, target: packageNode.id, type: 'contains' }); for (const [scope, dependencies] of Object.entries(packageNode.dependencies)) for (const [dependency, version] of Object.entries(dependencies as Record<string, unknown>)) { const dependencyId = idFor(rootKey, 'external', `${ecosystem}:${dependency}`); if (!nodes.some(node => node.id === dependencyId)) nodes.push({ id: dependencyId, type: 'external', label: dependency, parent: null, ecosystem, version }); edges.push({ id: `depends:${packageNode.id}:${dependencyId}:${scope}`, source: packageNode.id, target: dependencyId, type: 'depends_on', scope }); } }
  const modules = new Map<string, any>(), symbols = new Map<string, any[]>(), moduleImports = new Map<string, string[]>();
  for (const sourcePath of sourcePaths) { if (signal?.aborted) throw Object.assign(new Error('Analysis cancelled.'), { code: 'cancelled' }); const opened = await files.read({ contextId: repository.contextId, path: sourcePath }); if (!opened.text) continue; const relative = normalize(path.posix.relative(repository.path, sourcePath)), extension = path.posix.extname(sourcePath).toLowerCase(), analysis = ['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.svelte'].includes(extension) ? analyzeTypeScript(opened.text, relative) : analyzeStructural(opened.text, extension), packageNode = packages.filter(value => relative === value.path || relative.startsWith(value.path === '.' ? '' : `${value.path}/`)).sort((left, right) => right.path.length - left.path.length)[0], moduleId = idFor(rootKey, 'module', relative), moduleNode = { id: moduleId, type: 'module', label: path.posix.basename(relative), path: relative, parent: packageNode?.id ?? repoId, language: analysis.functions[0]?.language ?? extension.slice(1), metrics: { lines: opened.text.split(/\r?\n/).length, functions: analysis.functions.length } }; modules.set(relative, moduleNode); moduleImports.set(relative, analysis.imports); nodes.push(moduleNode); edges.push({ id: `contains:${moduleNode.parent}:${moduleId}`, source: moduleNode.parent, target: moduleId, type: 'contains' }); for (const item of analysis.functions) { const functionNode = { ...item, id: idFor(rootKey, 'function', `${relative}:${item.qualifiedName}:${item.line}:${item.column ?? 1}`), type: 'function', label: item.name, path: relative, parent: moduleId }; nodes.push(functionNode); edges.push({ id: `contains:${moduleId}:${functionNode.id}`, source: moduleId, target: functionNode.id, type: 'contains' }); for (const name of [item.name, item.qualifiedName]) symbols.set(name, [...(symbols.get(name) ?? []), functionNode]); } if (nodes.length % batchSize === 0) yield { nodes: nodes.slice(-batchSize), edges: [], complete: false, index: { id: repoId, contextId: repository.contextId, root: repository.path, revision: repository.revision, fingerprint: '', nodes, edges, summary: {} } }; }
  for (const [modulePath, moduleNode] of modules) {
    const testModule=/(^|\/)(?:test|tests|__tests__)(\/|$)|\.(?:test|spec)\.[^.]+$/i.test(modulePath);moduleNode.test=testModule;
    for(const child of nodes.filter(node=>node.parent===moduleNode.id&&node.type==='function'))child.test=testModule;
    const opened=await files.read({contextId:repository.contextId,path:path.posix.join(repository.path,modulePath)});
    for(const flow of inferredFlows(opened.text??'')){const flowId=idFor(rootKey,flow.kind,flow.label);if(!nodes.some(node=>node.id===flowId))nodes.push({id:flowId,type:flow.kind,label:flow.label,parent:null,confidence:'inferred'});edges.push({id:`${flow.edge}:${moduleNode.id}:${flowId}`,source:moduleNode.id,target:flowId,type:flow.edge,confidence:'inferred',evidence:{kind:'static-pattern',path:modulePath}});}
  }
  for (const [modulePath, values] of moduleImports) { const source = modules.get(modulePath); for (const specifier of values) { if (!specifier.startsWith('.')) continue; const base = normalize(path.posix.normalize(path.posix.join(path.posix.dirname(modulePath), specifier))), target = [base, ...['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.svelte'].map(extension => `${base}${extension}`), ...['index.ts', 'index.tsx', 'index.js'].map(name => `${base}/${name}`)].map(candidate => modules.get(candidate)).find(Boolean); if (target) edges.push({ id: `imports:${source.id}:${target.id}`, source: source.id, target: target.id, type: 'imports', confidence: 'resolved-path' }); } }
  for (const functionNode of nodes.filter(node => node.type === 'function')) for (const call of functionNode.calls ?? []) { const name = call.split('.').at(-1)?.replace(/[^\w$].*$/, ''), targets = [...new Map((symbols.get(name ?? '') ?? []).map(target => [target.id, target])).values()]; if (targets.length === 1) edges.push({ id: `calls:${functionNode.id}:${targets[0].id}`, source: functionNode.id, target: targets[0].id, type: 'calls', confidence: 'resolved-name' }); }
  try {
    const declared=await files.read({contextId:repository.contextId,path:path.posix.join(repository.path,'.atlas','flows.json')}),flow=JSON.parse(declared.text??'{}'),aliases=new Map<string,string>();
    for(const item of Array.isArray(flow.nodes)?flow.nodes:[]){if(typeof item?.id!=='string'||typeof item?.label!=='string')continue;const id=idFor(rootKey,'declared-flow',item.id);aliases.set(item.id,id);nodes.push({id,type:item.type??'flow',label:item.label,parent:repoId,confidence:'declared',metadata:item.metadata??{}});}
    for(const item of Array.isArray(flow.edges)?flow.edges:[]){const source=aliases.get(item?.source)??modules.get(normalize(item?.source??''))?.id,target=aliases.get(item?.target)??modules.get(normalize(item?.target??''))?.id;if(source&&target)edges.push({id:`declared:${source}:${target}:${item.type??'flows_to'}`,source,target,type:item.type??'flows_to',confidence:'declared',evidence:{kind:'atlas-flow-manifest'}});}
  } catch {}
  const summary = { files: sourcePaths.length, functions: nodes.filter(node => node.type === 'function').length, packages: packages.length, languages: [...new Set([...modules.values()].map(node => node.language))], generatedAt: new Date().toISOString() }, fingerprint = digest(nodes.map(node => `${node.id}:${node.physicalLines ?? ''}:${node.complexity ?? ''}`).join('|')), index = { id: repoId, contextId: repository.contextId, root: repository.path, revision: repository.revision, fingerprint, nodes, edges, summary };
  yield { nodes, edges, complete: true, index };
}
