import {spawn,type ChildProcess} from 'node:child_process';import {createServer} from 'node:net';import {randomBytes,randomUUID} from 'node:crypto';import type {DatabaseConnection,DatabaseRuntime,DatabaseSession} from './types.js';
type RuntimeRecord={session:DatabaseSession;token:string;origin:string;child:ChildProcess;timer:NodeJS.Timeout};
const safeVersion=(value:string)=>{const match=/^(\d+)\.(\d+)\.(\d+)$/.exec(value);if(!match)return false;const parts=match.slice(1).map(Number);return parts[0]>7||parts[0]===7&&(parts[1]>1||parts[1]===1&&parts[2]>=9)};
async function freePort(){return await new Promise<number>((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();if(!address||typeof address==='string')return reject(new Error('No loopback port available.'));server.close(error=>error?reject(error):resolve(address.port));});});}
export class DbGateSupervisor implements DatabaseRuntime{
  #records=new Map<string,RuntimeRecord>();constructor(readonly options:{command?:string;args?:string[];version?:string;uid?:number;ttlMs?:number;startupMs?:number}={}){}
  async start(connection:DatabaseConnection){const command=this.options.command??process.env.DBGATE_COMMAND,version=this.options.version??process.env.DBGATE_VERSION??'';if(!command)throw Object.assign(new Error('DbGate sidecar is not configured.'),{code:'database_runtime_unavailable'});if(!safeVersion(version))throw Object.assign(new Error('DbGate 7.1.9 or newer is required.'),{code:'unsafe_sidecar_version'});const currentUid=typeof process.getuid==='function'?process.getuid():undefined,uid=this.options.uid??(process.env.DBGATE_UID?Number(process.env.DBGATE_UID):undefined);if(currentUid===0&&(!Number.isInteger(uid)||uid===0))throw Object.assign(new Error('DbGate must run as an explicit non-root UID.'),{code:'sidecar_root_denied'});
    const id=randomUUID(),port=await freePort(),token=randomBytes(24).toString('base64url'),ttl=this.options.ttlMs??30*60_000,createdAt=new Date(),expiresAt=new Date(createdAt.getTime()+ttl),proxyPath=`/api/databases/sessions/${id}/workbench/`,engine=`${connection.engine}@dbgate-plugin-${connection.engine==='mariadb'?'mysql':connection.engine}`;
    const environment:NodeJS.ProcessEnv={PATH:process.env.PATH,HOME:process.env.DBGATE_HOME??'/tmp',PORT:String(port),WEB_ROOT:proxyPath,CONNECTIONS:'atlas',LABEL_atlas:connection.label??connection.database??connection.engine,SERVER_atlas:connection.host,PORT_atlas:String(connection.port??''),DATABASE_atlas:connection.database??'',USER_atlas:connection.user??'',PASSWORD_atlas:connection.password??'',ENGINE_atlas:engine,READONLY_atlas:connection.readOnly?'1':'0',SHELL_SCRIPTING:'0',SHELL_CONNECTION:'0',TOKEN_LIFETIME:`${Math.ceil(ttl/1000)}s`,NODE_ENV:'production'};
    const child=spawn(command,this.options.args??[],{env:environment,stdio:['ignore','ignore','pipe'],uid});const session:DatabaseSession={id,contextId:connection.contextId,engine:connection.engine,label:connection.label??connection.database??connection.engine,status:'starting',createdAt:createdAt.toISOString(),expiresAt:expiresAt.toISOString(),proxyPath,pid:child.pid};const origin=`http://127.0.0.1:${port}`;let stderr='';child.stderr?.on('data',chunk=>stderr=(stderr+chunk.toString()).slice(-1000));child.once('exit',()=>{if(session.status!=='stopped'&&session.status!=='expired'){session.status='failed';session.error=stderr.replace(/password\s*[:=]\s*\S+/ig,'password=[redacted]')}});const timer=setTimeout(()=>void this.stop(id,'expired'),ttl);timer.unref();const record={session,token,origin,child,timer};this.#records.set(id,record);
    const deadline=Date.now()+(this.options.startupMs??15_000);while(Date.now()<deadline){if(child.exitCode!==null)break;try{const response=await fetch(`${origin}${proxyPath}`,{redirect:'manual'});if(response.status<500){session.status='live';return {session:{...session},token,origin};}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}await this.stop(id);throw Object.assign(new Error(stderr||'DbGate did not become ready.'),{code:'sidecar_start_failed'});
  }
  list(){return [...this.#records.values()].map(value=>({...value.session}));}get(id:string){const value=this.#records.get(id);return value?{session:{...value.session},token:value.token,origin:value.origin}:undefined;}
  async stop(id:string,reason:'stopped'|'expired'='stopped'){const value=this.#records.get(id);if(!value)return false;clearTimeout(value.timer);value.session.status=reason;value.child.kill('SIGTERM');this.#records.delete(id);return true;}async close(){await Promise.all([...this.#records].map(([id])=>this.stop(id)));}
}
